/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessPermissionAssignment {
    #[serde(rename = "access_id", skip_serializing_if = "Option::is_none")]
    pub access_id: Option<String>,
    #[serde(rename = "access_type", skip_serializing_if = "Option::is_none")]
    pub access_type: Option<String>,
    #[serde(rename = "sub_claims", skip_serializing_if = "Option::is_none")]
    pub sub_claims: Option<std::collections::HashMap<String, Vec<String>>>,
}

impl AccessPermissionAssignment {
    pub fn new() -> AccessPermissionAssignment {
        AccessPermissionAssignment {
            access_id: None,
            access_type: None,
            sub_claims: None,
        }
    }
}

