/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AccountCustomFieldCreate : accountCustomFieldCreate is a command that creates a new custom field in the account settings
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountCustomFieldCreate {
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// The name of the custom field
    #[serde(rename = "name")]
    pub name: String,
    /// The object to create the custom field
    #[serde(rename = "object")]
    pub object: String,
    /// The object type to create the custom field [e.g. STATIC_SECRET,DYNAMIC_SECRET,ROTATED_SECRET]
    #[serde(rename = "object-type")]
    pub object_type: String,
    /// Specify whether the custom field is mandatory
    #[serde(rename = "required", skip_serializing_if = "Option::is_none")]
    pub required: Option<bool>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl AccountCustomFieldCreate {
    /// accountCustomFieldCreate is a command that creates a new custom field in the account settings
    pub fn new(name: String, object: String, object_type: String) -> AccountCustomFieldCreate {
        AccountCustomFieldCreate {
            json: None,
            name,
            object,
            object_type,
            required: None,
            token: None,
            uid_token: None,
        }
    }
}

