/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AliasDetails {
    /// Account alias
    #[serde(rename = "account-alias")]
    pub account_alias: String,
    /// Auth method name
    #[serde(rename = "auth-method-name")]
    pub auth_method_name: String,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
}

impl AliasDetails {
    pub fn new(account_alias: String, auth_method_name: String) -> AliasDetails {
        AliasDetails {
            account_alias,
            auth_method_name,
            json: None,
        }
    }
}

