/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AliasDetailsOutput {
    #[serde(rename = "access_type", skip_serializing_if = "Option::is_none")]
    pub access_type: Option<String>,
    #[serde(rename = "tenant_tag", skip_serializing_if = "Option::is_none")]
    pub tenant_tag: Option<String>,
}

impl AliasDetailsOutput {
    pub fn new() -> AliasDetailsOutput {
        AliasDetailsOutput {
            access_type: None,
            tenant_tag: None,
        }
    }
}

