/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllowedIpSettings {
    #[serde(rename = "cidr_whitelist", skip_serializing_if = "Option::is_none")]
    pub cidr_whitelist: Option<String>,
    #[serde(rename = "lock", skip_serializing_if = "Option::is_none")]
    pub lock: Option<bool>,
}

impl AllowedIpSettings {
    pub fn new() -> AllowedIpSettings {
        AllowedIpSettings {
            cidr_whitelist: None,
            lock: None,
        }
    }
}

