/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AuthMethodRoleAssociation : AuthMethodRoleAssociation includes details of an association between an auth method and a role.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthMethodRoleAssociation {
    #[serde(rename = "allowed_ops", skip_serializing_if = "Option::is_none")]
    pub allowed_ops: Option<Vec<String>>,
    #[serde(rename = "assoc_id", skip_serializing_if = "Option::is_none")]
    pub assoc_id: Option<String>,
    #[serde(rename = "auth_method_sub_claims", skip_serializing_if = "Option::is_none")]
    pub auth_method_sub_claims: Option<std::collections::HashMap<String, Vec<String>>>,
    #[serde(rename = "is_sub_claims_case_sensitive", skip_serializing_if = "Option::is_none")]
    pub is_sub_claims_case_sensitive: Option<bool>,
    #[serde(rename = "is_subclaims_with_operator", skip_serializing_if = "Option::is_none")]
    pub is_subclaims_with_operator: Option<bool>,
    #[serde(rename = "role_id", skip_serializing_if = "Option::is_none")]
    pub role_id: Option<i64>,
    #[serde(rename = "role_name", skip_serializing_if = "Option::is_none")]
    pub role_name: Option<String>,
    #[serde(rename = "rules", skip_serializing_if = "Option::is_none")]
    pub rules: Option<Box<models::Rules>>,
}

impl AuthMethodRoleAssociation {
    /// AuthMethodRoleAssociation includes details of an association between an auth method and a role.
    pub fn new() -> AuthMethodRoleAssociation {
        AuthMethodRoleAssociation {
            allowed_ops: None,
            assoc_id: None,
            auth_method_sub_claims: None,
            is_sub_claims_case_sensitive: None,
            is_subclaims_with_operator: None,
            role_id: None,
            role_name: None,
            rules: None,
        }
    }
}

