/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AuthMethodCreateAzureAd : authMethodCreateAzureAD is a command that creates a new auth method that will be able to authenticate using Azure Active Directory credentials.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthMethodCreateAzureAd {
    /// Access expiration date in Unix timestamp (select 0 for access without expiry date)
    #[serde(rename = "access-expires", skip_serializing_if = "Option::is_none")]
    pub access_expires: Option<i64>,
    /// limit the auth method usage for specific client types [cli,ui,gateway-admin,sdk,mobile,extension]
    #[serde(rename = "allowed-client-type", skip_serializing_if = "Option::is_none")]
    pub allowed_client_type: Option<Vec<String>>,
    /// Deprecated (Deprecated) The audience in the JWT
    #[serde(rename = "audience", skip_serializing_if = "Option::is_none")]
    pub audience: Option<String>,
    /// Subclaims to include in audit logs, e.g \"--audit-logs-claims email --audit-logs-claims username\"
    #[serde(rename = "audit-logs-claims", skip_serializing_if = "Option::is_none")]
    pub audit_logs_claims: Option<Vec<String>>,
    /// A list of group ids that the access is restricted to
    #[serde(rename = "bound-group-id", skip_serializing_if = "Option::is_none")]
    pub bound_group_id: Option<Vec<String>>,
    /// A CIDR whitelist with the IPs that the access is restricted to
    #[serde(rename = "bound-ips", skip_serializing_if = "Option::is_none")]
    pub bound_ips: Option<Vec<String>>,
    /// A list of resource providers that the access is restricted to (e.g, Microsoft.Compute, Microsoft.ManagedIdentity, etc)
    #[serde(rename = "bound-providers", skip_serializing_if = "Option::is_none")]
    pub bound_providers: Option<Vec<String>>,
    /// A list of full resource ids that the access is restricted to
    #[serde(rename = "bound-resource-id", skip_serializing_if = "Option::is_none")]
    pub bound_resource_id: Option<Vec<String>>,
    /// A list of resource names that the access is restricted to (e.g, a virtual machine name, scale set name, etc).
    #[serde(rename = "bound-resource-names", skip_serializing_if = "Option::is_none")]
    pub bound_resource_names: Option<Vec<String>>,
    /// A list of resource types that the access is restricted to (e.g, virtualMachines, userAssignedIdentities, etc)
    #[serde(rename = "bound-resource-types", skip_serializing_if = "Option::is_none")]
    pub bound_resource_types: Option<Vec<String>>,
    /// A list of resource groups that the access is restricted to
    #[serde(rename = "bound-rg-id", skip_serializing_if = "Option::is_none")]
    pub bound_rg_id: Option<Vec<String>>,
    /// A list of service principal IDs that the access is restricted to
    #[serde(rename = "bound-spid", skip_serializing_if = "Option::is_none")]
    pub bound_spid: Option<Vec<String>>,
    /// A list of subscription ids that the access is restricted to
    #[serde(rename = "bound-sub-id", skip_serializing_if = "Option::is_none")]
    pub bound_sub_id: Option<Vec<String>>,
    /// The Azure tenant id that the access is restricted to
    #[serde(rename = "bound-tenant-id")]
    pub bound_tenant_id: String,
    /// Protection from accidental deletion of this object [true/false]
    #[serde(rename = "delete_protection", skip_serializing_if = "Option::is_none")]
    pub delete_protection: Option<String>,
    /// Auth Method description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// How many days before the expiration of the auth method would you like to be notified.
    #[serde(rename = "expiration-event-in", skip_serializing_if = "Option::is_none")]
    pub expiration_event_in: Option<Vec<String>>,
    /// if true: enforce role-association must include sub claims
    #[serde(rename = "force-sub-claims", skip_serializing_if = "Option::is_none")]
    pub force_sub_claims: Option<bool>,
    /// A CIDR whitelist with the GW IPs that the access is restricted to
    #[serde(rename = "gw-bound-ips", skip_serializing_if = "Option::is_none")]
    pub gw_bound_ips: Option<Vec<String>>,
    /// Issuer URL
    #[serde(rename = "issuer", skip_serializing_if = "Option::is_none")]
    pub issuer: Option<String>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// The URL to the JSON Web Key Set (JWKS) that containing the public keys that should be used to verify any JSON Web Token (JWT) issued by the authorization server.
    #[serde(rename = "jwks-uri", skip_serializing_if = "Option::is_none")]
    pub jwks_uri: Option<String>,
    /// Jwt TTL
    #[serde(rename = "jwt-ttl", skip_serializing_if = "Option::is_none")]
    pub jwt_ttl: Option<i64>,
    /// Auth Method name
    #[serde(rename = "name")]
    pub name: String,
    /// Choose the relevant product type for the auth method [sm, sra, pm, dp, ca]
    #[serde(rename = "product-type", skip_serializing_if = "Option::is_none")]
    pub product_type: Option<Vec<String>>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
    /// A unique identifier (ID) value which is a \"sub claim\" name that contains details uniquely identifying that resource. This \"sub claim\" is used to distinguish between different identities.
    #[serde(rename = "unique-identifier", skip_serializing_if = "Option::is_none")]
    pub unique_identifier: Option<String>,
}

impl AuthMethodCreateAzureAd {
    /// authMethodCreateAzureAD is a command that creates a new auth method that will be able to authenticate using Azure Active Directory credentials.
    pub fn new(bound_tenant_id: String, name: String) -> AuthMethodCreateAzureAd {
        AuthMethodCreateAzureAd {
            access_expires: None,
            allowed_client_type: None,
            audience: None,
            audit_logs_claims: None,
            bound_group_id: None,
            bound_ips: None,
            bound_providers: None,
            bound_resource_id: None,
            bound_resource_names: None,
            bound_resource_types: None,
            bound_rg_id: None,
            bound_spid: None,
            bound_sub_id: None,
            bound_tenant_id,
            delete_protection: None,
            description: None,
            expiration_event_in: None,
            force_sub_claims: None,
            gw_bound_ips: None,
            issuer: None,
            json: None,
            jwks_uri: None,
            jwt_ttl: None,
            name,
            product_type: None,
            token: None,
            uid_token: None,
            unique_identifier: None,
        }
    }
}

