/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AuthMethodCreateOci : authMethodCreateOCI is a command that creates a new Oracle Auth Method that will be used in the account using OCI principle and groups.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthMethodCreateOci {
    /// Access expiration date in Unix timestamp (select 0 for access without expiry date)
    #[serde(rename = "access-expires", skip_serializing_if = "Option::is_none")]
    pub access_expires: Option<i64>,
    /// limit the auth method usage for specific client types [cli,ui,gateway-admin,sdk,mobile,extension]
    #[serde(rename = "allowed-client-type", skip_serializing_if = "Option::is_none")]
    pub allowed_client_type: Option<Vec<String>>,
    /// Subclaims to include in audit logs, e.g \"--audit-logs-claims email --audit-logs-claims username\"
    #[serde(rename = "audit-logs-claims", skip_serializing_if = "Option::is_none")]
    pub audit_logs_claims: Option<Vec<String>>,
    /// A CIDR whitelist with the IPs that the access is restricted to
    #[serde(rename = "bound-ips", skip_serializing_if = "Option::is_none")]
    pub bound_ips: Option<Vec<String>>,
    /// Protection from accidental deletion of this object [true/false]
    #[serde(rename = "delete_protection", skip_serializing_if = "Option::is_none")]
    pub delete_protection: Option<String>,
    /// Auth Method description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// How many days before the expiration of the auth method would you like to be notified.
    #[serde(rename = "expiration-event-in", skip_serializing_if = "Option::is_none")]
    pub expiration_event_in: Option<Vec<String>>,
    /// if true: enforce role-association must include sub claims
    #[serde(rename = "force-sub-claims", skip_serializing_if = "Option::is_none")]
    pub force_sub_claims: Option<bool>,
    /// A list of required groups ocids
    #[serde(rename = "group-ocid")]
    pub group_ocid: Vec<String>,
    /// A CIDR whitelist with the GW IPs that the access is restricted to
    #[serde(rename = "gw-bound-ips", skip_serializing_if = "Option::is_none")]
    pub gw_bound_ips: Option<Vec<String>>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Jwt TTL
    #[serde(rename = "jwt-ttl", skip_serializing_if = "Option::is_none")]
    pub jwt_ttl: Option<i64>,
    /// Auth Method name
    #[serde(rename = "name")]
    pub name: String,
    /// Choose the relevant product type for the auth method [sm, sra, pm, dp, ca]
    #[serde(rename = "product-type", skip_serializing_if = "Option::is_none")]
    pub product_type: Option<Vec<String>>,
    /// The Oracle Cloud tenant ID
    #[serde(rename = "tenant-ocid")]
    pub tenant_ocid: String,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl AuthMethodCreateOci {
    /// authMethodCreateOCI is a command that creates a new Oracle Auth Method that will be used in the account using OCI principle and groups.
    pub fn new(group_ocid: Vec<String>, name: String, tenant_ocid: String) -> AuthMethodCreateOci {
        AuthMethodCreateOci {
            access_expires: None,
            allowed_client_type: None,
            audit_logs_claims: None,
            bound_ips: None,
            delete_protection: None,
            description: None,
            expiration_event_in: None,
            force_sub_claims: None,
            group_ocid,
            gw_bound_ips: None,
            json: None,
            jwt_ttl: None,
            name,
            product_type: None,
            tenant_ocid,
            token: None,
            uid_token: None,
        }
    }
}

