/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Auth {
    /// Access ID
    #[serde(rename = "access-id", skip_serializing_if = "Option::is_none")]
    pub access_id: Option<String>,
    /// Access key (relevant only for access-type=access_key)
    #[serde(rename = "access-key", skip_serializing_if = "Option::is_none")]
    pub access_key: Option<String>,
    /// Access Type (access_key/password/saml/ldap/k8s/azure_ad/oidc/aws_iam/universal_identity/jwt/gcp/cert/oci/kerberos)
    #[serde(rename = "access-type", skip_serializing_if = "Option::is_none")]
    pub access_type: Option<String>,
    /// Account id (relevant only for access-type=password where the email address is associated with more than one account)
    #[serde(rename = "account-id", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    /// Email (relevant only for access-type=password)
    #[serde(rename = "admin-email", skip_serializing_if = "Option::is_none")]
    pub admin_email: Option<String>,
    /// Password (relevant only for access-type=password)
    #[serde(rename = "admin-password", skip_serializing_if = "Option::is_none")]
    pub admin_password: Option<String>,
    /// Azure cloud environment to use. Values: AzureCloud (default), AzureUSGovernment, AzureChinaCloud.
    #[serde(rename = "azure-cloud", skip_serializing_if = "Option::is_none")]
    pub azure_cloud: Option<String>,
    /// Certificate challenge encoded in base64. (relevant only for access-type=cert)
    #[serde(rename = "cert-challenge", skip_serializing_if = "Option::is_none")]
    pub cert_challenge: Option<String>,
    /// Certificate data encoded in base64. Used if file was not provided. (relevant only for access-type=cert)
    #[serde(rename = "cert-data", skip_serializing_if = "Option::is_none")]
    pub cert_data: Option<String>,
    /// The cloud identity (relevant only for access-type=azure_ad,aws_iam,gcp)
    #[serde(rename = "cloud-id", skip_serializing_if = "Option::is_none")]
    pub cloud_id: Option<String>,
    #[serde(rename = "debug", skip_serializing_if = "Option::is_none")]
    pub debug: Option<bool>,
    /// Disable the FAST negotiation in the Kerberos authentication method
    #[serde(rename = "disable-pafxfast", skip_serializing_if = "Option::is_none")]
    pub disable_pafxfast: Option<String>,
    /// The service principal name of the gateway as registered in LDAP (i.e., HTTP/gateway)
    #[serde(rename = "gateway-spn", skip_serializing_if = "Option::is_none")]
    pub gateway_spn: Option<String>,
    /// Gateway URL relevant only for access-type=k8s/oauth2/saml/oidc
    #[serde(rename = "gateway-url", skip_serializing_if = "Option::is_none")]
    pub gateway_url: Option<String>,
    /// GCP JWT audience
    #[serde(rename = "gcp-audience", skip_serializing_if = "Option::is_none")]
    pub gcp_audience: Option<String>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// The Json Web Token (relevant only for access-type=jwt/oidc)
    #[serde(rename = "jwt", skip_serializing_if = "Option::is_none")]
    pub jwt: Option<String>,
    /// The K8S Auth config name (relevant only for access-type=k8s)
    #[serde(rename = "k8s-auth-config-name", skip_serializing_if = "Option::is_none")]
    pub k8s_auth_config_name: Option<String>,
    /// The K8S service account token. (relevant only for access-type=k8s)
    #[serde(rename = "k8s-service-account-token", skip_serializing_if = "Option::is_none")]
    pub k8s_service_account_token: Option<String>,
    /// KerberosToken represents a Kerberos token generated for the gateway SPN (Service Principal Name).
    #[serde(rename = "kerberos-token", skip_serializing_if = "Option::is_none")]
    pub kerberos_token: Option<String>,
    /// TThe username for the entry within the keytab to authenticate via Kerberos
    #[serde(rename = "kerberos-username", skip_serializing_if = "Option::is_none")]
    pub kerberos_username: Option<String>,
    /// Private key data encoded in base64. Used if file was not provided.(relevant only for access-type=cert)
    #[serde(rename = "key-data", skip_serializing_if = "Option::is_none")]
    pub key_data: Option<String>,
    /// Base64-encoded content of a valid keytab file, containing the service account's entry.
    #[serde(rename = "keytab-data", skip_serializing_if = "Option::is_none")]
    pub keytab_data: Option<String>,
    /// Base64-encoded content of a valid krb5.conf file, specifying the settings and parameters required for Kerberos authentication.
    #[serde(rename = "krb5-conf-data", skip_serializing_if = "Option::is_none")]
    pub krb5_conf_data: Option<String>,
    /// LDAP password (relevant only for access-type=ldap)
    #[serde(rename = "ldap-password", skip_serializing_if = "Option::is_none")]
    pub ldap_password: Option<String>,
    /// The type of the OCI configuration to use [instance/apikey/resource] (relevant only for access-type=oci)
    #[serde(rename = "oci-auth-type", skip_serializing_if = "Option::is_none")]
    pub oci_auth_type: Option<String>,
    /// A list of Oracle Cloud IDs groups (relevant only for access-type=oci)
    #[serde(rename = "oci-group-ocid", skip_serializing_if = "Option::is_none")]
    pub oci_group_ocid: Option<Vec<String>>,
    #[serde(rename = "otp", skip_serializing_if = "Option::is_none")]
    pub otp: Option<String>,
    /// Signed certificate challenge encoded in base64. (relevant only for access-type=cert)
    #[serde(rename = "signed-cert-challenge", skip_serializing_if = "Option::is_none")]
    pub signed_cert_challenge: Option<String>,
    /// The universal_identity token (relevant only for access-type=universal_identity)
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
    /// Returns a link to complete the authentication remotely (relevant only for access-type=saml/oidc)
    #[serde(rename = "use-remote-browser", skip_serializing_if = "Option::is_none")]
    pub use_remote_browser: Option<bool>,
    /// LDAP username (relevant only for access-type=ldap)
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
}

impl Auth {
    pub fn new() -> Auth {
        Auth {
            access_id: None,
            access_key: None,
            access_type: None,
            account_id: None,
            admin_email: None,
            admin_password: None,
            azure_cloud: None,
            cert_challenge: None,
            cert_data: None,
            cloud_id: None,
            debug: None,
            disable_pafxfast: None,
            gateway_spn: None,
            gateway_url: None,
            gcp_audience: None,
            json: None,
            jwt: None,
            k8s_auth_config_name: None,
            k8s_service_account_token: None,
            kerberos_token: None,
            kerberos_username: None,
            key_data: None,
            keytab_data: None,
            krb5_conf_data: None,
            ldap_password: None,
            oci_auth_type: None,
            oci_group_ocid: None,
            otp: None,
            signed_cert_challenge: None,
            uid_token: None,
            use_remote_browser: None,
            username: None,
        }
    }
}

