/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthMethodCreateOutput {
    #[serde(rename = "access_id", skip_serializing_if = "Option::is_none")]
    pub access_id: Option<String>,
    #[serde(rename = "access_key", skip_serializing_if = "Option::is_none")]
    pub access_key: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "prv_key", skip_serializing_if = "Option::is_none")]
    pub prv_key: Option<String>,
}

impl AuthMethodCreateOutput {
    pub fn new() -> AuthMethodCreateOutput {
        AuthMethodCreateOutput {
            access_id: None,
            access_key: None,
            name: None,
            prv_key: None,
        }
    }
}

