/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AuthMethodUpdateK8s : authMethodUpdateK8s is a command that updates a new auth method that will be able to authenticate using K8S.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthMethodUpdateK8s {
    /// Access expiration date in Unix timestamp (select 0 for access without expiry date)
    #[serde(rename = "access-expires", skip_serializing_if = "Option::is_none")]
    pub access_expires: Option<i64>,
    /// limit the auth method usage for specific client types [cli,ui,gateway-admin,sdk,mobile,extension]
    #[serde(rename = "allowed-client-type", skip_serializing_if = "Option::is_none")]
    pub allowed_client_type: Option<Vec<String>>,
    /// The audience in the Kubernetes JWT that the access is restricted to
    #[serde(rename = "audience", skip_serializing_if = "Option::is_none")]
    pub audience: Option<String>,
    /// Subclaims to include in audit logs, e.g \"--audit-logs-claims email --audit-logs-claims username\"
    #[serde(rename = "audit-logs-claims", skip_serializing_if = "Option::is_none")]
    pub audit_logs_claims: Option<Vec<String>>,
    /// A CIDR whitelist with the IPs that the access is restricted to
    #[serde(rename = "bound-ips", skip_serializing_if = "Option::is_none")]
    pub bound_ips: Option<Vec<String>>,
    /// A list of namespaces that the access is restricted to
    #[serde(rename = "bound-namespaces", skip_serializing_if = "Option::is_none")]
    pub bound_namespaces: Option<Vec<String>>,
    /// A list of pod names that the access is restricted to
    #[serde(rename = "bound-pod-names", skip_serializing_if = "Option::is_none")]
    pub bound_pod_names: Option<Vec<String>>,
    /// A list of service account names that the access is restricted to
    #[serde(rename = "bound-sa-names", skip_serializing_if = "Option::is_none")]
    pub bound_sa_names: Option<Vec<String>>,
    /// Protection from accidental deletion of this object [true/false]
    #[serde(rename = "delete_protection", skip_serializing_if = "Option::is_none")]
    pub delete_protection: Option<String>,
    /// Auth Method description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// How many days before the expiration of the auth method would you like to be notified.
    #[serde(rename = "expiration-event-in", skip_serializing_if = "Option::is_none")]
    pub expiration_event_in: Option<Vec<String>>,
    /// if true: enforce role-association must include sub claims
    #[serde(rename = "force-sub-claims", skip_serializing_if = "Option::is_none")]
    pub force_sub_claims: Option<bool>,
    /// Automatically generate key-pair for K8S configuration. If set to false, a public key needs to be provided [true/false]
    #[serde(rename = "gen-key", skip_serializing_if = "Option::is_none")]
    pub gen_key: Option<String>,
    /// A CIDR whitelist with the GW IPs that the access is restricted to
    #[serde(rename = "gw-bound-ips", skip_serializing_if = "Option::is_none")]
    pub gw_bound_ips: Option<Vec<String>>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Jwt TTL
    #[serde(rename = "jwt-ttl", skip_serializing_if = "Option::is_none")]
    pub jwt_ttl: Option<i64>,
    /// Auth Method name
    #[serde(rename = "name")]
    pub name: String,
    /// Auth Method new name
    #[serde(rename = "new-name", skip_serializing_if = "Option::is_none")]
    pub new_name: Option<String>,
    /// Choose the relevant product type for the auth method [sm, sra, pm, dp, ca]
    #[serde(rename = "product-type", skip_serializing_if = "Option::is_none")]
    pub product_type: Option<Vec<String>>,
    /// Base64-encoded or PEM formatted public key data for K8S authentication method is required [RSA2048]
    #[serde(rename = "public-key", skip_serializing_if = "Option::is_none")]
    pub public_key: Option<String>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl AuthMethodUpdateK8s {
    /// authMethodUpdateK8s is a command that updates a new auth method that will be able to authenticate using K8S.
    pub fn new(name: String) -> AuthMethodUpdateK8s {
        AuthMethodUpdateK8s {
            access_expires: None,
            allowed_client_type: None,
            audience: None,
            audit_logs_claims: None,
            bound_ips: None,
            bound_namespaces: None,
            bound_pod_names: None,
            bound_sa_names: None,
            delete_protection: None,
            description: None,
            expiration_event_in: None,
            force_sub_claims: None,
            gen_key: None,
            gw_bound_ips: None,
            json: None,
            jwt_ttl: None,
            name,
            new_name: None,
            product_type: None,
            public_key: None,
            token: None,
            uid_token: None,
        }
    }
}

