/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AwsS3LogForwardingConfig {
    #[serde(rename = "aws_access_id", skip_serializing_if = "Option::is_none")]
    pub aws_access_id: Option<String>,
    #[serde(rename = "aws_access_key", skip_serializing_if = "Option::is_none")]
    pub aws_access_key: Option<String>,
    #[serde(rename = "aws_auth_type", skip_serializing_if = "Option::is_none")]
    pub aws_auth_type: Option<String>,
    #[serde(rename = "aws_region", skip_serializing_if = "Option::is_none")]
    pub aws_region: Option<String>,
    #[serde(rename = "aws_role_arn", skip_serializing_if = "Option::is_none")]
    pub aws_role_arn: Option<String>,
    /// deprecated
    #[serde(rename = "aws_use_gateway_cloud_identity", skip_serializing_if = "Option::is_none")]
    pub aws_use_gateway_cloud_identity: Option<bool>,
    #[serde(rename = "bucket_name", skip_serializing_if = "Option::is_none")]
    pub bucket_name: Option<String>,
    #[serde(rename = "log_folder", skip_serializing_if = "Option::is_none")]
    pub log_folder: Option<String>,
}

impl AwsS3LogForwardingConfig {
    pub fn new() -> AwsS3LogForwardingConfig {
        AwsS3LogForwardingConfig {
            aws_access_id: None,
            aws_access_key: None,
            aws_auth_type: None,
            aws_region: None,
            aws_role_arn: None,
            aws_use_gateway_cloud_identity: None,
            bucket_name: None,
            log_folder: None,
        }
    }
}

