/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AzureAdAccessRules : AzureADAccessRules contains access rules specific to Azure Active Directory authentication.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AzureAdAccessRules {
    /// The audience in the JWT.
    #[serde(rename = "ad_endpoint", skip_serializing_if = "Option::is_none")]
    pub ad_endpoint: Option<String>,
    /// Azure cloud environment [AzureCloud/AzureUSGovernment/AzureChinaCloud]. For create/update, cloud is inferred from jwks_uri.
    #[serde(rename = "azure_cloud", skip_serializing_if = "Option::is_none")]
    pub azure_cloud: Option<String>,
    /// The list of group ids that login is restricted to.
    #[serde(rename = "bound_group_ids", skip_serializing_if = "Option::is_none")]
    pub bound_group_ids: Option<Vec<String>>,
    /// The list of resource groups that login is restricted to.
    #[serde(rename = "bound_resource_groups", skip_serializing_if = "Option::is_none")]
    pub bound_resource_groups: Option<Vec<String>>,
    /// The list of full resource ids that the login is restricted to.
    #[serde(rename = "bound_resource_ids", skip_serializing_if = "Option::is_none")]
    pub bound_resource_ids: Option<Vec<String>>,
    /// The list of resource names that the login is restricted to (e.g, a virtual machine name, scale set name, etc).
    #[serde(rename = "bound_resource_names", skip_serializing_if = "Option::is_none")]
    pub bound_resource_names: Option<Vec<String>>,
    /// The list of resource providers that login is restricted to (e.g, Microsoft.Compute, Microsoft.ManagedIdentity, etc).
    #[serde(rename = "bound_resource_providers", skip_serializing_if = "Option::is_none")]
    pub bound_resource_providers: Option<Vec<String>>,
    /// The list of resource types that login is restricted to  (e.g, virtualMachines, userAssignedIdentities, etc).
    #[serde(rename = "bound_resource_types", skip_serializing_if = "Option::is_none")]
    pub bound_resource_types: Option<Vec<String>>,
    /// The list of service principal IDs that login is restricted to.
    #[serde(rename = "bound_service_principal_ids", skip_serializing_if = "Option::is_none")]
    pub bound_service_principal_ids: Option<Vec<String>>,
    /// The list of subscription IDs that login is restricted to.
    #[serde(rename = "bound_subscription_ids", skip_serializing_if = "Option::is_none")]
    pub bound_subscription_ids: Option<Vec<String>>,
    /// The tenants id for the Azure Active Directory organization.
    #[serde(rename = "bound_tenant_id", skip_serializing_if = "Option::is_none")]
    pub bound_tenant_id: Option<String>,
    /// Issuer URL
    #[serde(rename = "issuer", skip_serializing_if = "Option::is_none")]
    pub issuer: Option<String>,
    /// The URL to the JSON Web Key Set (JWKS) that containing the public keys that should be used to verify any JSON Web Token (JWT) issued by the authorization server.
    #[serde(rename = "jwks_uri", skip_serializing_if = "Option::is_none")]
    pub jwks_uri: Option<String>,
    /// A unique identifier to distinguish different users
    #[serde(rename = "unique_identifier", skip_serializing_if = "Option::is_none")]
    pub unique_identifier: Option<String>,
}

impl AzureAdAccessRules {
    /// AzureADAccessRules contains access rules specific to Azure Active Directory authentication.
    pub fn new() -> AzureAdAccessRules {
        AzureAdAccessRules {
            ad_endpoint: None,
            azure_cloud: None,
            bound_group_ids: None,
            bound_resource_groups: None,
            bound_resource_ids: None,
            bound_resource_names: None,
            bound_resource_providers: None,
            bound_resource_types: None,
            bound_service_principal_ids: None,
            bound_subscription_ids: None,
            bound_tenant_id: None,
            issuer: None,
            jwks_uri: None,
            unique_identifier: None,
        }
    }
}

