/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AzureLogAnalyticsForwardingConfig {
    #[serde(rename = "azure_enable_batch", skip_serializing_if = "Option::is_none")]
    pub azure_enable_batch: Option<String>,
    #[serde(rename = "azure_workspace_id", skip_serializing_if = "Option::is_none")]
    pub azure_workspace_id: Option<String>,
    #[serde(rename = "azure_workspace_key", skip_serializing_if = "Option::is_none")]
    pub azure_workspace_key: Option<String>,
}

impl AzureLogAnalyticsForwardingConfig {
    pub fn new() -> AzureLogAnalyticsForwardingConfig {
        AzureLogAnalyticsForwardingConfig {
            azure_enable_batch: None,
            azure_workspace_id: None,
            azure_workspace_key: None,
        }
    }
}

