/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CertAccessRules {
    /// a list of allowed cors domains if used for browser authentication
    #[serde(rename = "allowed_cors", skip_serializing_if = "Option::is_none")]
    pub allowed_cors: Option<Vec<String>>,
    /// A list of names. At least one must exist in the Common Name. Supports globbing.
    #[serde(rename = "bound_common_names", skip_serializing_if = "Option::is_none")]
    pub bound_common_names: Option<Vec<String>>,
    /// A list of DNS names. At least one must exist in the SANs. Supports globbing.
    #[serde(rename = "bound_dns_sans", skip_serializing_if = "Option::is_none")]
    pub bound_dns_sans: Option<Vec<String>>,
    /// A list of Email Addresses. At least one must exist in the SANs. Supports globbing.
    #[serde(rename = "bound_email_sans", skip_serializing_if = "Option::is_none")]
    pub bound_email_sans: Option<Vec<String>>,
    /// A list of extensions formatted as \"oid:value\". Expects the extension value to be some type of ASN1 encoded string. All values must match. Supports globbing on \"value\".
    #[serde(rename = "bound_extensions", skip_serializing_if = "Option::is_none")]
    pub bound_extensions: Option<Vec<String>>,
    /// A list of Organizational Units names. At least one must exist in the OU field.
    #[serde(rename = "bound_organizational_units", skip_serializing_if = "Option::is_none")]
    pub bound_organizational_units: Option<Vec<String>>,
    /// A list of URIs. At least one must exist in the SANs. Supports globbing.
    #[serde(rename = "bound_uri_sans", skip_serializing_if = "Option::is_none")]
    pub bound_uri_sans: Option<Vec<String>>,
    /// Base64 encdoed PEM certificate
    #[serde(rename = "certificate", skip_serializing_if = "Option::is_none")]
    pub certificate: Option<String>,
    /// RequireCrlDp indicates whether CRL distribution points are required on the leaf client certificate, and whether CRL validation must be enforced during authentication.
    #[serde(rename = "require_crl_dp", skip_serializing_if = "Option::is_none")]
    pub require_crl_dp: Option<bool>,
    /// A list of revoked cert ids
    #[serde(rename = "revoked_cert_ids", skip_serializing_if = "Option::is_none")]
    pub revoked_cert_ids: Option<Vec<String>>,
    /// A unique identifier to distinguish different users
    #[serde(rename = "unique_identifier", skip_serializing_if = "Option::is_none")]
    pub unique_identifier: Option<String>,
}

impl CertAccessRules {
    pub fn new() -> CertAccessRules {
        CertAccessRules {
            allowed_cors: None,
            bound_common_names: None,
            bound_dns_sans: None,
            bound_email_sans: None,
            bound_extensions: None,
            bound_organizational_units: None,
            bound_uri_sans: None,
            certificate: None,
            require_crl_dp: None,
            revoked_cert_ids: None,
            unique_identifier: None,
        }
    }
}

