/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CertificateVersionInfo {
    #[serde(rename = "not_after", skip_serializing_if = "Option::is_none")]
    pub not_after: Option<String>,
    #[serde(rename = "not_before", skip_serializing_if = "Option::is_none")]
    pub not_before: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

impl CertificateVersionInfo {
    pub fn new() -> CertificateVersionInfo {
        CertificateVersionInfo {
            not_after: None,
            not_before: None,
            status: None,
        }
    }
}

