/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CertificateDiscovery : CertificateDiscovery is a command that discovery certificates
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CertificateDiscovery {
    /// Debug mode
    #[serde(rename = "debug", skip_serializing_if = "Option::is_none")]
    pub debug: Option<bool>,
    /// How many days before the expiration of the certificate would you like to be notified.
    #[serde(rename = "expiration-event-in", skip_serializing_if = "Option::is_none")]
    pub expiration_event_in: Option<Vec<String>>,
    /// A comma separated list of IPs, CIDR ranges, or DNS names to discovery
    #[serde(rename = "hosts")]
    pub hosts: String,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// A comma separated list of port ranges Examples: \"80,443\" or \"80,443,8080-8090\" or \"443\"
    #[serde(rename = "port-ranges", skip_serializing_if = "Option::is_none")]
    pub port_ranges: Option<String>,
    /// The name of the key that protects the certificate value
    #[serde(rename = "protection-key", skip_serializing_if = "Option::is_none")]
    pub protection_key: Option<String>,
    /// The folder where the results will be saved
    #[serde(rename = "target-location")]
    pub target_location: String,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl CertificateDiscovery {
    /// CertificateDiscovery is a command that discovery certificates
    pub fn new(hosts: String, target_location: String) -> CertificateDiscovery {
        CertificateDiscovery {
            debug: None,
            expiration_event_in: None,
            hosts,
            json: None,
            port_ranges: None,
            protection_key: None,
            target_location,
            token: None,
            uid_token: None,
        }
    }
}

