/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CertificateTemplateInfo {
    #[serde(rename = "common_name", skip_serializing_if = "Option::is_none")]
    pub common_name: Option<String>,
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    #[serde(rename = "csr_cnf_base_64", skip_serializing_if = "Option::is_none")]
    pub csr_cnf_base_64: Option<String>,
    #[serde(rename = "digest_algo", skip_serializing_if = "Option::is_none")]
    pub digest_algo: Option<String>,
    #[serde(rename = "hash_algorithm", skip_serializing_if = "Option::is_none")]
    pub hash_algorithm: Option<String>,
    #[serde(rename = "locality", skip_serializing_if = "Option::is_none")]
    pub locality: Option<String>,
    #[serde(rename = "organization", skip_serializing_if = "Option::is_none")]
    pub organization: Option<String>,
    #[serde(rename = "province", skip_serializing_if = "Option::is_none")]
    pub province: Option<String>,
    #[serde(rename = "self_signed_enabled", skip_serializing_if = "Option::is_none")]
    pub self_signed_enabled: Option<bool>,
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i64>,
}

impl CertificateTemplateInfo {
    pub fn new() -> CertificateTemplateInfo {
        CertificateTemplateInfo {
            common_name: None,
            country: None,
            csr_cnf_base_64: None,
            digest_algo: None,
            hash_algorithm: None,
            locality: None,
            organization: None,
            province: None,
            self_signed_enabled: None,
            ttl: None,
        }
    }
}

