/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CertificateInfo {
    #[serde(rename = "ExtKeyUsage", skip_serializing_if = "Option::is_none")]
    pub ext_key_usage: Option<Vec<i64>>,
    /// KeyUsage represents the set of actions that are valid for a given key. It's a bitmap of the KeyUsage* constants.
    #[serde(rename = "KeyUsage", skip_serializing_if = "Option::is_none")]
    pub key_usage: Option<i64>,
    #[serde(rename = "crl_distribution_points", skip_serializing_if = "Option::is_none")]
    pub crl_distribution_points: Option<Vec<String>>,
    #[serde(rename = "dns_names", skip_serializing_if = "Option::is_none")]
    pub dns_names: Option<Vec<String>>,
    #[serde(rename = "email_addresses", skip_serializing_if = "Option::is_none")]
    pub email_addresses: Option<Vec<String>>,
    #[serde(rename = "extensions", skip_serializing_if = "Option::is_none")]
    pub extensions: Option<Vec<models::Extension>>,
    #[serde(rename = "ip_addresses", skip_serializing_if = "Option::is_none")]
    pub ip_addresses: Option<Vec<String>>,
    #[serde(rename = "is_ca", skip_serializing_if = "Option::is_none")]
    pub is_ca: Option<bool>,
    #[serde(rename = "issuer", skip_serializing_if = "Option::is_none")]
    pub issuer: Option<Box<models::Name>>,
    #[serde(rename = "issuing_certificate_url", skip_serializing_if = "Option::is_none")]
    pub issuing_certificate_url: Option<Vec<String>>,
    #[serde(rename = "key_size", skip_serializing_if = "Option::is_none")]
    pub key_size: Option<i64>,
    #[serde(rename = "not_after", skip_serializing_if = "Option::is_none")]
    pub not_after: Option<String>,
    #[serde(rename = "not_before", skip_serializing_if = "Option::is_none")]
    pub not_before: Option<String>,
    #[serde(rename = "ocsp_server", skip_serializing_if = "Option::is_none")]
    pub ocsp_server: Option<Vec<String>>,
    #[serde(rename = "public_key_algorithm_name", skip_serializing_if = "Option::is_none")]
    pub public_key_algorithm_name: Option<String>,
    #[serde(rename = "serial_number", skip_serializing_if = "Option::is_none")]
    pub serial_number: Option<String>,
    #[serde(rename = "sha_1_fingerprint", skip_serializing_if = "Option::is_none")]
    pub sha_1_fingerprint: Option<String>,
    #[serde(rename = "sha_256_fingerprint", skip_serializing_if = "Option::is_none")]
    pub sha_256_fingerprint: Option<String>,
    #[serde(rename = "signature", skip_serializing_if = "Option::is_none")]
    pub signature: Option<String>,
    #[serde(rename = "signature_algorithm_name", skip_serializing_if = "Option::is_none")]
    pub signature_algorithm_name: Option<String>,
    #[serde(rename = "subject", skip_serializing_if = "Option::is_none")]
    pub subject: Option<Box<models::Name>>,
    #[serde(rename = "subject_public_key", skip_serializing_if = "Option::is_none")]
    pub subject_public_key: Option<String>,
    #[serde(rename = "uris", skip_serializing_if = "Option::is_none")]
    pub uris: Option<Vec<String>>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<i64>,
}

impl CertificateInfo {
    pub fn new() -> CertificateInfo {
        CertificateInfo {
            ext_key_usage: None,
            key_usage: None,
            crl_distribution_points: None,
            dns_names: None,
            email_addresses: None,
            extensions: None,
            ip_addresses: None,
            is_ca: None,
            issuer: None,
            issuing_certificate_url: None,
            key_size: None,
            not_after: None,
            not_before: None,
            ocsp_server: None,
            public_key_algorithm_name: None,
            serial_number: None,
            sha_1_fingerprint: None,
            sha_256_fingerprint: None,
            signature: None,
            signature_algorithm_name: None,
            subject: None,
            subject_public_key: None,
            uris: None,
            version: None,
        }
    }
}

