/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CertificateChainInfo {
    #[serde(rename = "auto_renew_certificate", skip_serializing_if = "Option::is_none")]
    pub auto_renew_certificate: Option<bool>,
    #[serde(rename = "certificate_chain", skip_serializing_if = "Option::is_none")]
    pub certificate_chain: Option<Vec<models::CertificateInfo>>,
    #[serde(rename = "certificate_format", skip_serializing_if = "Option::is_none")]
    pub certificate_format: Option<String>,
    #[serde(rename = "certificate_has_private_key", skip_serializing_if = "Option::is_none")]
    pub certificate_has_private_key: Option<bool>,
    #[serde(rename = "certificate_issuer_gw_cluster_id", skip_serializing_if = "Option::is_none")]
    pub certificate_issuer_gw_cluster_id: Option<i64>,
    #[serde(rename = "certificate_issuer_gw_cluster_url", skip_serializing_if = "Option::is_none")]
    pub certificate_issuer_gw_cluster_url: Option<String>,
    #[serde(rename = "certificate_issuer_item_id", skip_serializing_if = "Option::is_none")]
    pub certificate_issuer_item_id: Option<i64>,
    #[serde(rename = "certificate_issuer_name", skip_serializing_if = "Option::is_none")]
    pub certificate_issuer_name: Option<String>,
    #[serde(rename = "certificate_pem", skip_serializing_if = "Option::is_none")]
    pub certificate_pem: Option<String>,
    #[serde(rename = "certificate_status", skip_serializing_if = "Option::is_none")]
    pub certificate_status: Option<String>,
    #[serde(rename = "common_name", skip_serializing_if = "Option::is_none")]
    pub common_name: Option<String>,
    /// CSRPEM contains the PEM-encoded CSR for pending certificates (HTTP-01 challenge)
    #[serde(rename = "csr_pem", skip_serializing_if = "Option::is_none")]
    pub csr_pem: Option<String>,
    #[serde(rename = "error_message", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    #[serde(rename = "expiration_date", skip_serializing_if = "Option::is_none")]
    pub expiration_date: Option<String>,
    #[serde(rename = "expiration_events", skip_serializing_if = "Option::is_none")]
    pub expiration_events: Option<Vec<models::CertificateExpirationEvent>>,
    #[serde(rename = "external_ca_id", skip_serializing_if = "Option::is_none")]
    pub external_ca_id: Option<Box<models::NullString>>,
    #[serde(rename = "issuance_status", skip_serializing_if = "Option::is_none")]
    pub issuance_status: Option<String>,
    #[serde(rename = "not_before", skip_serializing_if = "Option::is_none")]
    pub not_before: Option<String>,
    #[serde(rename = "renew_before_expiration_in_days", skip_serializing_if = "Option::is_none")]
    pub renew_before_expiration_in_days: Option<i64>,
}

impl CertificateChainInfo {
    pub fn new() -> CertificateChainInfo {
        CertificateChainInfo {
            auto_renew_certificate: None,
            certificate_chain: None,
            certificate_format: None,
            certificate_has_private_key: None,
            certificate_issuer_gw_cluster_id: None,
            certificate_issuer_gw_cluster_url: None,
            certificate_issuer_item_id: None,
            certificate_issuer_name: None,
            certificate_pem: None,
            certificate_status: None,
            common_name: None,
            csr_pem: None,
            error_message: None,
            expiration_date: None,
            expiration_events: None,
            external_ca_id: None,
            issuance_status: None,
            not_before: None,
            renew_before_expiration_in_days: None,
        }
    }
}

