/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChefTargetDetails : ChefTargetDetails
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChefTargetDetails {
    #[serde(rename = "chef_server_host_name", skip_serializing_if = "Option::is_none")]
    pub chef_server_host_name: Option<String>,
    #[serde(rename = "chef_server_key", skip_serializing_if = "Option::is_none")]
    pub chef_server_key: Option<String>,
    #[serde(rename = "chef_server_port", skip_serializing_if = "Option::is_none")]
    pub chef_server_port: Option<String>,
    #[serde(rename = "chef_server_url", skip_serializing_if = "Option::is_none")]
    pub chef_server_url: Option<String>,
    #[serde(rename = "chef_server_username", skip_serializing_if = "Option::is_none")]
    pub chef_server_username: Option<String>,
    #[serde(rename = "chef_skip_ssl", skip_serializing_if = "Option::is_none")]
    pub chef_skip_ssl: Option<bool>,
}

impl ChefTargetDetails {
    /// ChefTargetDetails
    pub fn new() -> ChefTargetDetails {
        ChefTargetDetails {
            chef_server_host_name: None,
            chef_server_key: None,
            chef_server_port: None,
            chef_server_url: None,
            chef_server_username: None,
            chef_skip_ssl: None,
        }
    }
}

