/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigHash {
    #[serde(rename = "admins", skip_serializing_if = "Option::is_none")]
    pub admins: Option<String>,
    #[serde(rename = "ai_insights", skip_serializing_if = "Option::is_none")]
    pub ai_insights: Option<String>,
    #[serde(rename = "cache", skip_serializing_if = "Option::is_none")]
    pub cache: Option<String>,
    #[serde(rename = "customer_fragements", skip_serializing_if = "Option::is_none")]
    pub customer_fragements: Option<String>,
    #[serde(rename = "general", skip_serializing_if = "Option::is_none")]
    pub general: Option<String>,
    #[serde(rename = "k8s_auths", skip_serializing_if = "Option::is_none")]
    pub k8s_auths: Option<String>,
    #[serde(rename = "kmip", skip_serializing_if = "Option::is_none")]
    pub kmip: Option<String>,
    #[serde(rename = "ldap", skip_serializing_if = "Option::is_none")]
    pub ldap: Option<String>,
    #[serde(rename = "leadership", skip_serializing_if = "Option::is_none")]
    pub leadership: Option<String>,
    #[serde(rename = "log_forwarding", skip_serializing_if = "Option::is_none")]
    pub log_forwarding: Option<String>,
    #[serde(rename = "m_queue", skip_serializing_if = "Option::is_none")]
    pub m_queue: Option<String>,
    #[serde(rename = "migration_status", skip_serializing_if = "Option::is_none")]
    pub migration_status: Option<String>,
    #[serde(rename = "migrations", skip_serializing_if = "Option::is_none")]
    pub migrations: Option<String>,
    #[serde(rename = "producers", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub producers: Option<Option<serde_json::Value>>,
    #[serde(rename = "producers_status", skip_serializing_if = "Option::is_none")]
    pub producers_status: Option<String>,
    #[serde(rename = "rotators", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rotators: Option<Option<serde_json::Value>>,
    #[serde(rename = "saml", skip_serializing_if = "Option::is_none")]
    pub saml: Option<String>,
    #[serde(rename = "universal_identity", skip_serializing_if = "Option::is_none")]
    pub universal_identity: Option<String>,
}

impl ConfigHash {
    pub fn new() -> ConfigHash {
        ConfigHash {
            admins: None,
            ai_insights: None,
            cache: None,
            customer_fragements: None,
            general: None,
            k8s_auths: None,
            kmip: None,
            ldap: None,
            leadership: None,
            log_forwarding: None,
            m_queue: None,
            migration_status: None,
            migrations: None,
            producers: None,
            producers_status: None,
            rotators: None,
            saml: None,
            universal_identity: None,
        }
    }
}

