/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConjurPayload {
    #[serde(rename = "conjur_account", skip_serializing_if = "Option::is_none")]
    pub conjur_account: Option<String>,
    #[serde(rename = "conjur_api_key", skip_serializing_if = "Option::is_none")]
    pub conjur_api_key: Option<String>,
    #[serde(rename = "conjur_url", skip_serializing_if = "Option::is_none")]
    pub conjur_url: Option<String>,
    #[serde(rename = "conjur_username", skip_serializing_if = "Option::is_none")]
    pub conjur_username: Option<String>,
}

impl ConjurPayload {
    pub fn new() -> ConjurPayload {
        ConjurPayload {
            conjur_account: None,
            conjur_api_key: None,
            conjur_url: None,
            conjur_username: None,
        }
    }
}

