/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateEventForwarder : createEventForwarder is a command that creates a new event forwarder [Deprecated - please use event-forwarder-create-* command]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateEventForwarder {
    /// Workstation Admin Name
    #[serde(rename = "admin-name", skip_serializing_if = "Option::is_none")]
    pub admin_name: Option<String>,
    /// Workstation Admin password
    #[serde(rename = "admin-pwd", skip_serializing_if = "Option::is_none")]
    pub admin_pwd: Option<String>,
    /// The RSA Private Key PEM formatted in base64 to use when connecting to ServiceNow with jwt authentication
    #[serde(rename = "app-private-key-base64", skip_serializing_if = "Option::is_none")]
    pub app_private_key_base64: Option<String>,
    /// The authentication type to use when connecting to ServiceNow (user-pass / jwt)
    #[serde(rename = "auth-type", skip_serializing_if = "Option::is_none")]
    pub auth_type: Option<String>,
    /// The client ID to use when connecting to ServiceNow with jwt authentication
    #[serde(rename = "client-id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// The client secret to use when connecting to ServiceNow with jwt authentication
    #[serde(rename = "client-secret", skip_serializing_if = "Option::is_none")]
    pub client_secret: Option<String>,
    /// Deprecated - use description
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    /// Description of the object
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// A comma seperated list of email addresses to send event to (relevant only for \"email\" Event Forwarder)
    #[serde(rename = "email-to", skip_serializing_if = "Option::is_none")]
    pub email_to: Option<String>,
    /// Event sources
    #[serde(rename = "event-source-locations")]
    pub event_source_locations: Vec<String>,
    /// Event Source type [item, target, auth_method, gateway]
    #[serde(rename = "event-source-type", skip_serializing_if = "Option::is_none")]
    pub event_source_type: Option<String>,
    /// List of event types to notify about [request-access, certificate-pending-expiration, certificate-expired, certificate-provisioning-success, certificate-provisioning-failure, auth-method-pending-expiration, auth-method-expired, rotated-secret-success, rotated-secret-failure, dynamic-secret-failure, multi-auth-failure, uid-rotation-failure, apply-justification, email-auth-method-approved, usage, rotation-usage, gateway-inactive, static-secret-updated]
    #[serde(rename = "event-types", skip_serializing_if = "Option::is_none")]
    pub event_types: Option<Vec<String>>,
    /// Rate of periodic runner repetition in hours
    #[serde(rename = "every", skip_serializing_if = "Option::is_none")]
    pub every: Option<String>,
    #[serde(rename = "forwarder-type")]
    pub forwarder_type: String,
    /// Workstation Host
    #[serde(rename = "host", skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// The name of a key that used to encrypt the EventForwarder secret value (if empty, the account default protectionKey key will be used)
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// EventForwarder name
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "runner-type")]
    pub runner_type: String,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
    /// The user email to use when connecting to ServiceNow with jwt authentication
    #[serde(rename = "user-email", skip_serializing_if = "Option::is_none")]
    pub user_email: Option<String>,
}

impl CreateEventForwarder {
    /// createEventForwarder is a command that creates a new event forwarder [Deprecated - please use event-forwarder-create-* command]
    pub fn new(event_source_locations: Vec<String>, forwarder_type: String, name: String, runner_type: String) -> CreateEventForwarder {
        CreateEventForwarder {
            admin_name: None,
            admin_pwd: None,
            app_private_key_base64: None,
            auth_type: None,
            client_id: None,
            client_secret: None,
            comment: None,
            description: None,
            email_to: None,
            event_source_locations,
            event_source_type: None,
            event_types: None,
            every: None,
            forwarder_type,
            host: None,
            json: None,
            key: None,
            name,
            runner_type,
            token: None,
            uid_token: None,
            user_email: None,
        }
    }
}

