/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateGroup {
    /// Description of the object
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// A short group alias
    #[serde(rename = "group-alias")]
    pub group_alias: String,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Group name
    #[serde(rename = "name")]
    pub name: String,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
    /// A json string defining the access permission assignment for this client
    #[serde(rename = "user-assignment", skip_serializing_if = "Option::is_none")]
    pub user_assignment: Option<String>,
}

impl CreateGroup {
    pub fn new(group_alias: String, name: String) -> CreateGroup {
        CreateGroup {
            description: None,
            group_alias,
            json: None,
            name,
            token: None,
            uid_token: None,
            user_assignment: None,
        }
    }
}

