/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateRole {
    /// Allow this role to view analytics. Currently only 'none', 'own', 'all' values are supported, allowing associated auth methods to view reports produced by the same auth methods.
    #[serde(rename = "analytics-access", skip_serializing_if = "Option::is_none")]
    pub analytics_access: Option<String>,
    /// Allow this role to view audit logs. Currently only 'none', 'own', 'scoped' and 'all' values are supported, allowing associated auth methods to view audit logs produced by the same auth methods.
    #[serde(rename = "audit-access", skip_serializing_if = "Option::is_none")]
    pub audit_access: Option<String>,
    /// Deprecated - use description
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    /// Protection from accidental deletion of this object [true/false]
    #[serde(rename = "delete_protection", skip_serializing_if = "Option::is_none")]
    pub delete_protection: Option<String>,
    /// Description of the object
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Allow this role to view Event Center. Currently only 'none', 'scoped' and 'all' values are supported
    #[serde(rename = "event-center-access", skip_serializing_if = "Option::is_none")]
    pub event_center_access: Option<String>,
    /// Allow this role to manage Event Forwarders. Currently only 'none' and 'all' values are supported.
    #[serde(rename = "event-forwarders-access", skip_serializing_if = "Option::is_none")]
    pub event_forwarders_access: Option<String>,
    /// Allow this role to manage the following Event Forwarders.
    #[serde(rename = "event-forwarders-name", skip_serializing_if = "Option::is_none")]
    pub event_forwarders_name: Option<Vec<String>>,
    /// Allow this role to view gw analytics. Currently only 'none', 'scoped', 'all' values are supported, allowing associated auth methods to view reports produced by the same auth methods.
    #[serde(rename = "gw-analytics-access", skip_serializing_if = "Option::is_none")]
    pub gw_analytics_access: Option<String>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Role name
    #[serde(rename = "name")]
    pub name: String,
    /// Allow this role to view Reverse RBAC. Supported values: 'scoped', 'all'.
    #[serde(rename = "reverse-rbac-access", skip_serializing_if = "Option::is_none")]
    pub reverse_rbac_access: Option<String>,
    /// Allow this role to view SRA Clusters. Currently only 'none', 'scoped', 'all' values are supported.
    #[serde(rename = "sra-reports-access", skip_serializing_if = "Option::is_none")]
    pub sra_reports_access: Option<String>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
    /// Allow this role to view Usage Report. Currently only 'none' and 'all' values are supported.
    #[serde(rename = "usage-reports-access", skip_serializing_if = "Option::is_none")]
    pub usage_reports_access: Option<String>,
}

impl CreateRole {
    pub fn new(name: String) -> CreateRole {
        CreateRole {
            analytics_access: None,
            audit_access: None,
            comment: None,
            delete_protection: None,
            description: None,
            event_center_access: None,
            event_forwarders_access: None,
            event_forwarders_name: None,
            gw_analytics_access: None,
            json: None,
            name,
            reverse_rbac_access: None,
            sra_reports_access: None,
            token: None,
            uid_token: None,
            usage_reports_access: None,
        }
    }
}

