/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSshCertIssuer {
    #[serde(rename = "ProviderType", skip_serializing_if = "Option::is_none")]
    pub provider_type: Option<String>,
    /// Users allowed to fetch the certificate, e.g root,ubuntu
    #[serde(rename = "allowed-users")]
    pub allowed_users: String,
    /// Protection from accidental deletion of this object [true/false]
    #[serde(rename = "delete_protection", skip_serializing_if = "Option::is_none")]
    pub delete_protection: Option<String>,
    /// Description of the object
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Signed certificates with extensions, e.g permit-port-forwarding=\\\"\\\"
    #[serde(rename = "extensions", skip_serializing_if = "Option::is_none")]
    pub extensions: Option<std::collections::HashMap<String, String>>,
    /// Externally provided username [true/false]
    #[serde(rename = "external-username", skip_serializing_if = "Option::is_none")]
    pub external_username: Option<String>,
    /// For externally provided users, denotes the key-name of IdP claim to extract the username from (relevant only for external-username=true)
    #[serde(rename = "fixed-user-claim-keyname", skip_serializing_if = "Option::is_none")]
    pub fixed_user_claim_keyname: Option<String>,
    /// Host provider type [explicit/target], Default Host provider is explicit, Relevant only for Secure Remote Access of ssh cert issuer, ldap rotated secret and ldap dynamic secret
    #[serde(rename = "host-provider", skip_serializing_if = "Option::is_none")]
    pub host_provider: Option<String>,
    /// Additional custom fields to associate with the item
    #[serde(rename = "item-custom-fields", skip_serializing_if = "Option::is_none")]
    pub item_custom_fields: Option<std::collections::HashMap<String, String>>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Deprecated - use description
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<String>,
    /// SSH certificate issuer name
    #[serde(rename = "name")]
    pub name: String,
    /// Signed certificates with principal, e.g example_role1,example_role2
    #[serde(rename = "principals", skip_serializing_if = "Option::is_none")]
    pub principals: Option<String>,
    /// Secure Access SSH control API endpoint. E.g. https://my.sra-server:9900
    #[serde(rename = "secure-access-api", skip_serializing_if = "Option::is_none")]
    pub secure_access_api: Option<String>,
    /// Deprecated. use secure-access-api
    #[serde(rename = "secure-access-bastion-api", skip_serializing_if = "Option::is_none")]
    pub secure_access_bastion_api: Option<String>,
    /// Deprecated. use secure-access-ssh
    #[serde(rename = "secure-access-bastion-ssh", skip_serializing_if = "Option::is_none")]
    pub secure_access_bastion_ssh: Option<String>,
    /// Enable/Disable secure remote access [true/false]
    #[serde(rename = "secure-access-enable", skip_serializing_if = "Option::is_none")]
    pub secure_access_enable: Option<String>,
    /// Enable this flag to enforce connections only to the hosts listed in --secure-access-host
    #[serde(rename = "secure-access-enforce-hosts-restriction", skip_serializing_if = "Option::is_none")]
    pub secure_access_enforce_hosts_restriction: Option<bool>,
    #[serde(rename = "secure-access-gateway", skip_serializing_if = "Option::is_none")]
    pub secure_access_gateway: Option<String>,
    /// Target servers for connections (In case of Linked Target association, host(s) will inherit Linked Target hosts - Relevant only for Dynamic Secrets/producers)
    #[serde(rename = "secure-access-host", skip_serializing_if = "Option::is_none")]
    pub secure_access_host: Option<Vec<String>>,
    /// Bastion's SSH server. E.g. my.sra-server:22
    #[serde(rename = "secure-access-ssh", skip_serializing_if = "Option::is_none")]
    pub secure_access_ssh: Option<String>,
    /// SSH username to connect to target server, must be in 'Allowed Users' list
    #[serde(rename = "secure-access-ssh-creds-user", skip_serializing_if = "Option::is_none")]
    pub secure_access_ssh_creds_user: Option<String>,
    /// Deprecated. Use secure-access-use-internal-ssh-access
    #[serde(rename = "secure-access-use-internal-bastion", skip_serializing_if = "Option::is_none")]
    pub secure_access_use_internal_bastion: Option<bool>,
    /// Use internal SSH Access
    #[serde(rename = "secure-access-use-internal-ssh-access", skip_serializing_if = "Option::is_none")]
    pub secure_access_use_internal_ssh_access: Option<bool>,
    /// A key to sign the certificate with
    #[serde(rename = "signer-key-name")]
    pub signer_key_name: String,
    /// List of the tags attached to this key
    #[serde(rename = "tag", skip_serializing_if = "Option::is_none")]
    pub tag: Option<Vec<String>>,
    /// A list of linked targets to be associated, Relevant only for Secure Remote Access for ssh cert issuer, ldap rotated secret and ldap dynamic secret, To specify multiple targets use argument multiple times
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<Vec<String>>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The requested Time To Live for the certificate, in seconds
    #[serde(rename = "ttl")]
    pub ttl: i64,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl CreateSshCertIssuer {
    pub fn new(allowed_users: String, name: String, signer_key_name: String, ttl: i64) -> CreateSshCertIssuer {
        CreateSshCertIssuer {
            provider_type: None,
            allowed_users,
            delete_protection: None,
            description: None,
            extensions: None,
            external_username: None,
            fixed_user_claim_keyname: None,
            host_provider: None,
            item_custom_fields: None,
            json: None,
            metadata: None,
            name,
            principals: None,
            secure_access_api: None,
            secure_access_bastion_api: None,
            secure_access_bastion_ssh: None,
            secure_access_enable: None,
            secure_access_enforce_hosts_restriction: None,
            secure_access_gateway: None,
            secure_access_host: None,
            secure_access_ssh: None,
            secure_access_ssh_creds_user: None,
            secure_access_use_internal_bastion: None,
            secure_access_use_internal_ssh_access: None,
            signer_key_name,
            tag: None,
            target: None,
            token: None,
            ttl,
            uid_token: None,
        }
    }
}

