/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreatePasskey : CreatePasskey is a command that creates a new passkey
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePasskey {
    /// for personal password manager
    #[serde(rename = "accessibility", skip_serializing_if = "Option::is_none")]
    pub accessibility: Option<String>,
    /// Passkey type; options: [EC256, EC384, EC512]
    #[serde(rename = "alg")]
    pub alg: String,
    /// Protection from accidental deletion of this object [true/false]
    #[serde(rename = "delete_protection", skip_serializing_if = "Option::is_none")]
    pub delete_protection: Option<String>,
    /// Description of the object
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// ClassicKey name
    #[serde(rename = "name")]
    pub name: String,
    /// Originating websites for this passkey
    #[serde(rename = "origin-url", skip_serializing_if = "Option::is_none")]
    pub origin_url: Option<Vec<String>>,
    /// The name of a key that used to encrypt the secret value (if empty, the account default protectionKey key will be used)
    #[serde(rename = "protection-key-name", skip_serializing_if = "Option::is_none")]
    pub protection_key_name: Option<String>,
    /// Add tags attached to this object
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
    /// For Password Management use
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
}

impl CreatePasskey {
    /// CreatePasskey is a command that creates a new passkey
    pub fn new(alg: String, name: String) -> CreatePasskey {
        CreatePasskey {
            accessibility: None,
            alg,
            delete_protection: None,
            description: None,
            json: None,
            name,
            origin_url: None,
            protection_key_name: None,
            tags: None,
            token: None,
            uid_token: None,
            username: None,
        }
    }
}

