/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateGlobalSignAtlasTarget : createGlobalSignAtlasTarget is a command that creates a new target. [Deprecated: Use target-create-globalsign-atlas command]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateGlobalSignAtlasTarget {
    /// API Key of the GlobalSign Atlas account
    #[serde(rename = "api-key")]
    pub api_key: String,
    /// API Secret of the GlobalSign Atlas account
    #[serde(rename = "api-secret")]
    pub api_secret: String,
    /// Deprecated - use description
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    /// Description of the object
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Set the maximum number of versions, limited by the account settings defaults.
    #[serde(rename = "max-versions", skip_serializing_if = "Option::is_none")]
    pub max_versions: Option<String>,
    /// Mutual TLS Certificate contents of the GlobalSign Atlas account encoded in base64, either mtls-cert-file-path or mtls-cert-data-base64 must be supplied
    #[serde(rename = "mtls-cert-data-base64", skip_serializing_if = "Option::is_none")]
    pub mtls_cert_data_base64: Option<String>,
    /// Mutual TLS Key contents of the GlobalSign Atlas account encoded in base64, either mtls-key-file-path or mtls-data-base64 must be supplied
    #[serde(rename = "mtls-key-data-base64", skip_serializing_if = "Option::is_none")]
    pub mtls_key_data_base64: Option<String>,
    /// Target name
    #[serde(rename = "name")]
    pub name: String,
    /// Timeout waiting for certificate validation in Duration format (1h - 1 Hour, 20m - 20 Minutes, 33m3s - 33 Minutes and 3 Seconds), maximum 1h.
    #[serde(rename = "timeout", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<String>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl CreateGlobalSignAtlasTarget {
    /// createGlobalSignAtlasTarget is a command that creates a new target. [Deprecated: Use target-create-globalsign-atlas command]
    pub fn new(api_key: String, api_secret: String, name: String) -> CreateGlobalSignAtlasTarget {
        CreateGlobalSignAtlasTarget {
            api_key,
            api_secret,
            comment: None,
            description: None,
            json: None,
            key: None,
            max_versions: None,
            mtls_cert_data_base64: None,
            mtls_key_data_base64: None,
            name,
            timeout: None,
            token: None,
            uid_token: None,
        }
    }
}

