/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DefaultConfigPart {
    #[serde(rename = "certificate_access_id", skip_serializing_if = "Option::is_none")]
    pub certificate_access_id: Option<String>,
    #[serde(rename = "default_protection_key_id", skip_serializing_if = "Option::is_none")]
    pub default_protection_key_id: Option<i64>,
    #[serde(rename = "default_secret_location", skip_serializing_if = "Option::is_none")]
    pub default_secret_location: Option<String>,
    #[serde(rename = "oidc_access_id", skip_serializing_if = "Option::is_none")]
    pub oidc_access_id: Option<String>,
    #[serde(rename = "saml_access_id", skip_serializing_if = "Option::is_none")]
    pub saml_access_id: Option<String>,
}

impl DefaultConfigPart {
    pub fn new() -> DefaultConfigPart {
        DefaultConfigPart {
            certificate_access_id: None,
            default_protection_key_id: None,
            default_secret_location: None,
            oidc_access_id: None,
            saml_access_id: None,
        }
    }
}

