/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteTargets {
    /// Enforce deletion
    #[serde(rename = "force-deletion", skip_serializing_if = "Option::is_none")]
    pub force_deletion: Option<bool>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Path to delete the targets from
    #[serde(rename = "path")]
    pub path: String,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl DeleteTargets {
    pub fn new(path: String) -> DeleteTargets {
        DeleteTargets {
            force_deletion: None,
            json: None,
            path,
            token: None,
            uid_token: None,
        }
    }
}

