/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeleteTargetAssociation : deleteTargetAssociation is a command that deletes an association between target and item.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteTargetAssociation {
    /// The association id to be deleted
    #[serde(rename = "assoc-id", skip_serializing_if = "Option::is_none")]
    pub assoc_id: Option<String>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Item name
    #[serde(rename = "name")]
    pub name: String,
    /// The target to associate
    #[serde(rename = "target-name", skip_serializing_if = "Option::is_none")]
    pub target_name: Option<String>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl DeleteTargetAssociation {
    /// deleteTargetAssociation is a command that deletes an association between target and item.
    pub fn new(name: String) -> DeleteTargetAssociation {
        DeleteTargetAssociation {
            assoc_id: None,
            json: None,
            name,
            target_name: None,
            token: None,
            uid_token: None,
        }
    }
}

