/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeleteGatewayAllowedAccessId : deleteGatewayAllowedAccessId is a command that deletes access-id
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteGatewayAllowedAccessId {
    /// The access id to be stripped of access to gateway
    #[serde(rename = "access-id")]
    pub access_id: String,
    /// The name of the updated cluster, e.g. acc-abcd12345678/p-123456789012/defaultCluster
    #[serde(rename = "cluster-name")]
    pub cluster_name: String,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl DeleteGatewayAllowedAccessId {
    /// deleteGatewayAllowedAccessId is a command that deletes access-id
    pub fn new(access_id: String, cluster_name: String) -> DeleteGatewayAllowedAccessId {
        DeleteGatewayAllowedAccessId {
            access_id,
            cluster_name,
            json: None,
            token: None,
            uid_token: None,
        }
    }
}

