/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DesktopAppConf {
    #[serde(rename = "default_cert_issuer_id", skip_serializing_if = "Option::is_none")]
    pub default_cert_issuer_id: Option<i64>,
    #[serde(rename = "default_cert_issuer_name", skip_serializing_if = "Option::is_none")]
    pub default_cert_issuer_name: Option<String>,
    #[serde(rename = "secure_web_access_url", skip_serializing_if = "Option::is_none")]
    pub secure_web_access_url: Option<String>,
    #[serde(rename = "secure_web_proxy_url", skip_serializing_if = "Option::is_none")]
    pub secure_web_proxy_url: Option<String>,
}

impl DesktopAppConf {
    pub fn new() -> DesktopAppConf {
        DesktopAppConf {
            default_cert_issuer_id: None,
            default_cert_issuer_name: None,
            secure_web_access_url: None,
            secure_web_proxy_url: None,
        }
    }
}

