/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DynamicSecretMaxTtl {
    #[serde(rename = "enable", skip_serializing_if = "Option::is_none")]
    pub enable: Option<bool>,
    #[serde(rename = "max_ttl_by_minutes", skip_serializing_if = "Option::is_none")]
    pub max_ttl_by_minutes: Option<i64>,
}

impl DynamicSecretMaxTtl {
    pub fn new() -> DynamicSecretMaxTtl {
        DynamicSecretMaxTtl {
            enable: None,
            max_ttl_by_minutes: None,
        }
    }
}

