/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DynamicSecretUpdateEks : dynamicSecretUpdateEks is a command that updates eks dynamic secret
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DynamicSecretUpdateEks {
    /// Protection from accidental deletion of this object [true/false]
    #[serde(rename = "delete_protection", skip_serializing_if = "Option::is_none")]
    pub delete_protection: Option<String>,
    /// Description of the object
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Access Key ID
    #[serde(rename = "eks-access-key-id", skip_serializing_if = "Option::is_none")]
    pub eks_access_key_id: Option<String>,
    /// IAM assume role
    #[serde(rename = "eks-assume-role", skip_serializing_if = "Option::is_none")]
    pub eks_assume_role: Option<String>,
    /// EKS cluster CA certificate
    #[serde(rename = "eks-cluster-ca-cert", skip_serializing_if = "Option::is_none")]
    pub eks_cluster_ca_cert: Option<String>,
    /// EKS cluster URL endpoint
    #[serde(rename = "eks-cluster-endpoint", skip_serializing_if = "Option::is_none")]
    pub eks_cluster_endpoint: Option<String>,
    /// EKS cluster name
    #[serde(rename = "eks-cluster-name", skip_serializing_if = "Option::is_none")]
    pub eks_cluster_name: Option<String>,
    /// Region
    #[serde(rename = "eks-region", skip_serializing_if = "Option::is_none")]
    pub eks_region: Option<String>,
    /// Secret Access Key
    #[serde(rename = "eks-secret-access-key", skip_serializing_if = "Option::is_none")]
    pub eks_secret_access_key: Option<String>,
    /// Additional custom fields to associate with the item
    #[serde(rename = "item-custom-fields", skip_serializing_if = "Option::is_none")]
    pub item_custom_fields: Option<std::collections::HashMap<String, String>>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Dynamic secret name
    #[serde(rename = "name")]
    pub name: String,
    /// Dynamic secret name
    #[serde(rename = "new-name", skip_serializing_if = "Option::is_none")]
    pub new_name: Option<String>,
    /// Dynamic producer encryption key
    #[serde(rename = "producer-encryption-key-name", skip_serializing_if = "Option::is_none")]
    pub producer_encryption_key_name: Option<String>,
    /// Enable Port forwarding while using CLI access
    #[serde(rename = "secure-access-allow-port-forwading", skip_serializing_if = "Option::is_none")]
    pub secure_access_allow_port_forwading: Option<bool>,
    /// Deprecated. use secure-access-certificate-issuer
    #[serde(rename = "secure-access-bastion-issuer", skip_serializing_if = "Option::is_none")]
    pub secure_access_bastion_issuer: Option<String>,
    /// Path to the SSH Certificate Issuer for your Akeyless Secure Access
    #[serde(rename = "secure-access-certificate-issuer", skip_serializing_if = "Option::is_none")]
    pub secure_access_certificate_issuer: Option<String>,
    /// The K8s cluster endpoint URL
    #[serde(rename = "secure-access-cluster-endpoint", skip_serializing_if = "Option::is_none")]
    pub secure_access_cluster_endpoint: Option<String>,
    /// The delay duration, in seconds, to wait after generating just-in-time credentials. Accepted range: 0-120 seconds
    #[serde(rename = "secure-access-delay", skip_serializing_if = "Option::is_none")]
    pub secure_access_delay: Option<i64>,
    /// Enable/Disable secure remote access [true/false]
    #[serde(rename = "secure-access-enable", skip_serializing_if = "Option::is_none")]
    pub secure_access_enable: Option<String>,
    /// Enable Web Secure Remote Access
    #[serde(rename = "secure-access-web", skip_serializing_if = "Option::is_none")]
    pub secure_access_web: Option<bool>,
    /// Add tags attached to this object
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    /// Target name
    #[serde(rename = "target-name", skip_serializing_if = "Option::is_none")]
    pub target_name: Option<String>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
    /// User TTL
    #[serde(rename = "user-ttl", skip_serializing_if = "Option::is_none")]
    pub user_ttl: Option<String>,
}

impl DynamicSecretUpdateEks {
    /// dynamicSecretUpdateEks is a command that updates eks dynamic secret
    pub fn new(name: String) -> DynamicSecretUpdateEks {
        DynamicSecretUpdateEks {
            delete_protection: None,
            description: None,
            eks_access_key_id: None,
            eks_assume_role: None,
            eks_cluster_ca_cert: None,
            eks_cluster_endpoint: None,
            eks_cluster_name: None,
            eks_region: None,
            eks_secret_access_key: None,
            item_custom_fields: None,
            json: None,
            name,
            new_name: None,
            producer_encryption_key_name: None,
            secure_access_allow_port_forwading: None,
            secure_access_bastion_issuer: None,
            secure_access_certificate_issuer: None,
            secure_access_cluster_endpoint: None,
            secure_access_delay: None,
            secure_access_enable: None,
            secure_access_web: None,
            tags: None,
            target_name: None,
            token: None,
            uid_token: None,
            user_ttl: None,
        }
    }
}

