/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DynamicSecretCreateChef : dynamicSecretCreateChef is a command that creates chef dynamic secret
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DynamicSecretCreateChef {
    /// Organizations
    #[serde(rename = "chef-orgs", skip_serializing_if = "Option::is_none")]
    pub chef_orgs: Option<String>,
    /// Server key
    #[serde(rename = "chef-server-key", skip_serializing_if = "Option::is_none")]
    pub chef_server_key: Option<String>,
    /// Server URL
    #[serde(rename = "chef-server-url", skip_serializing_if = "Option::is_none")]
    pub chef_server_url: Option<String>,
    /// Server username
    #[serde(rename = "chef-server-username", skip_serializing_if = "Option::is_none")]
    pub chef_server_username: Option<String>,
    /// Customize how temporary usernames are generated using go template
    #[serde(rename = "custom-username-template", skip_serializing_if = "Option::is_none")]
    pub custom_username_template: Option<String>,
    /// Protection from accidental deletion of this object [true/false]
    #[serde(rename = "delete_protection", skip_serializing_if = "Option::is_none")]
    pub delete_protection: Option<String>,
    /// Description of the object
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Additional custom fields to associate with the item
    #[serde(rename = "item-custom-fields", skip_serializing_if = "Option::is_none")]
    pub item_custom_fields: Option<std::collections::HashMap<String, String>>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Dynamic secret name
    #[serde(rename = "name")]
    pub name: String,
    /// The length of the password to be generated
    #[serde(rename = "password-length", skip_serializing_if = "Option::is_none")]
    pub password_length: Option<String>,
    /// Dynamic producer encryption key
    #[serde(rename = "producer-encryption-key-name", skip_serializing_if = "Option::is_none")]
    pub producer_encryption_key_name: Option<String>,
    /// Skip SSL
    #[serde(rename = "skip-ssl", skip_serializing_if = "Option::is_none")]
    pub skip_ssl: Option<bool>,
    /// Add tags attached to this object
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    /// Target name
    #[serde(rename = "target-name", skip_serializing_if = "Option::is_none")]
    pub target_name: Option<String>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
    /// User TTL
    #[serde(rename = "user-ttl", skip_serializing_if = "Option::is_none")]
    pub user_ttl: Option<String>,
}

impl DynamicSecretCreateChef {
    /// dynamicSecretCreateChef is a command that creates chef dynamic secret
    pub fn new(name: String) -> DynamicSecretCreateChef {
        DynamicSecretCreateChef {
            chef_orgs: None,
            chef_server_key: None,
            chef_server_url: None,
            chef_server_username: None,
            custom_username_template: None,
            delete_protection: None,
            description: None,
            item_custom_fields: None,
            json: None,
            name,
            password_length: None,
            producer_encryption_key_name: None,
            skip_ssl: None,
            tags: None,
            target_name: None,
            token: None,
            uid_token: None,
            user_ttl: None,
        }
    }
}

