/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DynamicSecretCreateK8s : dynamicSecretCreateK8s is a command that creates k8s dynamic secret
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DynamicSecretCreateK8s {
    /// Customize how temporary usernames are generated using go template
    #[serde(rename = "custom-username-template", skip_serializing_if = "Option::is_none")]
    pub custom_username_template: Option<String>,
    /// Protection from accidental deletion of this object [true/false]
    #[serde(rename = "delete_protection", skip_serializing_if = "Option::is_none")]
    pub delete_protection: Option<String>,
    /// Description of the object
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Additional custom fields to associate with the item
    #[serde(rename = "item-custom-fields", skip_serializing_if = "Option::is_none")]
    pub item_custom_fields: Option<std::collections::HashMap<String, String>>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Comma-separated list of allowed K8S namespaces for the generated ServiceAccount (relevant only for k8s-service-account-type=dynamic)
    #[serde(rename = "k8s-allowed-namespaces", skip_serializing_if = "Option::is_none")]
    pub k8s_allowed_namespaces: Option<String>,
    /// K8S cluster CA certificate
    #[serde(rename = "k8s-cluster-ca-cert", skip_serializing_if = "Option::is_none")]
    pub k8s_cluster_ca_cert: Option<String>,
    /// K8S cluster URL endpoint
    #[serde(rename = "k8s-cluster-endpoint", skip_serializing_if = "Option::is_none")]
    pub k8s_cluster_endpoint: Option<String>,
    /// K8S cluster name
    #[serde(rename = "k8s-cluster-name", skip_serializing_if = "Option::is_none")]
    pub k8s_cluster_name: Option<String>,
    /// K8S cluster Bearer token
    #[serde(rename = "k8s-cluster-token", skip_serializing_if = "Option::is_none")]
    pub k8s_cluster_token: Option<String>,
    /// K8S Namespace where the ServiceAccount exists.
    #[serde(rename = "k8s-namespace", skip_serializing_if = "Option::is_none")]
    pub k8s_namespace: Option<String>,
    /// The pre-existing Role or ClusterRole name to bind the generated ServiceAccount to (relevant only for k8s-service-account-type=dynamic)
    #[serde(rename = "k8s-predefined-role-name", skip_serializing_if = "Option::is_none")]
    pub k8s_predefined_role_name: Option<String>,
    /// Specifies the type of the pre-existing K8S role [Role, ClusterRole] (relevant only for k8s-service-account-type=dynamic)
    #[serde(rename = "k8s-predefined-role-type", skip_serializing_if = "Option::is_none")]
    pub k8s_predefined_role_type: Option<String>,
    /// Content of the yaml in a Base64 format.
    #[serde(rename = "k8s-rolebinding-yaml-data", skip_serializing_if = "Option::is_none")]
    pub k8s_rolebinding_yaml_data: Option<String>,
    /// Path to yaml file that contains definitions of K8S role and role binding (relevant only for k8s-service-account-type=dynamic)
    #[serde(rename = "k8s-rolebinding-yaml-def", skip_serializing_if = "Option::is_none")]
    pub k8s_rolebinding_yaml_def: Option<String>,
    /// K8S ServiceAccount to extract token from.
    #[serde(rename = "k8s-service-account", skip_serializing_if = "Option::is_none")]
    pub k8s_service_account: Option<String>,
    /// K8S ServiceAccount type [fixed, dynamic].
    #[serde(rename = "k8s-service-account-type", skip_serializing_if = "Option::is_none")]
    pub k8s_service_account_type: Option<String>,
    /// Dynamic secret name
    #[serde(rename = "name")]
    pub name: String,
    /// Dynamic producer encryption key
    #[serde(rename = "producer-encryption-key-name", skip_serializing_if = "Option::is_none")]
    pub producer_encryption_key_name: Option<String>,
    /// Enable Port forwarding while using CLI access
    #[serde(rename = "secure-access-allow-port-forwading", skip_serializing_if = "Option::is_none")]
    pub secure_access_allow_port_forwading: Option<bool>,
    /// Deprecated. use secure-access-certificate-issuer
    #[serde(rename = "secure-access-bastion-issuer", skip_serializing_if = "Option::is_none")]
    pub secure_access_bastion_issuer: Option<String>,
    /// Path to the SSH Certificate Issuer for your Akeyless Secure Access
    #[serde(rename = "secure-access-certificate-issuer", skip_serializing_if = "Option::is_none")]
    pub secure_access_certificate_issuer: Option<String>,
    /// The K8s cluster endpoint URL
    #[serde(rename = "secure-access-cluster-endpoint", skip_serializing_if = "Option::is_none")]
    pub secure_access_cluster_endpoint: Option<String>,
    /// The K8s dashboard url
    #[serde(rename = "secure-access-dashboard-url", skip_serializing_if = "Option::is_none")]
    pub secure_access_dashboard_url: Option<String>,
    /// The delay duration, in seconds, to wait after generating just-in-time credentials. Accepted range: 0-120 seconds
    #[serde(rename = "secure-access-delay", skip_serializing_if = "Option::is_none")]
    pub secure_access_delay: Option<i64>,
    /// Enable/Disable secure remote access [true/false]
    #[serde(rename = "secure-access-enable", skip_serializing_if = "Option::is_none")]
    pub secure_access_enable: Option<String>,
    /// Enable Web Secure Remote Access
    #[serde(rename = "secure-access-web", skip_serializing_if = "Option::is_none")]
    pub secure_access_web: Option<bool>,
    /// Secure browser via Akeyless's Secure Remote Access (SRA)
    #[serde(rename = "secure-access-web-browsing", skip_serializing_if = "Option::is_none")]
    pub secure_access_web_browsing: Option<bool>,
    /// Web-Proxy via Akeyless's Secure Remote Access (SRA)
    #[serde(rename = "secure-access-web-proxy", skip_serializing_if = "Option::is_none")]
    pub secure_access_web_proxy: Option<bool>,
    /// Add tags attached to this object
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    /// Target name
    #[serde(rename = "target-name", skip_serializing_if = "Option::is_none")]
    pub target_name: Option<String>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
    /// Use the GW's service account
    #[serde(rename = "use-gw-service-account", skip_serializing_if = "Option::is_none")]
    pub use_gw_service_account: Option<bool>,
    /// User TTL
    #[serde(rename = "user-ttl", skip_serializing_if = "Option::is_none")]
    pub user_ttl: Option<String>,
}

impl DynamicSecretCreateK8s {
    /// dynamicSecretCreateK8s is a command that creates k8s dynamic secret
    pub fn new(name: String) -> DynamicSecretCreateK8s {
        DynamicSecretCreateK8s {
            custom_username_template: None,
            delete_protection: None,
            description: None,
            item_custom_fields: None,
            json: None,
            k8s_allowed_namespaces: None,
            k8s_cluster_ca_cert: None,
            k8s_cluster_endpoint: None,
            k8s_cluster_name: None,
            k8s_cluster_token: None,
            k8s_namespace: None,
            k8s_predefined_role_name: None,
            k8s_predefined_role_type: None,
            k8s_rolebinding_yaml_data: None,
            k8s_rolebinding_yaml_def: None,
            k8s_service_account: None,
            k8s_service_account_type: None,
            name,
            producer_encryption_key_name: None,
            secure_access_allow_port_forwading: None,
            secure_access_bastion_issuer: None,
            secure_access_certificate_issuer: None,
            secure_access_cluster_endpoint: None,
            secure_access_dashboard_url: None,
            secure_access_delay: None,
            secure_access_enable: None,
            secure_access_web: None,
            secure_access_web_browsing: None,
            secure_access_web_proxy: None,
            tags: None,
            target_name: None,
            token: None,
            uid_token: None,
            use_gw_service_account: None,
            user_ttl: None,
        }
    }
}

