/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DynamicSecretUpdateOutput {
    #[serde(rename = "dynamic_secret_details", skip_serializing_if = "Option::is_none")]
    pub dynamic_secret_details: Option<Box<models::DsProducerDetails>>,
}

impl DynamicSecretUpdateOutput {
    pub fn new() -> DynamicSecretUpdateOutput {
        DynamicSecretUpdateOutput {
            dynamic_secret_details: None,
        }
    }
}

