/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DynamicSecretUpdatePing : dynamicSecretUpdatePing is a command that updates Ping dynamic secret
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DynamicSecretUpdatePing {
    /// Protection from accidental deletion of this object [true/false]
    #[serde(rename = "delete_protection", skip_serializing_if = "Option::is_none")]
    pub delete_protection: Option<String>,
    /// Description of the object
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Additional custom fields to associate with the item
    #[serde(rename = "item-custom-fields", skip_serializing_if = "Option::is_none")]
    pub item_custom_fields: Option<std::collections::HashMap<String, String>>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Dynamic secret name
    #[serde(rename = "name")]
    pub name: String,
    /// Dynamic secret name
    #[serde(rename = "new-name", skip_serializing_if = "Option::is_none")]
    pub new_name: Option<String>,
    /// Ping Federate administrative port
    #[serde(rename = "ping-administrative-port", skip_serializing_if = "Option::is_none")]
    pub ping_administrative_port: Option<String>,
    /// Set a specific Access Token Management (ATM) instance for the created OAuth Client by providing the ATM Id. If no explicit value is given, the default pingfederate server ATM will be set.
    #[serde(rename = "ping-atm-id", skip_serializing_if = "Option::is_none")]
    pub ping_atm_id: Option<String>,
    /// Ping Federate authorization port
    #[serde(rename = "ping-authorization-port", skip_serializing_if = "Option::is_none")]
    pub ping_authorization_port: Option<String>,
    /// The subject DN of the client certificate. If no explicit value is given, the producer will create CA certificate and matched client certificate and return it as value. Used in conjunction with ping-issuer-dn (relevant for CLIENT_TLS_CERTIFICATE authentication method)
    #[serde(rename = "ping-cert-subject-dn", skip_serializing_if = "Option::is_none")]
    pub ping_cert_subject_dn: Option<String>,
    /// OAuth Client Authentication Type [CLIENT_SECRET, PRIVATE_KEY_JWT, CLIENT_TLS_CERTIFICATE]
    #[serde(rename = "ping-client-authentication-type", skip_serializing_if = "Option::is_none")]
    pub ping_client_authentication_type: Option<String>,
    /// Determines whether PingFederate requires a unique signed JWT from the client for each action (relevant for PRIVATE_KEY_JWT authentication method) [true/false]
    #[serde(rename = "ping-enforce-replay-prevention", skip_serializing_if = "Option::is_none")]
    pub ping_enforce_replay_prevention: Option<String>,
    /// List of OAuth client grant types [IMPLICIT, AUTHORIZATION_CODE, CLIENT_CREDENTIALS, TOKEN_EXCHANGE, REFRESH_TOKEN, ASSERTION_GRANTS, PASSWORD, RESOURCE_OWNER_CREDENTIALS]. If no explicit value is given, AUTHORIZATION_CODE will be selected as default.
    #[serde(rename = "ping-grant-types", skip_serializing_if = "Option::is_none")]
    pub ping_grant_types: Option<Vec<String>>,
    /// Issuer DN of trusted CA certificate that imported into Ping Federate server. You may select \\\"Trust Any\\\" to trust all the existing issuers in Ping Federate server. Used in conjunction with ping-cert-subject-dn (relevant for CLIENT_TLS_CERTIFICATE authentication method)
    #[serde(rename = "ping-issuer-dn", skip_serializing_if = "Option::is_none")]
    pub ping_issuer_dn: Option<String>,
    /// Base64-encoded JSON Web Key Set (JWKS). If no explicit value is given, the producer will create JWKs and matched signed JWT (Sign Algo: RS256) and return it as value (relevant for PRIVATE_KEY_JWT authentication method)
    #[serde(rename = "ping-jwks", skip_serializing_if = "Option::is_none")]
    pub ping_jwks: Option<String>,
    /// The URL of the JSON Web Key Set (JWKS). If no explicit value is given, the producer will create JWKs and matched signed JWT and return it as value (relevant for PRIVATE_KEY_JWT authentication method)
    #[serde(rename = "ping-jwks-url", skip_serializing_if = "Option::is_none")]
    pub ping_jwks_url: Option<String>,
    /// Ping Federate privileged user password
    #[serde(rename = "ping-password", skip_serializing_if = "Option::is_none")]
    pub ping_password: Option<String>,
    /// Ping Federate privileged user
    #[serde(rename = "ping-privileged-user", skip_serializing_if = "Option::is_none")]
    pub ping_privileged_user: Option<String>,
    /// List of URIs to which the OAuth authorization server may redirect the resource owner's user agent after authorization is obtained. At least one redirection URI is required for the AUTHORIZATION_CODE and IMPLICIT grant types.
    #[serde(rename = "ping-redirect-uris", skip_serializing_if = "Option::is_none")]
    pub ping_redirect_uris: Option<Vec<String>>,
    /// Limit the OAuth client to specific scopes list
    #[serde(rename = "ping-restricted-scopes", skip_serializing_if = "Option::is_none")]
    pub ping_restricted_scopes: Option<Vec<String>>,
    /// The signing algorithm that the client must use to sign its request objects [RS256,RS384,RS512,ES256,ES384,ES512,PS256,PS384,PS512] If no explicit value is given, the client can use any of the supported signing algorithms (relevant for PRIVATE_KEY_JWT authentication method)
    #[serde(rename = "ping-signing-algo", skip_serializing_if = "Option::is_none")]
    pub ping_signing_algo: Option<String>,
    /// Ping URL
    #[serde(rename = "ping-url", skip_serializing_if = "Option::is_none")]
    pub ping_url: Option<String>,
    /// Dynamic producer encryption key
    #[serde(rename = "producer-encryption-key-name", skip_serializing_if = "Option::is_none")]
    pub producer_encryption_key_name: Option<String>,
    /// Add tags attached to this object
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    /// Target name
    #[serde(rename = "target-name", skip_serializing_if = "Option::is_none")]
    pub target_name: Option<String>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
    /// The time from dynamic secret creation to expiration.
    #[serde(rename = "user-ttl", skip_serializing_if = "Option::is_none")]
    pub user_ttl: Option<String>,
}

impl DynamicSecretUpdatePing {
    /// dynamicSecretUpdatePing is a command that updates Ping dynamic secret
    pub fn new(name: String) -> DynamicSecretUpdatePing {
        DynamicSecretUpdatePing {
            delete_protection: None,
            description: None,
            item_custom_fields: None,
            json: None,
            name,
            new_name: None,
            ping_administrative_port: None,
            ping_atm_id: None,
            ping_authorization_port: None,
            ping_cert_subject_dn: None,
            ping_client_authentication_type: None,
            ping_enforce_replay_prevention: None,
            ping_grant_types: None,
            ping_issuer_dn: None,
            ping_jwks: None,
            ping_jwks_url: None,
            ping_password: None,
            ping_privileged_user: None,
            ping_redirect_uris: None,
            ping_restricted_scopes: None,
            ping_signing_algo: None,
            ping_url: None,
            producer_encryption_key_name: None,
            tags: None,
            target_name: None,
            token: None,
            uid_token: None,
            user_ttl: None,
        }
    }
}

