/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DynamicSecretCreateHanaDb : dynamicSecretCreateHanaDb is a command that creates hanadb dynamic secret
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DynamicSecretCreateHanaDb {
    /// Customize how temporary usernames are generated using go template
    #[serde(rename = "custom-username-template", skip_serializing_if = "Option::is_none")]
    pub custom_username_template: Option<String>,
    /// Protection from accidental deletion of this object [true/false]
    #[serde(rename = "delete_protection", skip_serializing_if = "Option::is_none")]
    pub delete_protection: Option<String>,
    /// Description of the object
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// HanaDb Name
    #[serde(rename = "hana-dbname", skip_serializing_if = "Option::is_none")]
    pub hana_dbname: Option<String>,
    /// HanaDb Creation statements
    #[serde(rename = "hanadb-create-statements", skip_serializing_if = "Option::is_none")]
    pub hanadb_create_statements: Option<String>,
    /// HanaDb Host
    #[serde(rename = "hanadb-host", skip_serializing_if = "Option::is_none")]
    pub hanadb_host: Option<String>,
    /// HanaDb Password
    #[serde(rename = "hanadb-password", skip_serializing_if = "Option::is_none")]
    pub hanadb_password: Option<String>,
    /// HanaDb Port
    #[serde(rename = "hanadb-port", skip_serializing_if = "Option::is_none")]
    pub hanadb_port: Option<String>,
    /// HanaDb Revocation statements
    #[serde(rename = "hanadb-revocation-statements", skip_serializing_if = "Option::is_none")]
    pub hanadb_revocation_statements: Option<String>,
    /// HanaDb Username
    #[serde(rename = "hanadb-username", skip_serializing_if = "Option::is_none")]
    pub hanadb_username: Option<String>,
    /// Additional custom fields to associate with the item
    #[serde(rename = "item-custom-fields", skip_serializing_if = "Option::is_none")]
    pub item_custom_fields: Option<std::collections::HashMap<String, String>>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Dynamic secret name
    #[serde(rename = "name")]
    pub name: String,
    /// The length of the password to be generated
    #[serde(rename = "password-length", skip_serializing_if = "Option::is_none")]
    pub password_length: Option<String>,
    /// Dynamic producer encryption key
    #[serde(rename = "producer-encryption-key-name", skip_serializing_if = "Option::is_none")]
    pub producer_encryption_key_name: Option<String>,
    /// Deprecated. use secure-access-certificate-issuer
    #[serde(rename = "secure-access-bastion-issuer", skip_serializing_if = "Option::is_none")]
    pub secure_access_bastion_issuer: Option<String>,
    /// Path to the SSH Certificate Issuer for your Akeyless Secure Access
    #[serde(rename = "secure-access-certificate-issuer", skip_serializing_if = "Option::is_none")]
    pub secure_access_certificate_issuer: Option<String>,
    /// The DB name (relevant only for DB Dynamic-Secret)
    #[serde(rename = "secure-access-db-name", skip_serializing_if = "Option::is_none")]
    pub secure_access_db_name: Option<String>,
    /// The DB schema
    #[serde(rename = "secure-access-db-schema", skip_serializing_if = "Option::is_none")]
    pub secure_access_db_schema: Option<String>,
    /// Enable/Disable secure remote access [true/false]
    #[serde(rename = "secure-access-enable", skip_serializing_if = "Option::is_none")]
    pub secure_access_enable: Option<String>,
    /// Target DB servers for connections (In case of Linked Target association, host(s) will inherit Linked Target hosts)
    #[serde(rename = "secure-access-host", skip_serializing_if = "Option::is_none")]
    pub secure_access_host: Option<Vec<String>>,
    /// Enable Web Secure Remote Access
    #[serde(rename = "secure-access-web", skip_serializing_if = "Option::is_none")]
    pub secure_access_web: Option<bool>,
    /// Add tags attached to this object
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    /// Target name
    #[serde(rename = "target-name", skip_serializing_if = "Option::is_none")]
    pub target_name: Option<String>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
    /// User TTL
    #[serde(rename = "user-ttl", skip_serializing_if = "Option::is_none")]
    pub user_ttl: Option<String>,
}

impl DynamicSecretCreateHanaDb {
    /// dynamicSecretCreateHanaDb is a command that creates hanadb dynamic secret
    pub fn new(name: String) -> DynamicSecretCreateHanaDb {
        DynamicSecretCreateHanaDb {
            custom_username_template: None,
            delete_protection: None,
            description: None,
            hana_dbname: None,
            hanadb_create_statements: None,
            hanadb_host: None,
            hanadb_password: None,
            hanadb_port: None,
            hanadb_revocation_statements: None,
            hanadb_username: None,
            item_custom_fields: None,
            json: None,
            name,
            password_length: None,
            producer_encryption_key_name: None,
            secure_access_bastion_issuer: None,
            secure_access_certificate_issuer: None,
            secure_access_db_name: None,
            secure_access_db_schema: None,
            secure_access_enable: None,
            secure_access_host: None,
            secure_access_web: None,
            tags: None,
            target_name: None,
            token: None,
            uid_token: None,
            user_ttl: None,
        }
    }
}

