/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EksTargetDetails : EKSTargetDetails defines details related to connecting to a EKS (Elastic Container Service) target
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EksTargetDetails {
    #[serde(rename = "eks_access_key_id", skip_serializing_if = "Option::is_none")]
    pub eks_access_key_id: Option<String>,
    #[serde(rename = "eks_cluster_ca_certificate", skip_serializing_if = "Option::is_none")]
    pub eks_cluster_ca_certificate: Option<String>,
    #[serde(rename = "eks_cluster_endpoint", skip_serializing_if = "Option::is_none")]
    pub eks_cluster_endpoint: Option<String>,
    #[serde(rename = "eks_cluster_name", skip_serializing_if = "Option::is_none")]
    pub eks_cluster_name: Option<String>,
    #[serde(rename = "eks_region", skip_serializing_if = "Option::is_none")]
    pub eks_region: Option<String>,
    #[serde(rename = "eks_secret_access_key", skip_serializing_if = "Option::is_none")]
    pub eks_secret_access_key: Option<String>,
    #[serde(rename = "use_gw_cloud_identity", skip_serializing_if = "Option::is_none")]
    pub use_gw_cloud_identity: Option<bool>,
}

impl EksTargetDetails {
    /// EKSTargetDetails defines details related to connecting to a EKS (Elastic Container Service) target
    pub fn new() -> EksTargetDetails {
        EksTargetDetails {
            eks_access_key_id: None,
            eks_cluster_ca_certificate: None,
            eks_cluster_endpoint: None,
            eks_cluster_name: None,
            eks_region: None,
            eks_secret_access_key: None,
            use_gw_cloud_identity: None,
        }
    }
}

