/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ElasticsearchLogForwardingConfig {
    #[serde(rename = "elasticsearch_api_key", skip_serializing_if = "Option::is_none")]
    pub elasticsearch_api_key: Option<String>,
    #[serde(rename = "elasticsearch_auth_type", skip_serializing_if = "Option::is_none")]
    pub elasticsearch_auth_type: Option<String>,
    #[serde(rename = "elasticsearch_cloud_id", skip_serializing_if = "Option::is_none")]
    pub elasticsearch_cloud_id: Option<String>,
    #[serde(rename = "elasticsearch_enable_tls", skip_serializing_if = "Option::is_none")]
    pub elasticsearch_enable_tls: Option<bool>,
    #[serde(rename = "elasticsearch_index", skip_serializing_if = "Option::is_none")]
    pub elasticsearch_index: Option<String>,
    #[serde(rename = "elasticsearch_nodes", skip_serializing_if = "Option::is_none")]
    pub elasticsearch_nodes: Option<String>,
    #[serde(rename = "elasticsearch_password", skip_serializing_if = "Option::is_none")]
    pub elasticsearch_password: Option<String>,
    #[serde(rename = "elasticsearch_server_type", skip_serializing_if = "Option::is_none")]
    pub elasticsearch_server_type: Option<String>,
    #[serde(rename = "elasticsearch_tls_certificate", skip_serializing_if = "Option::is_none")]
    pub elasticsearch_tls_certificate: Option<String>,
    #[serde(rename = "elasticsearch_user_name", skip_serializing_if = "Option::is_none")]
    pub elasticsearch_user_name: Option<String>,
}

impl ElasticsearchLogForwardingConfig {
    pub fn new() -> ElasticsearchLogForwardingConfig {
        ElasticsearchLogForwardingConfig {
            elasticsearch_api_key: None,
            elasticsearch_auth_type: None,
            elasticsearch_cloud_id: None,
            elasticsearch_enable_tls: None,
            elasticsearch_index: None,
            elasticsearch_nodes: None,
            elasticsearch_password: None,
            elasticsearch_server_type: None,
            elasticsearch_tls_certificate: None,
            elasticsearch_user_name: None,
        }
    }
}

