/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmailEntry {
    #[serde(rename = "to_email", skip_serializing_if = "Option::is_none")]
    pub to_email: Option<String>,
    #[serde(rename = "to_name", skip_serializing_if = "Option::is_none")]
    pub to_name: Option<String>,
}

impl EmailEntry {
    pub fn new() -> EmailEntry {
        EmailEntry {
            to_email: None,
            to_name: None,
        }
    }
}

