/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmailPassAccessRules {
    #[serde(rename = "alg", skip_serializing_if = "Option::is_none")]
    pub alg: Option<String>,
    /// The Email value
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// EncEmailWithSharedKey is the email of this auth method, encrypted with the shared auth/uam key (for use in uam)
    #[serde(rename = "enc_email_with_shared_key", skip_serializing_if = "Option::is_none")]
    pub enc_email_with_shared_key: Option<String>,
    /// The password value
    #[serde(rename = "hash_pass", skip_serializing_if = "Option::is_none")]
    pub hash_pass: Option<String>,
    /// The last password change date
    #[serde(rename = "last_reset_password", skip_serializing_if = "Option::is_none")]
    pub last_reset_password: Option<String>,
    #[serde(rename = "mfa_type", skip_serializing_if = "Option::is_none")]
    pub mfa_type: Option<String>,
}

impl EmailPassAccessRules {
    pub fn new() -> EmailPassAccessRules {
        EmailPassAccessRules {
            alg: None,
            email: None,
            enc_email_with_shared_key: None,
            hash_pass: None,
            last_reset_password: None,
            mfa_type: None,
        }
    }
}

