/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Encrypt {
    /// The display id of the key to use in the encryption process
    #[serde(rename = "display-id", skip_serializing_if = "Option::is_none")]
    pub display_id: Option<String>,
    /// name-value pair that specifies the encryption context to be used for authenticated encryption. If used here, the same value must be supplied to the decrypt command or decryption will fail
    #[serde(rename = "encryption-context", skip_serializing_if = "Option::is_none")]
    pub encryption_context: Option<std::collections::HashMap<String, String>>,
    /// Select default assumed format for any plaintext input. Currently supported options: [base64]
    #[serde(rename = "input-format", skip_serializing_if = "Option::is_none")]
    pub input_format: Option<String>,
    /// The item id of the key to use in the encryption process
    #[serde(rename = "item-id", skip_serializing_if = "Option::is_none")]
    pub item_id: Option<i64>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// The name of the key to use in the encryption process
    #[serde(rename = "key-name")]
    pub key_name: String,
    /// Data to be encrypted
    #[serde(rename = "plaintext", skip_serializing_if = "Option::is_none")]
    pub plaintext: Option<String>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
    /// key version (relevant only for classic key)
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<i32>,
}

impl Encrypt {
    pub fn new(key_name: String) -> Encrypt {
        Encrypt {
            display_id: None,
            encryption_context: None,
            input_format: None,
            item_id: None,
            json: None,
            key_name,
            plaintext: None,
            token: None,
            uid_token: None,
            version: None,
        }
    }
}

