/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EsmGet : esmGet is a command that gets the value and interal details of a secret from an External Secrets Manager
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EsmGet {
    /// Name of the External Secrets Manager item
    #[serde(rename = "esm-name")]
    pub esm_name: String,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// The secret id (or name, for AWS, Azure or K8s targets) to get from the External Secrets Manager
    #[serde(rename = "secret-id")]
    pub secret_id: String,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl EsmGet {
    /// esmGet is a command that gets the value and interal details of a secret from an External Secrets Manager
    pub fn new(esm_name: String, secret_id: String) -> EsmGet {
        EsmGet {
            esm_name,
            json: None,
            secret_id,
            token: None,
            uid_token: None,
        }
    }
}

