/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EsmCreate : esmCreate is a command that creates a new secret in an External Secrets Manager
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EsmCreate {
    /// Use this option if the external secret value is a base64 encoded binary
    #[serde(rename = "binary-value", skip_serializing_if = "Option::is_none")]
    pub binary_value: Option<bool>,
    /// Description of the external secret
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Name of the External Secrets Manager item
    #[serde(rename = "esm-name")]
    pub esm_name: String,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Name for the new external secret
    #[serde(rename = "secret-name")]
    pub secret_name: String,
    /// Tags for the external secret
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<std::collections::HashMap<String, String>>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
    /// Value of the external secret item, either text or base64 encoded binary
    #[serde(rename = "value")]
    pub value: String,
}

impl EsmCreate {
    /// esmCreate is a command that creates a new secret in an External Secrets Manager
    pub fn new(esm_name: String, secret_name: String, value: String) -> EsmCreate {
        EsmCreate {
            binary_value: None,
            description: None,
            esm_name,
            json: None,
            secret_name,
            tags: None,
            token: None,
            uid_token: None,
            value,
        }
    }
}

