/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EventForwarderUpdateEmail : eventForwarderUpdateEmail is a command that updates email event forwarder
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventForwarderUpdateEmail {
    /// Auth Method Event sources
    #[serde(rename = "auth-methods-event-source-locations", skip_serializing_if = "Option::is_none")]
    pub auth_methods_event_source_locations: Option<Vec<String>>,
    /// Description of the object
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// A comma seperated list of email addresses to send event to
    #[serde(rename = "email-to", skip_serializing_if = "Option::is_none")]
    pub email_to: Option<String>,
    /// Enable/Disable Event Forwarder [true/false]
    #[serde(rename = "enable", skip_serializing_if = "Option::is_none")]
    pub enable: Option<String>,
    /// List of event types to notify about [request-access, certificate-pending-expiration, certificate-expired, certificate-provisioning-success, certificate-provisioning-failure, auth-method-pending-expiration, auth-method-expired, next-automatic-rotation, rotated-secret-success, rotated-secret-failure, dynamic-secret-failure, multi-auth-failure, uid-rotation-failure, apply-justification, email-auth-method-approved, usage, rotation-usage, gateway-inactive, static-secret-updated, rate-limiting, usage-report, secret-sync]
    #[serde(rename = "event-types", skip_serializing_if = "Option::is_none")]
    pub event_types: Option<Vec<String>>,
    /// Event sources
    #[serde(rename = "gateways-event-source-locations")]
    pub gateways_event_source_locations: Vec<String>,
    /// Set this option to include event errors details [true/false]
    #[serde(rename = "include-error", skip_serializing_if = "Option::is_none")]
    pub include_error: Option<String>,
    /// Items Event sources
    #[serde(rename = "items-event-source-locations", skip_serializing_if = "Option::is_none")]
    pub items_event_source_locations: Option<Vec<String>>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Whether to keep previous version [true/false]. If not set, use default according to account settings
    #[serde(rename = "keep-prev-version", skip_serializing_if = "Option::is_none")]
    pub keep_prev_version: Option<String>,
    /// The name of a key that used to encrypt the EventForwarder secret value (if empty, the account default protectionKey key will be used)
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// EventForwarder name
    #[serde(rename = "name")]
    pub name: String,
    /// New EventForwarder name
    #[serde(rename = "new-name", skip_serializing_if = "Option::is_none")]
    pub new_name: Option<String>,
    /// Override Akeyless default URL with your Gateway url (port 18888)
    #[serde(rename = "override-url", skip_serializing_if = "Option::is_none")]
    pub override_url: Option<String>,
    /// Targets Event sources
    #[serde(rename = "targets-event-source-locations", skip_serializing_if = "Option::is_none")]
    pub targets_event_source_locations: Option<Vec<String>>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl EventForwarderUpdateEmail {
    /// eventForwarderUpdateEmail is a command that updates email event forwarder
    pub fn new(gateways_event_source_locations: Vec<String>, name: String) -> EventForwarderUpdateEmail {
        EventForwarderUpdateEmail {
            auth_methods_event_source_locations: None,
            description: None,
            email_to: None,
            enable: None,
            event_types: None,
            gateways_event_source_locations,
            include_error: None,
            items_event_source_locations: None,
            json: None,
            keep_prev_version: None,
            key: None,
            name,
            new_name: None,
            override_url: None,
            targets_event_source_locations: None,
            token: None,
            uid_token: None,
        }
    }
}

