/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventForwarderCreateUpdateOutput {
    #[serde(rename = "event_forwarder_id", skip_serializing_if = "Option::is_none")]
    pub event_forwarder_id: Option<i64>,
    #[serde(rename = "event_forwarder_name", skip_serializing_if = "Option::is_none")]
    pub event_forwarder_name: Option<String>,
}

impl EventForwarderCreateUpdateOutput {
    pub fn new() -> EventForwarderCreateUpdateOutput {
        EventForwarderCreateUpdateOutput {
            event_forwarder_id: None,
            event_forwarder_name: None,
        }
    }
}

