/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExportClassicKeyOutput {
    #[serde(rename = "certificatePem", skip_serializing_if = "Option::is_none")]
    pub certificate_pem: Option<String>,
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "ssh", skip_serializing_if = "Option::is_none")]
    pub ssh: Option<String>,
    #[serde(rename = "wrapping-iv", skip_serializing_if = "Option::is_none")]
    pub wrapping_iv: Option<String>,
}

impl ExportClassicKeyOutput {
    pub fn new() -> ExportClassicKeyOutput {
        ExportClassicKeyOutput {
            certificate_pem: None,
            key: None,
            ssh: None,
            wrapping_iv: None,
        }
    }
}

