/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GatewayUpdateProducerDockerhub : gatewayUpdateProducerDockerhub is a command that updates a DOCKERHUB producer [Deprecated: Use dynamic-secret-update-dockerhub command]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GatewayUpdateProducerDockerhub {
    /// Protection from accidental deletion of this object [true/false]
    #[serde(rename = "delete_protection", skip_serializing_if = "Option::is_none")]
    pub delete_protection: Option<String>,
    /// DockerhubPassword is either the user's password access token to manage the repository
    #[serde(rename = "dockerhub-password", skip_serializing_if = "Option::is_none")]
    pub dockerhub_password: Option<String>,
    /// Access token scopes list (comma-separated) to give the dynamic secret valid options are in \"repo:admin\", \"repo:write\", \"repo:read\", \"repo:public_read\"
    #[serde(rename = "dockerhub-token-scopes", skip_serializing_if = "Option::is_none")]
    pub dockerhub_token_scopes: Option<String>,
    /// DockerhubUsername is the name of the user in dockerhub
    #[serde(rename = "dockerhub-username", skip_serializing_if = "Option::is_none")]
    pub dockerhub_username: Option<String>,
    /// Additional custom fields to associate with the item
    #[serde(rename = "item-custom-fields", skip_serializing_if = "Option::is_none")]
    pub item_custom_fields: Option<std::collections::HashMap<String, String>>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Dynamic secret name
    #[serde(rename = "name")]
    pub name: String,
    /// Dynamic secret name
    #[serde(rename = "new-name", skip_serializing_if = "Option::is_none")]
    pub new_name: Option<String>,
    /// Dynamic producer encryption key
    #[serde(rename = "producer-encryption-key-name", skip_serializing_if = "Option::is_none")]
    pub producer_encryption_key_name: Option<String>,
    /// Add tags attached to this object
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    /// Target name
    #[serde(rename = "target-name", skip_serializing_if = "Option::is_none")]
    pub target_name: Option<String>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
    /// User TTL
    #[serde(rename = "user-ttl", skip_serializing_if = "Option::is_none")]
    pub user_ttl: Option<String>,
}

impl GatewayUpdateProducerDockerhub {
    /// gatewayUpdateProducerDockerhub is a command that updates a DOCKERHUB producer [Deprecated: Use dynamic-secret-update-dockerhub command]
    pub fn new(name: String) -> GatewayUpdateProducerDockerhub {
        GatewayUpdateProducerDockerhub {
            delete_protection: None,
            dockerhub_password: None,
            dockerhub_token_scopes: None,
            dockerhub_username: None,
            item_custom_fields: None,
            json: None,
            name,
            new_name: None,
            producer_encryption_key_name: None,
            tags: None,
            target_name: None,
            token: None,
            uid_token: None,
            user_ttl: None,
        }
    }
}

