/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GatewayPartialUpdateK8SAuthConfigOutput {
    #[serde(rename = "cluster_id", skip_serializing_if = "Option::is_none")]
    pub cluster_id: Option<String>,
    #[serde(rename = "parts_change", skip_serializing_if = "Option::is_none")]
    pub parts_change: Option<Box<models::ConfigChange>>,
    #[serde(rename = "total_hash", skip_serializing_if = "Option::is_none")]
    pub total_hash: Option<String>,
}

impl GatewayPartialUpdateK8SAuthConfigOutput {
    pub fn new() -> GatewayPartialUpdateK8SAuthConfigOutput {
        GatewayPartialUpdateK8SAuthConfigOutput {
            cluster_id: None,
            parts_change: None,
            total_hash: None,
        }
    }
}

