/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GatewayUpdateLogForwardingLogzIo : gatewayUpdateLogForwardingLogzIo is a command that updates log forwarding config (logz-io target)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GatewayUpdateLogForwardingLogzIo {
    /// Enable Log Forwarding [true/false]
    #[serde(rename = "enable", skip_serializing_if = "Option::is_none")]
    pub enable: Option<String>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Logz-io token
    #[serde(rename = "logz-io-token", skip_serializing_if = "Option::is_none")]
    pub logz_io_token: Option<String>,
    /// Logs format [text/json]
    #[serde(rename = "output-format", skip_serializing_if = "Option::is_none")]
    pub output_format: Option<String>,
    /// LogzIo protocol [tcp/https]
    #[serde(rename = "protocol", skip_serializing_if = "Option::is_none")]
    pub protocol: Option<String>,
    /// Pull interval in seconds
    #[serde(rename = "pull-interval", skip_serializing_if = "Option::is_none")]
    pub pull_interval: Option<String>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl GatewayUpdateLogForwardingLogzIo {
    /// gatewayUpdateLogForwardingLogzIo is a command that updates log forwarding config (logz-io target)
    pub fn new() -> GatewayUpdateLogForwardingLogzIo {
        GatewayUpdateLogForwardingLogzIo {
            enable: None,
            json: None,
            logz_io_token: None,
            output_format: None,
            protocol: None,
            pull_interval: None,
            token: None,
            uid_token: None,
        }
    }
}

