/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GatewayUpdateTlsCert : gatewayUpdateTlsCert is a command that updates Gateway TLS certificate
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GatewayUpdateTlsCert {
    /// TLS Certificate (base64 encoded)
    #[serde(rename = "cert-data", skip_serializing_if = "Option::is_none")]
    pub cert_data: Option<String>,
    /// How many days before the expiration of the certificate would you like to be notified.
    #[serde(rename = "expiration-event-in", skip_serializing_if = "Option::is_none")]
    pub expiration_event_in: Option<Vec<String>>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// TLS Private Key (base64 encoded)
    #[serde(rename = "key-data", skip_serializing_if = "Option::is_none")]
    pub key_data: Option<String>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl GatewayUpdateTlsCert {
    /// gatewayUpdateTlsCert is a command that updates Gateway TLS certificate
    pub fn new() -> GatewayUpdateTlsCert {
        GatewayUpdateTlsCert {
            cert_data: None,
            expiration_event_in: None,
            json: None,
            key_data: None,
            token: None,
            uid_token: None,
        }
    }
}

