/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GatewayMessageQueueInfo {
    #[serde(rename = "broadcast_queue_name_a", skip_serializing_if = "Option::is_none")]
    pub broadcast_queue_name_a: Option<String>,
    #[serde(rename = "mq_type", skip_serializing_if = "Option::is_none")]
    pub mq_type: Option<String>,
    #[serde(rename = "queue_name", skip_serializing_if = "Option::is_none")]
    pub queue_name: Option<String>,
    #[serde(rename = "queue_url", skip_serializing_if = "Option::is_none")]
    pub queue_url: Option<String>,
}

impl GatewayMessageQueueInfo {
    pub fn new() -> GatewayMessageQueueInfo {
        GatewayMessageQueueInfo {
            broadcast_queue_name_a: None,
            mq_type: None,
            queue_name: None,
            queue_url: None,
        }
    }
}

