/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GatewayUpdateLdapAuthConfig : gatewayUpdateLdapAuth is a command that updates ldap auth config
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GatewayUpdateLdapAuthConfig {
    /// The access ID of the Ldap auth method
    #[serde(rename = "access-id", skip_serializing_if = "Option::is_none")]
    pub access_id: Option<String>,
    /// Bind DN
    #[serde(rename = "bind-dn", skip_serializing_if = "Option::is_none")]
    pub bind_dn: Option<String>,
    /// Bind DN Password
    #[serde(rename = "bind-dn-password", skip_serializing_if = "Option::is_none")]
    pub bind_dn_password: Option<String>,
    /// Group Attr
    #[serde(rename = "group-attr", skip_serializing_if = "Option::is_none")]
    pub group_attr: Option<String>,
    /// Group Dn
    #[serde(rename = "group-dn", skip_serializing_if = "Option::is_none")]
    pub group_dn: Option<String>,
    /// Group Filter
    #[serde(rename = "group-filter", skip_serializing_if = "Option::is_none")]
    pub group_filter: Option<String>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// LDAP CA Certificate (base64 encoded)
    #[serde(rename = "ldap-ca-cert", skip_serializing_if = "Option::is_none")]
    pub ldap_ca_cert: Option<String>,
    /// Enable Ldap [true/false]
    #[serde(rename = "ldap-enable", skip_serializing_if = "Option::is_none")]
    pub ldap_enable: Option<String>,
    /// LDAP Server URL, e.g. ldap://planetexpress.com:389
    #[serde(rename = "ldap-url", skip_serializing_if = "Option::is_none")]
    pub ldap_url: Option<String>,
    /// The private key (base64 encoded), associated with the public key defined in the Ldap auth
    #[serde(rename = "signing-key-data", skip_serializing_if = "Option::is_none")]
    pub signing_key_data: Option<String>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
    /// User Attribute
    #[serde(rename = "user-attribute", skip_serializing_if = "Option::is_none")]
    pub user_attribute: Option<String>,
    /// User DN
    #[serde(rename = "user-dn", skip_serializing_if = "Option::is_none")]
    pub user_dn: Option<String>,
}

impl GatewayUpdateLdapAuthConfig {
    /// gatewayUpdateLdapAuth is a command that updates ldap auth config
    pub fn new() -> GatewayUpdateLdapAuthConfig {
        GatewayUpdateLdapAuthConfig {
            access_id: None,
            bind_dn: None,
            bind_dn_password: None,
            group_attr: None,
            group_dn: None,
            group_filter: None,
            json: None,
            ldap_ca_cert: None,
            ldap_enable: None,
            ldap_url: None,
            signing_key_data: None,
            token: None,
            uid_token: None,
            user_attribute: None,
            user_dn: None,
        }
    }
}

