/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GatewayStopProducerOutput {
    #[serde(rename = "producer_name", skip_serializing_if = "Option::is_none")]
    pub producer_name: Option<String>,
}

impl GatewayStopProducerOutput {
    pub fn new() -> GatewayStopProducerOutput {
        GatewayStopProducerOutput {
            producer_name: None,
        }
    }
}

