/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GatewayUpdateRemoteAccessDesktopApp : gatewayUpdateRemoteAccessDesktopApp is a command that update remote access desktop app config
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GatewayUpdateRemoteAccessDesktopApp {
    #[serde(rename = "desktop-app-secure-web-access-url", skip_serializing_if = "Option::is_none")]
    pub desktop_app_secure_web_access_url: Option<String>,
    #[serde(rename = "desktop-app-secure-web-proxy", skip_serializing_if = "Option::is_none")]
    pub desktop_app_secure_web_proxy: Option<String>,
    #[serde(rename = "desktop-app-ssh-cert-issuer", skip_serializing_if = "Option::is_none")]
    pub desktop_app_ssh_cert_issuer: Option<String>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl GatewayUpdateRemoteAccessDesktopApp {
    /// gatewayUpdateRemoteAccessDesktopApp is a command that update remote access desktop app config
    pub fn new() -> GatewayUpdateRemoteAccessDesktopApp {
        GatewayUpdateRemoteAccessDesktopApp {
            desktop_app_secure_web_access_url: None,
            desktop_app_secure_web_proxy: None,
            desktop_app_ssh_cert_issuer: None,
            json: None,
            token: None,
            uid_token: None,
        }
    }
}

