/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GatewayMigrationCreateOutput {
    #[serde(rename = "migration_name", skip_serializing_if = "Option::is_none")]
    pub migration_name: Option<String>,
}

impl GatewayMigrationCreateOutput {
    pub fn new() -> GatewayMigrationCreateOutput {
        GatewayMigrationCreateOutput {
            migration_name: None,
        }
    }
}

