/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GatewayUpdateProducerMssql : gatewayUpdateProducerMSSQL is a command that updates mssql producer [Deprecated: Use dynamic-secret-update-mssql command]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GatewayUpdateProducerMssql {
    /// Customize how temporary usernames are generated using go template
    #[serde(rename = "custom-username-template", skip_serializing_if = "Option::is_none")]
    pub custom_username_template: Option<String>,
    /// Protection from accidental deletion of this object [true/false]
    #[serde(rename = "delete_protection", skip_serializing_if = "Option::is_none")]
    pub delete_protection: Option<String>,
    /// Additional custom fields to associate with the item
    #[serde(rename = "item-custom-fields", skip_serializing_if = "Option::is_none")]
    pub item_custom_fields: Option<std::collections::HashMap<String, String>>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// CSV of allowed DB names for runtime selection when getting the secret value. Empty => use target DB only; \"*\" => any DB allowed; One or more names => user must choose from this list
    #[serde(rename = "mssql-allowed-db-names", skip_serializing_if = "Option::is_none")]
    pub mssql_allowed_db_names: Option<String>,
    /// MSSQL Creation statements
    #[serde(rename = "mssql-create-statements", skip_serializing_if = "Option::is_none")]
    pub mssql_create_statements: Option<String>,
    /// MSSQL Name
    #[serde(rename = "mssql-dbname", skip_serializing_if = "Option::is_none")]
    pub mssql_dbname: Option<String>,
    /// MSSQL Host
    #[serde(rename = "mssql-host", skip_serializing_if = "Option::is_none")]
    pub mssql_host: Option<String>,
    /// MSSQL Password
    #[serde(rename = "mssql-password", skip_serializing_if = "Option::is_none")]
    pub mssql_password: Option<String>,
    /// MSSQL Port
    #[serde(rename = "mssql-port", skip_serializing_if = "Option::is_none")]
    pub mssql_port: Option<String>,
    /// MSSQL Revocation statements
    #[serde(rename = "mssql-revocation-statements", skip_serializing_if = "Option::is_none")]
    pub mssql_revocation_statements: Option<String>,
    /// MSSQL Username
    #[serde(rename = "mssql-username", skip_serializing_if = "Option::is_none")]
    pub mssql_username: Option<String>,
    /// Dynamic secret name
    #[serde(rename = "name")]
    pub name: String,
    /// Dynamic secret name
    #[serde(rename = "new-name", skip_serializing_if = "Option::is_none")]
    pub new_name: Option<String>,
    /// The length of the password to be generated
    #[serde(rename = "password-length", skip_serializing_if = "Option::is_none")]
    pub password_length: Option<String>,
    /// Dynamic producer encryption key
    #[serde(rename = "producer-encryption-key-name", skip_serializing_if = "Option::is_none")]
    pub producer_encryption_key_name: Option<String>,
    /// Deprecated. use secure-access-certificate-issuer
    #[serde(rename = "secure-access-bastion-issuer", skip_serializing_if = "Option::is_none")]
    pub secure_access_bastion_issuer: Option<String>,
    /// Path to the SSH Certificate Issuer for your Akeyless Secure Access
    #[serde(rename = "secure-access-certificate-issuer", skip_serializing_if = "Option::is_none")]
    pub secure_access_certificate_issuer: Option<String>,
    /// The DB name (relevant only for DB Dynamic-Secret)
    #[serde(rename = "secure-access-db-name", skip_serializing_if = "Option::is_none")]
    pub secure_access_db_name: Option<String>,
    /// The DB schema
    #[serde(rename = "secure-access-db-schema", skip_serializing_if = "Option::is_none")]
    pub secure_access_db_schema: Option<String>,
    /// The delay duration, in seconds, to wait after generating just-in-time credentials. Accepted range: 0-120 seconds
    #[serde(rename = "secure-access-delay", skip_serializing_if = "Option::is_none")]
    pub secure_access_delay: Option<i64>,
    /// Enable/Disable secure remote access [true/false]
    #[serde(rename = "secure-access-enable", skip_serializing_if = "Option::is_none")]
    pub secure_access_enable: Option<String>,
    /// Target DB servers for connections (In case of Linked Target association, host(s) will inherit Linked Target hosts)
    #[serde(rename = "secure-access-host", skip_serializing_if = "Option::is_none")]
    pub secure_access_host: Option<Vec<String>>,
    /// Enable Web Secure Remote Access
    #[serde(rename = "secure-access-web", skip_serializing_if = "Option::is_none")]
    pub secure_access_web: Option<bool>,
    /// Add tags attached to this object
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    /// Target name
    #[serde(rename = "target-name", skip_serializing_if = "Option::is_none")]
    pub target_name: Option<String>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
    /// User TTL
    #[serde(rename = "user-ttl", skip_serializing_if = "Option::is_none")]
    pub user_ttl: Option<String>,
}

impl GatewayUpdateProducerMssql {
    /// gatewayUpdateProducerMSSQL is a command that updates mssql producer [Deprecated: Use dynamic-secret-update-mssql command]
    pub fn new(name: String) -> GatewayUpdateProducerMssql {
        GatewayUpdateProducerMssql {
            custom_username_template: None,
            delete_protection: None,
            item_custom_fields: None,
            json: None,
            mssql_allowed_db_names: None,
            mssql_create_statements: None,
            mssql_dbname: None,
            mssql_host: None,
            mssql_password: None,
            mssql_port: None,
            mssql_revocation_statements: None,
            mssql_username: None,
            name,
            new_name: None,
            password_length: None,
            producer_encryption_key_name: None,
            secure_access_bastion_issuer: None,
            secure_access_certificate_issuer: None,
            secure_access_db_name: None,
            secure_access_db_schema: None,
            secure_access_delay: None,
            secure_access_enable: None,
            secure_access_host: None,
            secure_access_web: None,
            tags: None,
            target_name: None,
            token: None,
            uid_token: None,
            user_ttl: None,
        }
    }
}

