/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GatewayUpdateProducerMongo : gatewayUpdateProducerMongo is a command that updates either mongodb  producer or mongodb atlas producer [Deprecated: Use dynamic-secret-update-mongodb command]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GatewayUpdateProducerMongo {
    /// Customize how temporary usernames are generated using go template
    #[serde(rename = "custom-username-template", skip_serializing_if = "Option::is_none")]
    pub custom_username_template: Option<String>,
    /// Protection from accidental deletion of this object [true/false]
    #[serde(rename = "delete_protection", skip_serializing_if = "Option::is_none")]
    pub delete_protection: Option<String>,
    /// Additional custom fields to associate with the item
    #[serde(rename = "item-custom-fields", skip_serializing_if = "Option::is_none")]
    pub item_custom_fields: Option<std::collections::HashMap<String, String>>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// MongoDB Atlas private key
    #[serde(rename = "mongodb-atlas-api-private-key", skip_serializing_if = "Option::is_none")]
    pub mongodb_atlas_api_private_key: Option<String>,
    /// MongoDB Atlas public key
    #[serde(rename = "mongodb-atlas-api-public-key", skip_serializing_if = "Option::is_none")]
    pub mongodb_atlas_api_public_key: Option<String>,
    /// MongoDB Atlas project ID
    #[serde(rename = "mongodb-atlas-project-id", skip_serializing_if = "Option::is_none")]
    pub mongodb_atlas_project_id: Option<String>,
    /// MongoDB custom data
    #[serde(rename = "mongodb-custom-data", skip_serializing_if = "Option::is_none")]
    pub mongodb_custom_data: Option<String>,
    /// MongoDB server default authentication database
    #[serde(rename = "mongodb-default-auth-db", skip_serializing_if = "Option::is_none")]
    pub mongodb_default_auth_db: Option<String>,
    /// MongoDB server host and port
    #[serde(rename = "mongodb-host-port", skip_serializing_if = "Option::is_none")]
    pub mongodb_host_port: Option<String>,
    /// MongoDB Name
    #[serde(rename = "mongodb-name", skip_serializing_if = "Option::is_none")]
    pub mongodb_name: Option<String>,
    /// MongoDB server password. You will prompted to provide a password if it will not appear in CLI parameters
    #[serde(rename = "mongodb-password", skip_serializing_if = "Option::is_none")]
    pub mongodb_password: Option<String>,
    /// MongoDB Roles
    #[serde(rename = "mongodb-roles", skip_serializing_if = "Option::is_none")]
    pub mongodb_roles: Option<String>,
    /// MongoDB Scopes (Atlas only)
    #[serde(rename = "mongodb-scopes", skip_serializing_if = "Option::is_none")]
    pub mongodb_scopes: Option<String>,
    /// MongoDB server URI
    #[serde(rename = "mongodb-server-uri", skip_serializing_if = "Option::is_none")]
    pub mongodb_server_uri: Option<String>,
    /// MongoDB server URI options
    #[serde(rename = "mongodb-uri-options", skip_serializing_if = "Option::is_none")]
    pub mongodb_uri_options: Option<String>,
    /// MongoDB server username
    #[serde(rename = "mongodb-username", skip_serializing_if = "Option::is_none")]
    pub mongodb_username: Option<String>,
    /// Dynamic secret name
    #[serde(rename = "name")]
    pub name: String,
    /// Dynamic secret name
    #[serde(rename = "new-name", skip_serializing_if = "Option::is_none")]
    pub new_name: Option<String>,
    /// The length of the password to be generated
    #[serde(rename = "password-length", skip_serializing_if = "Option::is_none")]
    pub password_length: Option<String>,
    /// Encrypt producer with following key
    #[serde(rename = "producer-encryption-key-name", skip_serializing_if = "Option::is_none")]
    pub producer_encryption_key_name: Option<String>,
    /// Deprecated. use secure-access-certificate-issuer
    #[serde(rename = "secure-access-bastion-issuer", skip_serializing_if = "Option::is_none")]
    pub secure_access_bastion_issuer: Option<String>,
    /// Path to the SSH Certificate Issuer for your Akeyless Secure Access
    #[serde(rename = "secure-access-certificate-issuer", skip_serializing_if = "Option::is_none")]
    pub secure_access_certificate_issuer: Option<String>,
    /// The DB name (relevant only for DB Dynamic-Secret)
    #[serde(rename = "secure-access-db-name", skip_serializing_if = "Option::is_none")]
    pub secure_access_db_name: Option<String>,
    /// The delay duration, in seconds, to wait after generating just-in-time credentials. Accepted range: 0-120 seconds
    #[serde(rename = "secure-access-delay", skip_serializing_if = "Option::is_none")]
    pub secure_access_delay: Option<i64>,
    /// Enable/Disable secure remote access [true/false]
    #[serde(rename = "secure-access-enable", skip_serializing_if = "Option::is_none")]
    pub secure_access_enable: Option<String>,
    /// Target DB servers for connections (In case of Linked Target association, host(s) will inherit Linked Target hosts)
    #[serde(rename = "secure-access-host", skip_serializing_if = "Option::is_none")]
    pub secure_access_host: Option<Vec<String>>,
    /// Enable Web Secure Remote Access
    #[serde(rename = "secure-access-web", skip_serializing_if = "Option::is_none")]
    pub secure_access_web: Option<bool>,
    /// Add tags attached to this object
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    /// Target name
    #[serde(rename = "target-name", skip_serializing_if = "Option::is_none")]
    pub target_name: Option<String>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
    /// User TTL
    #[serde(rename = "user-ttl", skip_serializing_if = "Option::is_none")]
    pub user_ttl: Option<String>,
}

impl GatewayUpdateProducerMongo {
    /// gatewayUpdateProducerMongo is a command that updates either mongodb  producer or mongodb atlas producer [Deprecated: Use dynamic-secret-update-mongodb command]
    pub fn new(name: String) -> GatewayUpdateProducerMongo {
        GatewayUpdateProducerMongo {
            custom_username_template: None,
            delete_protection: None,
            item_custom_fields: None,
            json: None,
            mongodb_atlas_api_private_key: None,
            mongodb_atlas_api_public_key: None,
            mongodb_atlas_project_id: None,
            mongodb_custom_data: None,
            mongodb_default_auth_db: None,
            mongodb_host_port: None,
            mongodb_name: None,
            mongodb_password: None,
            mongodb_roles: None,
            mongodb_scopes: None,
            mongodb_server_uri: None,
            mongodb_uri_options: None,
            mongodb_username: None,
            name,
            new_name: None,
            password_length: None,
            producer_encryption_key_name: None,
            secure_access_bastion_issuer: None,
            secure_access_certificate_issuer: None,
            secure_access_db_name: None,
            secure_access_delay: None,
            secure_access_enable: None,
            secure_access_host: None,
            secure_access_web: None,
            tags: None,
            target_name: None,
            token: None,
            uid_token: None,
            user_ttl: None,
        }
    }
}

