/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GatewayStartProducer : gatewayStartProducer is a command that starts producer [Deprecated: Use set-item-state command]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GatewayStartProducer {
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Dynamic secret name
    #[serde(rename = "name")]
    pub name: String,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl GatewayStartProducer {
    /// gatewayStartProducer is a command that starts producer [Deprecated: Use set-item-state command]
    pub fn new(name: String) -> GatewayStartProducer {
        GatewayStartProducer {
            json: None,
            name,
            token: None,
            uid_token: None,
        }
    }
}

