/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GcpPayload {
    #[serde(rename = "gcp_credentials_json", skip_serializing_if = "Option::is_none")]
    pub gcp_credentials_json: Option<String>,
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
    #[serde(rename = "use_gw_cloud_identity", skip_serializing_if = "Option::is_none")]
    pub use_gw_cloud_identity: Option<bool>,
}

impl GcpPayload {
    pub fn new() -> GcpPayload {
        GcpPayload {
            gcp_credentials_json: None,
            project_id: None,
            use_gw_cloud_identity: None,
        }
    }
}

