/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GeminiTargetDetails : GeminiTargetDetails defines details related to connecting to a Google Gemini provider
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GeminiTargetDetails {
    #[serde(rename = "api_key", skip_serializing_if = "Option::is_none")]
    pub api_key: Option<String>,
    #[serde(rename = "gemini_url", skip_serializing_if = "Option::is_none")]
    pub gemini_url: Option<String>,
}

impl GeminiTargetDetails {
    /// GeminiTargetDetails defines details related to connecting to a Google Gemini provider
    pub fn new() -> GeminiTargetDetails {
        GeminiTargetDetails {
            api_key: None,
            gemini_url: None,
        }
    }
}

