/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenerateCaOutput {
    #[serde(rename = "intermediate_certificate_name", skip_serializing_if = "Option::is_none")]
    pub intermediate_certificate_name: Option<String>,
    #[serde(rename = "intermediate_issuer_name", skip_serializing_if = "Option::is_none")]
    pub intermediate_issuer_name: Option<String>,
    #[serde(rename = "intermediate_key_name", skip_serializing_if = "Option::is_none")]
    pub intermediate_key_name: Option<String>,
    #[serde(rename = "root_certificate_name", skip_serializing_if = "Option::is_none")]
    pub root_certificate_name: Option<String>,
    #[serde(rename = "root_issuer_name", skip_serializing_if = "Option::is_none")]
    pub root_issuer_name: Option<String>,
    #[serde(rename = "root_key_name", skip_serializing_if = "Option::is_none")]
    pub root_key_name: Option<String>,
}

impl GenerateCaOutput {
    pub fn new() -> GenerateCaOutput {
        GenerateCaOutput {
            intermediate_certificate_name: None,
            intermediate_issuer_name: None,
            intermediate_key_name: None,
            root_certificate_name: None,
            root_issuer_name: None,
            root_key_name: None,
        }
    }
}

