/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLastUserEventStatus {
    #[serde(rename = "event-source", skip_serializing_if = "Option::is_none")]
    pub event_source: Option<String>,
    #[serde(rename = "event-type")]
    pub event_type: String,
    /// Event item name
    #[serde(rename = "item-name")]
    pub item_name: String,
    /// Event item type can be either \"target\" or type of item eg \"static_secret\"/\"dynamic_secret\" To get type of some item run `akeyless describe-item -n {ITEM_NAME} --jq-expression .item_type`
    #[serde(rename = "item-type")]
    pub item_type: String,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// The time back to search the event, for example if the value is \"5m\" we will return the last user event issued in the last 5 minutes. By default, we will search without any time boundary.
    #[serde(rename = "time-back", skip_serializing_if = "Option::is_none")]
    pub time_back: Option<String>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl GetLastUserEventStatus {
    pub fn new(event_type: String, item_name: String, item_type: String) -> GetLastUserEventStatus {
        GetLastUserEventStatus {
            event_source: None,
            event_type,
            item_name,
            item_type,
            json: None,
            time_back: None,
            token: None,
            uid_token: None,
        }
    }
}

