/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetEventForwarderOutput {
    #[serde(rename = "event_forwarder", skip_serializing_if = "Option::is_none")]
    pub event_forwarder: Option<Box<models::NotiForwarder>>,
}

impl GetEventForwarderOutput {
    pub fn new() -> GetEventForwarderOutput {
        GetEventForwarderOutput {
            event_forwarder: None,
        }
    }
}

