/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRsaPublicOutput {
    #[serde(rename = "pem", skip_serializing_if = "Option::is_none")]
    pub pem: Option<String>,
    #[serde(rename = "raw", skip_serializing_if = "Option::is_none")]
    pub raw: Option<String>,
    #[serde(rename = "ssh", skip_serializing_if = "Option::is_none")]
    pub ssh: Option<String>,
}

impl GetRsaPublicOutput {
    pub fn new() -> GetRsaPublicOutput {
        GetRsaPublicOutput {
            pem: None,
            raw: None,
            ssh: None,
        }
    }
}

