/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCertificateValue {
    /// The parent PKI Certificate Issuer's name of the certificate, required when used with display-id and token
    #[serde(rename = "cert-issuer-name", skip_serializing_if = "Option::is_none")]
    pub cert_issuer_name: Option<String>,
    /// Certificate display ID
    #[serde(rename = "display-id", skip_serializing_if = "Option::is_none")]
    pub display_id: Option<String>,
    /// Retrieve the Secret value without checking the Gateway's cache [true/false]. This flag is only relevant when using the RestAPI
    #[serde(rename = "ignore-cache", skip_serializing_if = "Option::is_none")]
    pub ignore_cache: Option<String>,
    /// Token for getting the issued certificate
    #[serde(rename = "issuance-token", skip_serializing_if = "Option::is_none")]
    pub issuance_token: Option<String>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Certificate name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
    /// Certificate version
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<i32>,
}

impl GetCertificateValue {
    pub fn new() -> GetCertificateValue {
        GetCertificateValue {
            cert_issuer_name: None,
            display_id: None,
            ignore_cache: None,
            issuance_token: None,
            json: None,
            name: None,
            token: None,
            uid_token: None,
            version: None,
        }
    }
}

