/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubTargetDetails {
    #[serde(rename = "github_app_id", skip_serializing_if = "Option::is_none")]
    pub github_app_id: Option<i64>,
    #[serde(rename = "github_app_private_key", skip_serializing_if = "Option::is_none")]
    pub github_app_private_key: Option<String>,
    #[serde(rename = "github_base_url", skip_serializing_if = "Option::is_none")]
    pub github_base_url: Option<String>,
}

impl GithubTargetDetails {
    pub fn new() -> GithubTargetDetails {
        GithubTargetDetails {
            github_app_id: None,
            github_app_private_key: None,
            github_base_url: None,
        }
    }
}

