/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GodaddyTargetDetails : GodaddyTargetDetails
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GodaddyTargetDetails {
    #[serde(rename = "imap_fqdn", skip_serializing_if = "Option::is_none")]
    pub imap_fqdn: Option<String>,
    #[serde(rename = "imap_password", skip_serializing_if = "Option::is_none")]
    pub imap_password: Option<String>,
    #[serde(rename = "imap_port", skip_serializing_if = "Option::is_none")]
    pub imap_port: Option<String>,
    #[serde(rename = "imap_user", skip_serializing_if = "Option::is_none")]
    pub imap_user: Option<String>,
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
    /// Optional, used to find the certificate ID in GoDaddy's API
    #[serde(rename = "shopper_id", skip_serializing_if = "Option::is_none")]
    pub shopper_id: Option<String>,
    /// A Duration represents the elapsed time between two instants as an int64 nanosecond count. The representation limits the largest representable duration to approximately 290 years.
    #[serde(rename = "timeout", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<i64>,
    #[serde(rename = "validation_email", skip_serializing_if = "Option::is_none")]
    pub validation_email: Option<String>,
}

impl GodaddyTargetDetails {
    /// GodaddyTargetDetails
    pub fn new() -> GodaddyTargetDetails {
        GodaddyTargetDetails {
            imap_fqdn: None,
            imap_password: None,
            imap_port: None,
            imap_user: None,
            key: None,
            secret: None,
            shopper_id: None,
            timeout: None,
            validation_email: None,
        }
    }
}

