/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GoogleChronicleForwardingConfig {
    #[serde(rename = "customer_id", skip_serializing_if = "Option::is_none")]
    pub customer_id: Option<String>,
    #[serde(rename = "log_type", skip_serializing_if = "Option::is_none")]
    pub log_type: Option<String>,
    #[serde(rename = "region", skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    #[serde(rename = "service_account_key", skip_serializing_if = "Option::is_none")]
    pub service_account_key: Option<String>,
}

impl GoogleChronicleForwardingConfig {
    pub fn new() -> GoogleChronicleForwardingConfig {
        GoogleChronicleForwardingConfig {
            customer_id: None,
            log_type: None,
            region: None,
            service_account_key: None,
        }
    }
}

