/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GwClusterIdentity {
    #[serde(rename = "action_allowed", skip_serializing_if = "Option::is_none")]
    pub action_allowed: Option<bool>,
    #[serde(rename = "allowed", skip_serializing_if = "Option::is_none")]
    pub allowed: Option<bool>,
    #[serde(rename = "allowed_access_ids", skip_serializing_if = "Option::is_none")]
    pub allowed_access_ids: Option<Vec<String>>,
    #[serde(rename = "cluster_name", skip_serializing_if = "Option::is_none")]
    pub cluster_name: Option<String>,
    #[serde(rename = "cluster_url", skip_serializing_if = "Option::is_none")]
    pub cluster_url: Option<String>,
    #[serde(rename = "current_gw", skip_serializing_if = "Option::is_none")]
    pub current_gw: Option<bool>,
    /// Deprecated - use CustomerFragments instead
    #[serde(rename = "customer_fragment_ids", skip_serializing_if = "Option::is_none")]
    pub customer_fragment_ids: Option<Vec<String>>,
    #[serde(rename = "customer_fragments", skip_serializing_if = "Option::is_none")]
    pub customer_fragments: Option<Vec<models::CfInfo>>,
    #[serde(rename = "default_protection_key_id", skip_serializing_if = "Option::is_none")]
    pub default_protection_key_id: Option<i64>,
    #[serde(rename = "default_secret_location", skip_serializing_if = "Option::is_none")]
    pub default_secret_location: Option<String>,
    #[serde(rename = "display_name", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "is_kerberos_auth_enabled", skip_serializing_if = "Option::is_none")]
    pub is_kerberos_auth_enabled: Option<bool>,
    #[serde(rename = "is_ldap_auth_enabled", skip_serializing_if = "Option::is_none")]
    pub is_ldap_auth_enabled: Option<bool>,
    #[serde(rename = "serverless_type", skip_serializing_if = "Option::is_none")]
    pub serverless_type: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "status_description", skip_serializing_if = "Option::is_none")]
    pub status_description: Option<String>,
}

impl GwClusterIdentity {
    pub fn new() -> GwClusterIdentity {
        GwClusterIdentity {
            action_allowed: None,
            allowed: None,
            allowed_access_ids: None,
            cluster_name: None,
            cluster_url: None,
            current_gw: None,
            customer_fragment_ids: None,
            customer_fragments: None,
            default_protection_key_id: None,
            default_secret_location: None,
            display_name: None,
            id: None,
            is_kerberos_auth_enabled: None,
            is_ldap_auth_enabled: None,
            serverless_type: None,
            status: None,
            status_description: None,
        }
    }
}

