/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GwUpdateRemoteAccessSessionLogsSplunk : gwUpdateRemoteAccessSessionLogsSplunk is a command that updates session log forwarding config (splunk target)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GwUpdateRemoteAccessSessionLogsSplunk {
    /// Enable Log Forwarding [true/false]
    #[serde(rename = "enable", skip_serializing_if = "Option::is_none")]
    pub enable: Option<String>,
    /// Enable batch forwarding [true/false]
    #[serde(rename = "enable-batch", skip_serializing_if = "Option::is_none")]
    pub enable_batch: Option<String>,
    /// Enable tls
    #[serde(rename = "enable-tls", skip_serializing_if = "Option::is_none")]
    pub enable_tls: Option<bool>,
    /// Splunk index
    #[serde(rename = "index", skip_serializing_if = "Option::is_none")]
    pub index: Option<String>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Logs format [text/json]
    #[serde(rename = "output-format", skip_serializing_if = "Option::is_none")]
    pub output_format: Option<String>,
    /// Pull interval in seconds
    #[serde(rename = "pull-interval", skip_serializing_if = "Option::is_none")]
    pub pull_interval: Option<String>,
    /// Splunk source
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    /// Splunk source type
    #[serde(rename = "source-type", skip_serializing_if = "Option::is_none")]
    pub source_type: Option<String>,
    /// Splunk token
    #[serde(rename = "splunk-token", skip_serializing_if = "Option::is_none")]
    pub splunk_token: Option<String>,
    /// Splunk server URL
    #[serde(rename = "splunk-url", skip_serializing_if = "Option::is_none")]
    pub splunk_url: Option<String>,
    /// Splunk tls certificate
    #[serde(rename = "tls-certificate", skip_serializing_if = "Option::is_none")]
    pub tls_certificate: Option<String>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl GwUpdateRemoteAccessSessionLogsSplunk {
    /// gwUpdateRemoteAccessSessionLogsSplunk is a command that updates session log forwarding config (splunk target)
    pub fn new() -> GwUpdateRemoteAccessSessionLogsSplunk {
        GwUpdateRemoteAccessSessionLogsSplunk {
            enable: None,
            enable_batch: None,
            enable_tls: None,
            index: None,
            json: None,
            output_format: None,
            pull_interval: None,
            source: None,
            source_type: None,
            splunk_token: None,
            splunk_url: None,
            tls_certificate: None,
            token: None,
            uid_token: None,
        }
    }
}

