/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GwUpdateRemoteAccessSessionLogsDatadog : gwUpdateRemoteAccessSessionLogsDatadog is a command that updates session log forwarding config (datadog target)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GwUpdateRemoteAccessSessionLogsDatadog {
    /// Datadog api key
    #[serde(rename = "api-key", skip_serializing_if = "Option::is_none")]
    pub api_key: Option<String>,
    /// Enable Log Forwarding [true/false]
    #[serde(rename = "enable", skip_serializing_if = "Option::is_none")]
    pub enable: Option<String>,
    /// Datadog host
    #[serde(rename = "host", skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Datadog log service
    #[serde(rename = "log-service", skip_serializing_if = "Option::is_none")]
    pub log_service: Option<String>,
    /// Datadog log source
    #[serde(rename = "log-source", skip_serializing_if = "Option::is_none")]
    pub log_source: Option<String>,
    /// A comma-separated list of Datadog log tags formatted as \"key:value\" strings
    #[serde(rename = "log-tags", skip_serializing_if = "Option::is_none")]
    pub log_tags: Option<String>,
    /// Logs format [text/json]
    #[serde(rename = "output-format", skip_serializing_if = "Option::is_none")]
    pub output_format: Option<String>,
    /// Pull interval in seconds
    #[serde(rename = "pull-interval", skip_serializing_if = "Option::is_none")]
    pub pull_interval: Option<String>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl GwUpdateRemoteAccessSessionLogsDatadog {
    /// gwUpdateRemoteAccessSessionLogsDatadog is a command that updates session log forwarding config (datadog target)
    pub fn new() -> GwUpdateRemoteAccessSessionLogsDatadog {
        GwUpdateRemoteAccessSessionLogsDatadog {
            api_key: None,
            enable: None,
            host: None,
            json: None,
            log_service: None,
            log_source: None,
            log_tags: None,
            output_format: None,
            pull_interval: None,
            token: None,
            uid_token: None,
        }
    }
}

