/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssuerOverviewInfo {
    #[serde(rename = "certificate_authority_mode", skip_serializing_if = "Option::is_none")]
    pub certificate_authority_mode: Option<String>,
    #[serde(rename = "expiration_date", skip_serializing_if = "Option::is_none")]
    pub expiration_date: Option<String>,
    #[serde(rename = "key_type", skip_serializing_if = "Option::is_none")]
    pub key_type: Option<String>,
}

impl IssuerOverviewInfo {
    pub fn new() -> IssuerOverviewInfo {
        IssuerOverviewInfo {
            certificate_authority_mode: None,
            expiration_date: None,
            key_type: None,
        }
    }
}

