/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct K8SPayload {
    #[serde(rename = "ca", skip_serializing_if = "Option::is_none")]
    pub ca: Option<Vec<i32>>,
    #[serde(rename = "client_cert", skip_serializing_if = "Option::is_none")]
    pub client_cert: Option<Vec<i32>>,
    #[serde(rename = "client_key", skip_serializing_if = "Option::is_none")]
    pub client_key: Option<Vec<i32>>,
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(rename = "server", skip_serializing_if = "Option::is_none")]
    pub server: Option<String>,
    #[serde(rename = "skip_system", skip_serializing_if = "Option::is_none")]
    pub skip_system: Option<bool>,
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
}

impl K8SPayload {
    pub fn new() -> K8SPayload {
        K8SPayload {
            ca: None,
            client_cert: None,
            client_key: None,
            namespace: None,
            password: None,
            server: None,
            skip_system: None,
            token: None,
            username: None,
        }
    }
}

