/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct K8SMigration {
    #[serde(rename = "general", skip_serializing_if = "Option::is_none")]
    pub general: Option<Box<models::MigrationGeneral>>,
    #[serde(rename = "payload", skip_serializing_if = "Option::is_none")]
    pub payload: Option<Box<models::K8SPayload>>,
}

impl K8SMigration {
    pub fn new() -> K8SMigration {
        K8SMigration {
            general: None,
            payload: None,
        }
    }
}

