/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KerberosAccessRules {
    #[serde(rename = "sign_public_key", skip_serializing_if = "Option::is_none")]
    pub sign_public_key: Option<String>,
    #[serde(rename = "unique_identifier", skip_serializing_if = "Option::is_none")]
    pub unique_identifier: Option<String>,
}

impl KerberosAccessRules {
    pub fn new() -> KerberosAccessRules {
        KerberosAccessRules {
            sign_public_key: None,
            unique_identifier: None,
        }
    }
}

