/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KmipCreateClient {
    /// If set to 'true', newly created keys on the client will be set to an 'active' state
    #[serde(rename = "activate-keys-on-creation", skip_serializing_if = "Option::is_none")]
    pub activate_keys_on_creation: Option<String>,
    /// Client certificate TTL in days
    #[serde(rename = "certificate-ttl", skip_serializing_if = "Option::is_none")]
    pub certificate_ttl: Option<i64>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Client name
    #[serde(rename = "name")]
    pub name: String,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl KmipCreateClient {
    pub fn new(name: String) -> KmipCreateClient {
        KmipCreateClient {
            activate_keys_on_creation: None,
            certificate_ttl: None,
            json: None,
            name,
            token: None,
            uid_token: None,
        }
    }
}

