/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KmipEnvironmentCreateResponse {
    #[serde(rename = "ca_cert", skip_serializing_if = "Option::is_none")]
    pub ca_cert: Option<Vec<i32>>,
    #[serde(rename = "root", skip_serializing_if = "Option::is_none")]
    pub root: Option<String>,
}

impl KmipEnvironmentCreateResponse {
    pub fn new() -> KmipEnvironmentCreateResponse {
        KmipEnvironmentCreateResponse {
            ca_cert: None,
            root: None,
        }
    }
}

