/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// KmipDeleteServer : kmipDeleteServer is a command that the kmip server (allowed only if it has no clients nor associated items)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KmipDeleteServer {
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl KmipDeleteServer {
    /// kmipDeleteServer is a command that the kmip server (allowed only if it has no clients nor associated items)
    pub fn new() -> KmipDeleteServer {
        KmipDeleteServer {
            json: None,
            token: None,
            uid_token: None,
        }
    }
}

