/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KmipClient {
    #[serde(rename = "activate_keys_on_creation", skip_serializing_if = "Option::is_none")]
    pub activate_keys_on_creation: Option<bool>,
    #[serde(rename = "certificate_issue_date", skip_serializing_if = "Option::is_none")]
    pub certificate_issue_date: Option<String>,
    #[serde(rename = "certificate_ttl_in_seconds", skip_serializing_if = "Option::is_none")]
    pub certificate_ttl_in_seconds: Option<i64>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "rules", skip_serializing_if = "Option::is_none")]
    pub rules: Option<Vec<models::PathRule>>,
}

impl KmipClient {
    pub fn new() -> KmipClient {
        KmipClient {
            activate_keys_on_creation: None,
            certificate_issue_date: None,
            certificate_ttl_in_seconds: None,
            id: None,
            name: None,
            rules: None,
        }
    }
}

