/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KmipDescribeServerOutput {
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[serde(rename = "ca_cert", skip_serializing_if = "Option::is_none")]
    pub ca_cert: Option<Vec<i32>>,
    #[serde(rename = "certificate_issue_date", skip_serializing_if = "Option::is_none")]
    pub certificate_issue_date: Option<String>,
    #[serde(rename = "certificate_ttl_in_seconds", skip_serializing_if = "Option::is_none")]
    pub certificate_ttl_in_seconds: Option<i64>,
    #[serde(rename = "hostname", skip_serializing_if = "Option::is_none")]
    pub hostname: Option<String>,
    #[serde(rename = "root", skip_serializing_if = "Option::is_none")]
    pub root: Option<String>,
}

impl KmipDescribeServerOutput {
    pub fn new() -> KmipDescribeServerOutput {
        KmipDescribeServerOutput {
            active: None,
            ca_cert: None,
            certificate_issue_date: None,
            certificate_ttl_in_seconds: None,
            hostname: None,
            root: None,
        }
    }
}

