/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LogForwardingConfigPart {
    #[serde(rename = "aws_s3_config", skip_serializing_if = "Option::is_none")]
    pub aws_s3_config: Option<Box<models::AwsS3LogForwardingConfig>>,
    #[serde(rename = "azure_analytics_config", skip_serializing_if = "Option::is_none")]
    pub azure_analytics_config: Option<Box<models::AzureLogAnalyticsForwardingConfig>>,
    #[serde(rename = "datadog_config", skip_serializing_if = "Option::is_none")]
    pub datadog_config: Option<Box<models::DatadogForwardingConfig>>,
    #[serde(rename = "elasticsearch_config", skip_serializing_if = "Option::is_none")]
    pub elasticsearch_config: Option<Box<models::ElasticsearchLogForwardingConfig>>,
    #[serde(rename = "google_chronicle_config", skip_serializing_if = "Option::is_none")]
    pub google_chronicle_config: Option<Box<models::GoogleChronicleForwardingConfig>>,
    #[serde(rename = "json_output", skip_serializing_if = "Option::is_none")]
    pub json_output: Option<bool>,
    #[serde(rename = "logan_enable", skip_serializing_if = "Option::is_none")]
    pub logan_enable: Option<bool>,
    #[serde(rename = "logan_url", skip_serializing_if = "Option::is_none")]
    pub logan_url: Option<String>,
    #[serde(rename = "logstash_config", skip_serializing_if = "Option::is_none")]
    pub logstash_config: Option<Box<models::LogstashLogForwardingConfig>>,
    #[serde(rename = "logz_io_config", skip_serializing_if = "Option::is_none")]
    pub logz_io_config: Option<Box<models::LogzIoLogForwardingConfig>>,
    #[serde(rename = "pull_interval_sec", skip_serializing_if = "Option::is_none")]
    pub pull_interval_sec: Option<String>,
    #[serde(rename = "splunk_config", skip_serializing_if = "Option::is_none")]
    pub splunk_config: Option<Box<models::SplunkLogForwardingConfig>>,
    #[serde(rename = "sumo_logic_config", skip_serializing_if = "Option::is_none")]
    pub sumo_logic_config: Option<Box<models::SumologicLogForwardingConfig>>,
    #[serde(rename = "syslog_config", skip_serializing_if = "Option::is_none")]
    pub syslog_config: Option<Box<models::SyslogLogForwardingConfig>>,
    #[serde(rename = "target_log_type", skip_serializing_if = "Option::is_none")]
    pub target_log_type: Option<String>,
}

impl LogForwardingConfigPart {
    pub fn new() -> LogForwardingConfigPart {
        LogForwardingConfigPart {
            aws_s3_config: None,
            azure_analytics_config: None,
            datadog_config: None,
            elasticsearch_config: None,
            google_chronicle_config: None,
            json_output: None,
            logan_enable: None,
            logan_url: None,
            logstash_config: None,
            logz_io_config: None,
            pull_interval_sec: None,
            splunk_config: None,
            sumo_logic_config: None,
            syslog_config: None,
            target_log_type: None,
        }
    }
}

