/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NativeK8sTargetDetails {
    #[serde(rename = "k8s_auth_type", skip_serializing_if = "Option::is_none")]
    pub k8s_auth_type: Option<String>,
    #[serde(rename = "k8s_bearer_token", skip_serializing_if = "Option::is_none")]
    pub k8s_bearer_token: Option<String>,
    /// For K8s Client certificates authentication
    #[serde(rename = "k8s_client_cert_data", skip_serializing_if = "Option::is_none")]
    pub k8s_client_cert_data: Option<String>,
    #[serde(rename = "k8s_client_key_data", skip_serializing_if = "Option::is_none")]
    pub k8s_client_key_data: Option<String>,
    #[serde(rename = "k8s_cluster_ca_certificate", skip_serializing_if = "Option::is_none")]
    pub k8s_cluster_ca_certificate: Option<String>,
    #[serde(rename = "k8s_cluster_endpoint", skip_serializing_if = "Option::is_none")]
    pub k8s_cluster_endpoint: Option<String>,
    #[serde(rename = "k8s_cluster_name", skip_serializing_if = "Option::is_none")]
    pub k8s_cluster_name: Option<String>,
    #[serde(rename = "use_gw_service_account", skip_serializing_if = "Option::is_none")]
    pub use_gw_service_account: Option<bool>,
}

impl NativeK8sTargetDetails {
    pub fn new() -> NativeK8sTargetDetails {
        NativeK8sTargetDetails {
            k8s_auth_type: None,
            k8s_bearer_token: None,
            k8s_client_cert_data: None,
            k8s_client_key_data: None,
            k8s_cluster_ca_certificate: None,
            k8s_cluster_endpoint: None,
            k8s_cluster_name: None,
            use_gw_service_account: None,
        }
    }
}

