/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OAuth2CustomClaim : OAuth2CustomClaim is a custom claim specific to OAuth2 authentication method.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OAuth2CustomClaim {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

impl OAuth2CustomClaim {
    /// OAuth2CustomClaim is a custom claim specific to OAuth2 authentication method.
    pub fn new() -> OAuth2CustomClaim {
        OAuth2CustomClaim {
            name: None,
            values: None,
        }
    }
}

