/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OidcAccessRules : OIDCAccessRules contains access rules specific to Open Id Connect authentication method.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OidcAccessRules {
    /// Allowed redirect URIs after the authentication
    #[serde(rename = "allowed_redirect_URIs", skip_serializing_if = "Option::is_none")]
    pub allowed_redirect_uris: Option<Vec<String>>,
    /// Audience claim to be used as part of the authentication flow. In case set, it must match the one configured on the Identity Provider's Application
    #[serde(rename = "audience", skip_serializing_if = "Option::is_none")]
    pub audience: Option<String>,
    /// The claims that login is restricted to.
    #[serde(rename = "bound_claims", skip_serializing_if = "Option::is_none")]
    pub bound_claims: Option<Vec<models::OidcCustomClaim>>,
    /// Client ID
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// Client Secret
    #[serde(rename = "client_secret", skip_serializing_if = "Option::is_none")]
    pub client_secret: Option<String>,
    /// IsInternal indicates whether this is an internal Auth Method where the client has no control over it, or it was created by the client e.g - Sign In with Google will create an OIDC Auth Method with IsInternal=true
    #[serde(rename = "is_internal", skip_serializing_if = "Option::is_none")]
    pub is_internal: Option<bool>,
    /// Issuer URL
    #[serde(rename = "issuer", skip_serializing_if = "Option::is_none")]
    pub issuer: Option<String>,
    /// A list of required scopes to request from the oidc provider, and to check on the token
    #[serde(rename = "required_scopes", skip_serializing_if = "Option::is_none")]
    pub required_scopes: Option<Vec<String>>,
    /// A prefix to add to the required scopes (for example, azures' Application ID URI)
    #[serde(rename = "required_scopes_prefix", skip_serializing_if = "Option::is_none")]
    pub required_scopes_prefix: Option<String>,
    /// A unique identifier to distinguish different users
    #[serde(rename = "unique_identifier", skip_serializing_if = "Option::is_none")]
    pub unique_identifier: Option<String>,
}

impl OidcAccessRules {
    /// OIDCAccessRules contains access rules specific to Open Id Connect authentication method.
    pub fn new() -> OidcAccessRules {
        OidcAccessRules {
            allowed_redirect_uris: None,
            audience: None,
            bound_claims: None,
            client_id: None,
            client_secret: None,
            is_internal: None,
            issuer: None,
            required_scopes: None,
            required_scopes_prefix: None,
            unique_identifier: None,
        }
    }
}

