/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OpenAiTargetDetails : OpenAITargetDetails defines details related to connecting to an OpenAI provider
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpenAiTargetDetails {
    #[serde(rename = "api_key", skip_serializing_if = "Option::is_none")]
    pub api_key: Option<String>,
    #[serde(rename = "api_key_id", skip_serializing_if = "Option::is_none")]
    pub api_key_id: Option<String>,
    #[serde(rename = "openai_url", skip_serializing_if = "Option::is_none")]
    pub openai_url: Option<String>,
    #[serde(rename = "organization_id", skip_serializing_if = "Option::is_none")]
    pub organization_id: Option<String>,
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
}

impl OpenAiTargetDetails {
    /// OpenAITargetDetails defines details related to connecting to an OpenAI provider
    pub fn new() -> OpenAiTargetDetails {
        OpenAiTargetDetails {
            api_key: None,
            api_key_id: None,
            openai_url: None,
            organization_id: None,
            project_id: None,
        }
    }
}

