/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PasswordSecurityInfo {
    #[serde(rename = "breach_info", skip_serializing_if = "Option::is_none")]
    pub breach_info: Option<Box<models::PasswordBreachInfo>>,
    #[serde(rename = "score_info", skip_serializing_if = "Option::is_none")]
    pub score_info: Option<Box<models::PasswordScoreInfo>>,
}

impl PasswordSecurityInfo {
    pub fn new() -> PasswordSecurityInfo {
        PasswordSecurityInfo {
            breach_info: None,
            score_info: None,
        }
    }
}

