/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PkiCertificateIssueDetails {
    #[serde(rename = "acme_enabled", skip_serializing_if = "Option::is_none")]
    pub acme_enabled: Option<bool>,
    #[serde(rename = "allow_any_name", skip_serializing_if = "Option::is_none")]
    pub allow_any_name: Option<bool>,
    #[serde(rename = "allow_copy_ext_from_csr", skip_serializing_if = "Option::is_none")]
    pub allow_copy_ext_from_csr: Option<bool>,
    #[serde(rename = "allow_subdomains", skip_serializing_if = "Option::is_none")]
    pub allow_subdomains: Option<bool>,
    #[serde(rename = "allowed_domains_list", skip_serializing_if = "Option::is_none")]
    pub allowed_domains_list: Option<Vec<String>>,
    #[serde(rename = "allowed_extra_extensions", skip_serializing_if = "Option::is_none")]
    pub allowed_extra_extensions: Option<std::collections::HashMap<String, Vec<String>>>,
    #[serde(rename = "allowed_ip_sans", skip_serializing_if = "Option::is_none")]
    pub allowed_ip_sans: Option<Vec<String>>,
    #[serde(rename = "allowed_uri_sans", skip_serializing_if = "Option::is_none")]
    pub allowed_uri_sans: Option<Vec<String>>,
    #[serde(rename = "auto_renew_certificate", skip_serializing_if = "Option::is_none")]
    pub auto_renew_certificate: Option<bool>,
    #[serde(rename = "basic_constraints_valid_for_non_ca", skip_serializing_if = "Option::is_none")]
    pub basic_constraints_valid_for_non_ca: Option<bool>,
    #[serde(rename = "certificate_authority_mode", skip_serializing_if = "Option::is_none")]
    pub certificate_authority_mode: Option<String>,
    #[serde(rename = "client_flag", skip_serializing_if = "Option::is_none")]
    pub client_flag: Option<bool>,
    #[serde(rename = "code_signing_flag", skip_serializing_if = "Option::is_none")]
    pub code_signing_flag: Option<bool>,
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<Vec<String>>,
    #[serde(rename = "create_private_crl", skip_serializing_if = "Option::is_none")]
    pub create_private_crl: Option<bool>,
    /// CreatePrivateOcsp enables exposing an OCSP endpoint on the Gateway and embedding its URL in the AIA extension of issued certificates.
    #[serde(rename = "create_private_ocsp", skip_serializing_if = "Option::is_none")]
    pub create_private_ocsp: Option<bool>,
    #[serde(rename = "create_public_crl", skip_serializing_if = "Option::is_none")]
    pub create_public_crl: Option<bool>,
    /// CreatePublicOcsp enables exposing a public OCSP endpoint on the Gateway and embedding its URL in the AIA extension of issued certificates.
    #[serde(rename = "create_public_ocsp", skip_serializing_if = "Option::is_none")]
    pub create_public_ocsp: Option<bool>,
    /// DestinationPath is the destination to save generated certificates
    #[serde(rename = "destination_path", skip_serializing_if = "Option::is_none")]
    pub destination_path: Option<String>,
    #[serde(rename = "disable_wildcards", skip_serializing_if = "Option::is_none")]
    pub disable_wildcards: Option<bool>,
    #[serde(rename = "enforce_hostnames", skip_serializing_if = "Option::is_none")]
    pub enforce_hostnames: Option<bool>,
    /// ExpirationNotification holds a list of expiration notices that should be sent in case a certificate is about to expire, this value is being propagated to the Certificate resources that are created
    #[serde(rename = "expiration_events", skip_serializing_if = "Option::is_none")]
    pub expiration_events: Option<Vec<models::CertificateExpirationEvent>>,
    #[serde(rename = "gw_cluster_id", skip_serializing_if = "Option::is_none")]
    pub gw_cluster_id: Option<i64>,
    /// GWClusterURL is required when CAMode is \"public\" and it defines the cluster URL the PKI should be issued from. The GW cluster must have permissions to read associated target's details
    #[serde(rename = "gw_cluster_url", skip_serializing_if = "Option::is_none")]
    pub gw_cluster_url: Option<String>,
    #[serde(rename = "is_ca", skip_serializing_if = "Option::is_none")]
    pub is_ca: Option<bool>,
    #[serde(rename = "key_bits", skip_serializing_if = "Option::is_none")]
    pub key_bits: Option<i64>,
    #[serde(rename = "key_type", skip_serializing_if = "Option::is_none")]
    pub key_type: Option<String>,
    #[serde(rename = "key_usage_list", skip_serializing_if = "Option::is_none")]
    pub key_usage_list: Option<Vec<String>>,
    #[serde(rename = "locality", skip_serializing_if = "Option::is_none")]
    pub locality: Option<Vec<String>>,
    #[serde(rename = "max_path_len", skip_serializing_if = "Option::is_none")]
    pub max_path_len: Option<i64>,
    #[serde(rename = "non_critical_key_usage", skip_serializing_if = "Option::is_none")]
    pub non_critical_key_usage: Option<bool>,
    /// A Duration represents the elapsed time between two instants as an int64 nanosecond count. The representation limits the largest representable duration to approximately 290 years.
    #[serde(rename = "not_before_duration", skip_serializing_if = "Option::is_none")]
    pub not_before_duration: Option<i64>,
    /// OcspNextUpdate defines the desired NextUpdate window for OCSP responses. Value is in seconds; 0 means not set. Minimum enforced is 10 minutes.
    #[serde(rename = "ocsp_next_update", skip_serializing_if = "Option::is_none")]
    pub ocsp_next_update: Option<i64>,
    #[serde(rename = "organization_list", skip_serializing_if = "Option::is_none")]
    pub organization_list: Option<Vec<String>>,
    #[serde(rename = "organization_unit_list", skip_serializing_if = "Option::is_none")]
    pub organization_unit_list: Option<Vec<String>>,
    #[serde(rename = "pki_issuer_type", skip_serializing_if = "Option::is_none")]
    pub pki_issuer_type: Option<String>,
    #[serde(rename = "postal_code", skip_serializing_if = "Option::is_none")]
    pub postal_code: Option<Vec<String>>,
    /// ProtectGeneratedCertificates dictates whether the created certificates should be protected from deletion
    #[serde(rename = "protect_generated_certificates", skip_serializing_if = "Option::is_none")]
    pub protect_generated_certificates: Option<bool>,
    #[serde(rename = "province", skip_serializing_if = "Option::is_none")]
    pub province: Option<Vec<String>>,
    #[serde(rename = "renew_before_expiration_in_days", skip_serializing_if = "Option::is_none")]
    pub renew_before_expiration_in_days: Option<i64>,
    #[serde(rename = "require_cn", skip_serializing_if = "Option::is_none")]
    pub require_cn: Option<bool>,
    #[serde(rename = "server_flag", skip_serializing_if = "Option::is_none")]
    pub server_flag: Option<bool>,
    #[serde(rename = "street_address", skip_serializing_if = "Option::is_none")]
    pub street_address: Option<Vec<String>>,
}

impl PkiCertificateIssueDetails {
    pub fn new() -> PkiCertificateIssueDetails {
        PkiCertificateIssueDetails {
            acme_enabled: None,
            allow_any_name: None,
            allow_copy_ext_from_csr: None,
            allow_subdomains: None,
            allowed_domains_list: None,
            allowed_extra_extensions: None,
            allowed_ip_sans: None,
            allowed_uri_sans: None,
            auto_renew_certificate: None,
            basic_constraints_valid_for_non_ca: None,
            certificate_authority_mode: None,
            client_flag: None,
            code_signing_flag: None,
            country: None,
            create_private_crl: None,
            create_private_ocsp: None,
            create_public_crl: None,
            create_public_ocsp: None,
            destination_path: None,
            disable_wildcards: None,
            enforce_hostnames: None,
            expiration_events: None,
            gw_cluster_id: None,
            gw_cluster_url: None,
            is_ca: None,
            key_bits: None,
            key_type: None,
            key_usage_list: None,
            locality: None,
            max_path_len: None,
            non_critical_key_usage: None,
            not_before_duration: None,
            ocsp_next_update: None,
            organization_list: None,
            organization_unit_list: None,
            pki_issuer_type: None,
            postal_code: None,
            protect_generated_certificates: None,
            province: None,
            renew_before_expiration_in_days: None,
            require_cn: None,
            server_flag: None,
            street_address: None,
        }
    }
}

