/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PolicyCreateKeys {
    /// Specify allowed key algorithms (e.g., [RSA2048,AES128GCM])
    #[serde(rename = "allowed-algorithms", skip_serializing_if = "Option::is_none")]
    pub allowed_algorithms: Option<Vec<String>>,
    /// Specify allowed protection key names. To enforce using the account's default protection key, use 'default-account-key'
    #[serde(rename = "allowed-key-names", skip_serializing_if = "Option::is_none")]
    pub allowed_key_names: Option<Vec<String>>,
    /// Specify allowed key protection types (dfc, classic-key)
    #[serde(rename = "allowed-key-types", skip_serializing_if = "Option::is_none")]
    pub allowed_key_types: Option<Vec<String>>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Set the maximum rotation interval for automatic key rotation.
    #[serde(rename = "max-rotation-interval-days", skip_serializing_if = "Option::is_none")]
    pub max_rotation_interval_days: Option<i32>,
    /// The object types this policy will apply to (items, targets). If not provided, defaults to [items, targets].
    #[serde(rename = "object-types", skip_serializing_if = "Option::is_none")]
    pub object_types: Option<Vec<String>>,
    /// The path the policy refers to
    #[serde(rename = "path")]
    pub path: String,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl PolicyCreateKeys {
    pub fn new(path: String) -> PolicyCreateKeys {
        PolicyCreateKeys {
            allowed_algorithms: None,
            allowed_key_names: None,
            allowed_key_types: None,
            json: None,
            max_rotation_interval_days: None,
            object_types: None,
            path,
            token: None,
            uid_token: None,
        }
    }
}

