/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProvisionCertificateOutput {
    #[serde(rename = "FailMessage", skip_serializing_if = "Option::is_none")]
    pub fail_message: Option<String>,
    #[serde(rename = "SuccessMessage", skip_serializing_if = "Option::is_none")]
    pub success_message: Option<String>,
    #[serde(rename = "host_names", skip_serializing_if = "Option::is_none")]
    pub host_names: Option<Vec<String>>,
    #[serde(rename = "provisioned_at", skip_serializing_if = "Option::is_none")]
    pub provisioned_at: Option<String>,
}

impl ProvisionCertificateOutput {
    pub fn new() -> ProvisionCertificateOutput {
        ProvisionCertificateOutput {
            fail_message: None,
            success_message: None,
            host_names: None,
            provisioned_at: None,
        }
    }
}

