/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RabbitMqTargetDetails {
    #[serde(rename = "rabbitmq_server_password", skip_serializing_if = "Option::is_none")]
    pub rabbitmq_server_password: Option<String>,
    #[serde(rename = "rabbitmq_server_uri", skip_serializing_if = "Option::is_none")]
    pub rabbitmq_server_uri: Option<String>,
    #[serde(rename = "rabbitmq_server_user", skip_serializing_if = "Option::is_none")]
    pub rabbitmq_server_user: Option<String>,
}

impl RabbitMqTargetDetails {
    pub fn new() -> RabbitMqTargetDetails {
        RabbitMqTargetDetails {
            rabbitmq_server_password: None,
            rabbitmq_server_uri: None,
            rabbitmq_server_user: None,
        }
    }
}

