/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RenewCertificateOutput {
    #[serde(rename = "cert", skip_serializing_if = "Option::is_none")]
    pub cert: Option<String>,
    #[serde(rename = "cert_display_id", skip_serializing_if = "Option::is_none")]
    pub cert_display_id: Option<String>,
    #[serde(rename = "item_id", skip_serializing_if = "Option::is_none")]
    pub item_id: Option<String>,
    #[serde(rename = "parent_cert", skip_serializing_if = "Option::is_none")]
    pub parent_cert: Option<String>,
    #[serde(rename = "private_key", skip_serializing_if = "Option::is_none")]
    pub private_key: Option<String>,
    #[serde(rename = "reading_token", skip_serializing_if = "Option::is_none")]
    pub reading_token: Option<String>,
}

impl RenewCertificateOutput {
    pub fn new() -> RenewCertificateOutput {
        RenewCertificateOutput {
            cert: None,
            cert_display_id: None,
            item_id: None,
            parent_cert: None,
            private_key: None,
            reading_token: None,
        }
    }
}

