/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RequiredActivity {
    #[serde(rename = "migrations_required_activity", skip_serializing_if = "Option::is_none")]
    pub migrations_required_activity: Option<std::collections::HashMap<String, bool>>,
}

impl RequiredActivity {
    pub fn new() -> RequiredActivity {
        RequiredActivity {
            migrations_required_activity: None,
        }
    }
}

