/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReverseRbacClient {
    #[serde(rename = "assocs", skip_serializing_if = "Option::is_none")]
    pub assocs: Option<Vec<models::AuthMethodRoleAssociation>>,
    #[serde(rename = "auth_method_id", skip_serializing_if = "Option::is_none")]
    pub auth_method_id: Option<i64>,
    #[serde(rename = "auth_method_name", skip_serializing_if = "Option::is_none")]
    pub auth_method_name: Option<String>,
}

impl ReverseRbacClient {
    pub fn new() -> ReverseRbacClient {
        ReverseRbacClient {
            assocs: None,
            auth_method_id: None,
            auth_method_name: None,
        }
    }
}

