/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RotatedSecretUpdateLdap {
    #[serde(rename = "ProviderType", skip_serializing_if = "Option::is_none")]
    pub provider_type: Option<String>,
    /// List of the new tags that will be attached to this item
    #[serde(rename = "add-tag", skip_serializing_if = "Option::is_none")]
    pub add_tag: Option<Vec<String>>,
    /// The credentials to connect with use-user-creds/use-target-creds
    #[serde(rename = "authentication-credentials", skip_serializing_if = "Option::is_none")]
    pub authentication_credentials: Option<String>,
    /// Whether to automatically rotate every --rotation-interval days, or disable existing automatic rotation [true/false]
    #[serde(rename = "auto-rotate", skip_serializing_if = "Option::is_none")]
    pub auto_rotate: Option<String>,
    /// Protection from accidental deletion of this object [true/false]
    #[serde(rename = "delete_protection", skip_serializing_if = "Option::is_none")]
    pub delete_protection: Option<String>,
    /// Description of the object
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Host provider type [explicit/target], Default Host provider is explicit, Relevant only for Secure Remote Access of ssh cert issuer, ldap rotated secret and ldap dynamic secret
    #[serde(rename = "host-provider", skip_serializing_if = "Option::is_none")]
    pub host_provider: Option<String>,
    /// Additional custom fields to associate with the item
    #[serde(rename = "item-custom-fields", skip_serializing_if = "Option::is_none")]
    pub item_custom_fields: Option<std::collections::HashMap<String, String>>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Whether to keep previous version [true/false]. If not set, use default according to account settings
    #[serde(rename = "keep-prev-version", skip_serializing_if = "Option::is_none")]
    pub keep_prev_version: Option<String>,
    /// The name of a key that used to encrypt the secret value (if empty, the account default protectionKey key will be used)
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Set the maximum number of versions, limited by the account settings defaults.
    #[serde(rename = "max-versions", skip_serializing_if = "Option::is_none")]
    pub max_versions: Option<String>,
    /// Rotated secret name
    #[serde(rename = "name")]
    pub name: String,
    /// New item name
    #[serde(rename = "new-name", skip_serializing_if = "Option::is_none")]
    pub new_name: Option<String>,
    /// The length of the password to be generated
    #[serde(rename = "password-length", skip_serializing_if = "Option::is_none")]
    pub password_length: Option<String>,
    /// List of the existent tags that will be removed from this item
    #[serde(rename = "rm-tag", skip_serializing_if = "Option::is_none")]
    pub rm_tag: Option<Vec<String>>,
    /// Rotate the value of the secret after SRA session ends [true/false]
    #[serde(rename = "rotate-after-disconnect", skip_serializing_if = "Option::is_none")]
    pub rotate_after_disconnect: Option<String>,
    /// rotated-username password (relevant only for rotator-type=ldap)
    #[serde(rename = "rotated-password", skip_serializing_if = "Option::is_none")]
    pub rotated_password: Option<String>,
    /// username to be rotated, if selected use-self-creds at rotator-creds-type, this username will try to rotate it's own password, if use-target-creds is selected, target credentials will be use to rotate the rotated-password (relevant only for rotator-type=ldap)
    #[serde(rename = "rotated-username", skip_serializing_if = "Option::is_none")]
    pub rotated_username: Option<String>,
    /// How many days before the rotation of the item would you like to be notified
    #[serde(rename = "rotation-event-in", skip_serializing_if = "Option::is_none")]
    pub rotation_event_in: Option<Vec<String>>,
    /// The Hour of the rotation in UTC
    #[serde(rename = "rotation-hour", skip_serializing_if = "Option::is_none")]
    pub rotation_hour: Option<i32>,
    /// The number of days to wait between every automatic key rotation (1-365)
    #[serde(rename = "rotation-interval", skip_serializing_if = "Option::is_none")]
    pub rotation_interval: Option<String>,
    /// Deprecated. use secure-access-certificate-issuer
    #[serde(rename = "secure-access-bastion-issuer", skip_serializing_if = "Option::is_none")]
    pub secure_access_bastion_issuer: Option<String>,
    /// Path to the SSH Certificate Issuer for your Akeyless Secure Access
    #[serde(rename = "secure-access-certificate-issuer", skip_serializing_if = "Option::is_none")]
    pub secure_access_certificate_issuer: Option<String>,
    /// Enable/Disable secure remote access [true/false]
    #[serde(rename = "secure-access-enable", skip_serializing_if = "Option::is_none")]
    pub secure_access_enable: Option<String>,
    /// Target servers for connections (In case of Linked Target association, host(s) will inherit Linked Target hosts - Relevant only for Dynamic Secrets/producers)
    #[serde(rename = "secure-access-host", skip_serializing_if = "Option::is_none")]
    pub secure_access_host: Option<Vec<String>>,
    /// Default domain name server. i.e. microsoft.com
    #[serde(rename = "secure-access-rdp-domain", skip_serializing_if = "Option::is_none")]
    pub secure_access_rdp_domain: Option<String>,
    /// Destination URL to inject secrets
    #[serde(rename = "secure-access-url", skip_serializing_if = "Option::is_none")]
    pub secure_access_url: Option<String>,
    /// Enable Web Secure Remote Access
    #[serde(rename = "secure-access-web", skip_serializing_if = "Option::is_none")]
    pub secure_access_web: Option<bool>,
    /// Secure browser via Akeyless's Secure Remote Access (SRA)
    #[serde(rename = "secure-access-web-browsing", skip_serializing_if = "Option::is_none")]
    pub secure_access_web_browsing: Option<bool>,
    /// Web-Proxy via Akeyless's Secure Remote Access (SRA)
    #[serde(rename = "secure-access-web-proxy", skip_serializing_if = "Option::is_none")]
    pub secure_access_web_proxy: Option<bool>,
    /// A list of linked targets to be associated, Relevant only for Secure Remote Access for ssh cert issuer, ldap rotated secret and ldap dynamic secret, To specify multiple targets use argument multiple times
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<Vec<String>>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
    /// LDAP User Attribute, Default value \"cn\"
    #[serde(rename = "user-attribute", skip_serializing_if = "Option::is_none")]
    pub user_attribute: Option<String>,
    /// Base DN to Perform User Search
    #[serde(rename = "user-dn", skip_serializing_if = "Option::is_none")]
    pub user_dn: Option<String>,
}

impl RotatedSecretUpdateLdap {
    pub fn new(name: String) -> RotatedSecretUpdateLdap {
        RotatedSecretUpdateLdap {
            provider_type: None,
            add_tag: None,
            authentication_credentials: None,
            auto_rotate: None,
            delete_protection: None,
            description: None,
            host_provider: None,
            item_custom_fields: None,
            json: None,
            keep_prev_version: None,
            key: None,
            max_versions: None,
            name,
            new_name: None,
            password_length: None,
            rm_tag: None,
            rotate_after_disconnect: None,
            rotated_password: None,
            rotated_username: None,
            rotation_event_in: None,
            rotation_hour: None,
            rotation_interval: None,
            secure_access_bastion_issuer: None,
            secure_access_certificate_issuer: None,
            secure_access_enable: None,
            secure_access_host: None,
            secure_access_rdp_domain: None,
            secure_access_url: None,
            secure_access_web: None,
            secure_access_web_browsing: None,
            secure_access_web_proxy: None,
            target: None,
            token: None,
            uid_token: None,
            user_attribute: None,
            user_dn: None,
        }
    }
}

