/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RotatedSecretCreateSplunk : rotatedSecretCreateSplunk is a command that creates a rotated secret for a Splunk target. Currently we support target-rotator behavior (rotate credentials on the target itself).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RotatedSecretCreateSplunk {
    /// Token audience for Splunk token creation (required for rotator-type=token)
    #[serde(rename = "audience", skip_serializing_if = "Option::is_none")]
    pub audience: Option<String>,
    /// The credentials to connect with use-user-creds/use-target-creds
    #[serde(rename = "authentication-credentials", skip_serializing_if = "Option::is_none")]
    pub authentication_credentials: Option<String>,
    /// Whether to automatically rotate every --rotation-interval days, or disable existing automatic rotation [true/false]
    #[serde(rename = "auto-rotate", skip_serializing_if = "Option::is_none")]
    pub auto_rotate: Option<String>,
    /// Protection from accidental deletion of this object [true/false]
    #[serde(rename = "delete_protection", skip_serializing_if = "Option::is_none")]
    pub delete_protection: Option<String>,
    /// Description of the object
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Token expiration date in YYYY-MM-DD format (required for rotator-type=token when manual rotation is selected and no existing token is provided). Time will be set to 00:00 UTC.
    #[serde(rename = "expiration-date", skip_serializing_if = "Option::is_none")]
    pub expiration_date: Option<String>,
    /// Current Splunk HEC token value to store (relevant only for rotator-type=hec-token). If not provided, a new HEC input will be created in Splunk.
    #[serde(rename = "hec-token", skip_serializing_if = "Option::is_none")]
    pub hec_token: Option<String>,
    /// Splunk HEC input name to manage  (required for rotator-type=hec-token)
    #[serde(rename = "hec-token-name", skip_serializing_if = "Option::is_none")]
    pub hec_token_name: Option<String>,
    /// Additional custom fields to associate with the item
    #[serde(rename = "item-custom-fields", skip_serializing_if = "Option::is_none")]
    pub item_custom_fields: Option<std::collections::HashMap<String, String>>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// The name of a key that used to encrypt the secret value (if empty, the account default protectionKey key will be used)
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Set the maximum number of versions, limited by the account settings defaults.
    #[serde(rename = "max-versions", skip_serializing_if = "Option::is_none")]
    pub max_versions: Option<String>,
    /// Rotated secret name
    #[serde(rename = "name")]
    pub name: String,
    /// The length of the password to be generated
    #[serde(rename = "password-length", skip_serializing_if = "Option::is_none")]
    pub password_length: Option<String>,
    /// rotated-username password (relevant only for rotator-type=password)
    #[serde(rename = "rotated-password", skip_serializing_if = "Option::is_none")]
    pub rotated_password: Option<String>,
    /// username to be rotated, if selected use-self-creds at rotator-creds-type, this username will try to rotate it's own password, if use-target-creds is selected, target credentials will be use to rotate the rotated-password (relevant only for rotator-type=password)
    #[serde(rename = "rotated-username", skip_serializing_if = "Option::is_none")]
    pub rotated_username: Option<String>,
    /// How many days before the rotation of the item would you like to be notified
    #[serde(rename = "rotation-event-in", skip_serializing_if = "Option::is_none")]
    pub rotation_event_in: Option<Vec<String>>,
    /// The Hour of the rotation in UTC
    #[serde(rename = "rotation-hour", skip_serializing_if = "Option::is_none")]
    pub rotation_hour: Option<i32>,
    /// The number of days to wait between every automatic key rotation (1-365)
    #[serde(rename = "rotation-interval", skip_serializing_if = "Option::is_none")]
    pub rotation_interval: Option<String>,
    /// The rotator type. options: [target/password/token/hec-token]
    #[serde(rename = "rotator-type")]
    pub rotator_type: String,
    /// Current Splunk authentication token to store (relevant only for rotator-type=token). If not provided, a new token will be created in Splunk.
    #[serde(rename = "splunk-token", skip_serializing_if = "Option::is_none")]
    pub splunk_token: Option<String>,
    /// Add tags attached to this object
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    /// The target name to associate
    #[serde(rename = "target-name")]
    pub target_name: String,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// Splunk token owner username (relevant only for rotator-type=token)
    #[serde(rename = "token-owner", skip_serializing_if = "Option::is_none")]
    pub token_owner: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl RotatedSecretCreateSplunk {
    /// rotatedSecretCreateSplunk is a command that creates a rotated secret for a Splunk target. Currently we support target-rotator behavior (rotate credentials on the target itself).
    pub fn new(name: String, rotator_type: String, target_name: String) -> RotatedSecretCreateSplunk {
        RotatedSecretCreateSplunk {
            audience: None,
            authentication_credentials: None,
            auto_rotate: None,
            delete_protection: None,
            description: None,
            expiration_date: None,
            hec_token: None,
            hec_token_name: None,
            item_custom_fields: None,
            json: None,
            key: None,
            max_versions: None,
            name,
            password_length: None,
            rotated_password: None,
            rotated_username: None,
            rotation_event_in: None,
            rotation_hour: None,
            rotation_interval: None,
            rotator_type,
            splunk_token: None,
            tags: None,
            target_name,
            token: None,
            token_owner: None,
            uid_token: None,
        }
    }
}

