/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RotationSecretMaxInterval {
    #[serde(rename = "enable", skip_serializing_if = "Option::is_none")]
    pub enable: Option<bool>,
    #[serde(rename = "max_interval_by_days", skip_serializing_if = "Option::is_none")]
    pub max_interval_by_days: Option<i32>,
}

impl RotationSecretMaxInterval {
    pub fn new() -> RotationSecretMaxInterval {
        RotationSecretMaxInterval {
            enable: None,
            max_interval_by_days: None,
        }
    }
}

