/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RotateKeyOutput : RotateKeyOutput defines output of RotateKey operation
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RotateKeyOutput {
    #[serde(rename = "classic_key_gw_url", skip_serializing_if = "Option::is_none")]
    pub classic_key_gw_url: Option<String>,
    #[serde(rename = "item_type", skip_serializing_if = "Option::is_none")]
    pub item_type: Option<String>,
    #[serde(rename = "new_item_version", skip_serializing_if = "Option::is_none")]
    pub new_item_version: Option<i32>,
    #[serde(rename = "next_rotation_date", skip_serializing_if = "Option::is_none")]
    pub next_rotation_date: Option<String>,
}

impl RotateKeyOutput {
    /// RotateKeyOutput defines output of RotateKey operation
    pub fn new() -> RotateKeyOutput {
        RotateKeyOutput {
            classic_key_gw_url: None,
            item_type: None,
            new_item_version: None,
            next_rotation_date: None,
        }
    }
}

