/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RotatedSecretUpdateCustom {
    /// List of the new tags that will be attached to this item
    #[serde(rename = "add-tag", skip_serializing_if = "Option::is_none")]
    pub add_tag: Option<Vec<String>>,
    /// The credentials to connect with use-user-creds/use-target-creds
    #[serde(rename = "authentication-credentials", skip_serializing_if = "Option::is_none")]
    pub authentication_credentials: Option<String>,
    /// Whether to automatically rotate every --rotation-interval days, or disable existing automatic rotation [true/false]
    #[serde(rename = "auto-rotate", skip_serializing_if = "Option::is_none")]
    pub auto_rotate: Option<String>,
    /// Secret payload to be sent with rotation request
    #[serde(rename = "custom-payload", skip_serializing_if = "Option::is_none")]
    pub custom_payload: Option<String>,
    /// Protection from accidental deletion of this object [true/false]
    #[serde(rename = "delete_protection", skip_serializing_if = "Option::is_none")]
    pub delete_protection: Option<String>,
    /// Description of the object
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Enable password policy
    #[serde(rename = "enable-password-policy", skip_serializing_if = "Option::is_none")]
    pub enable_password_policy: Option<String>,
    /// Additional custom fields to associate with the item
    #[serde(rename = "item-custom-fields", skip_serializing_if = "Option::is_none")]
    pub item_custom_fields: Option<std::collections::HashMap<String, String>>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Whether to keep previous version [true/false]. If not set, use default according to account settings
    #[serde(rename = "keep-prev-version", skip_serializing_if = "Option::is_none")]
    pub keep_prev_version: Option<String>,
    /// The name of a key that used to encrypt the secret value (if empty, the account default protectionKey key will be used)
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Set the maximum number of versions, limited by the account settings defaults.
    #[serde(rename = "max-versions", skip_serializing_if = "Option::is_none")]
    pub max_versions: Option<String>,
    /// Rotated secret name
    #[serde(rename = "name")]
    pub name: String,
    /// New item name
    #[serde(rename = "new-name", skip_serializing_if = "Option::is_none")]
    pub new_name: Option<String>,
    /// The length of the password to be generated
    #[serde(rename = "password-length", skip_serializing_if = "Option::is_none")]
    pub password_length: Option<String>,
    /// List of the existent tags that will be removed from this item
    #[serde(rename = "rm-tag", skip_serializing_if = "Option::is_none")]
    pub rm_tag: Option<Vec<String>>,
    /// Rotate the value of the secret after SRA session ends [true/false]
    #[serde(rename = "rotate-after-disconnect", skip_serializing_if = "Option::is_none")]
    pub rotate_after_disconnect: Option<String>,
    /// How many days before the rotation of the item would you like to be notified
    #[serde(rename = "rotation-event-in", skip_serializing_if = "Option::is_none")]
    pub rotation_event_in: Option<Vec<String>>,
    /// The Hour of the rotation in UTC
    #[serde(rename = "rotation-hour", skip_serializing_if = "Option::is_none")]
    pub rotation_hour: Option<i32>,
    /// The number of days to wait between every automatic key rotation (1-365)
    #[serde(rename = "rotation-interval", skip_serializing_if = "Option::is_none")]
    pub rotation_interval: Option<String>,
    /// Allow providing external user for a domain users
    #[serde(rename = "secure-access-allow-external-user", skip_serializing_if = "Option::is_none")]
    pub secure_access_allow_external_user: Option<bool>,
    /// Deprecated. use secure-access-certificate-issuer
    #[serde(rename = "secure-access-bastion-issuer", skip_serializing_if = "Option::is_none")]
    pub secure_access_bastion_issuer: Option<String>,
    /// Path to the SSH Certificate Issuer for your Akeyless Secure Access
    #[serde(rename = "secure-access-certificate-issuer", skip_serializing_if = "Option::is_none")]
    pub secure_access_certificate_issuer: Option<String>,
    /// Enable/Disable secure remote access [true/false]
    #[serde(rename = "secure-access-enable", skip_serializing_if = "Option::is_none")]
    pub secure_access_enable: Option<String>,
    /// Target servers for connections (In case of Linked Target association, host(s) will inherit Linked Target hosts - Relevant only for Dynamic Secrets/producers)
    #[serde(rename = "secure-access-host", skip_serializing_if = "Option::is_none")]
    pub secure_access_host: Option<Vec<String>>,
    /// Default domain name server. i.e. microsoft.com
    #[serde(rename = "secure-access-rdp-domain", skip_serializing_if = "Option::is_none")]
    pub secure_access_rdp_domain: Option<String>,
    /// Override the RDP Domain username
    #[serde(rename = "secure-access-rdp-user", skip_serializing_if = "Option::is_none")]
    pub secure_access_rdp_user: Option<String>,
    /// Override the SSH username as indicated in SSH Certificate Issuer
    #[serde(rename = "secure-access-ssh-user", skip_serializing_if = "Option::is_none")]
    pub secure_access_ssh_user: Option<String>,
    /// Destination URL to inject secrets
    #[serde(rename = "secure-access-url", skip_serializing_if = "Option::is_none")]
    pub secure_access_url: Option<String>,
    /// Enable Web Secure Remote Access
    #[serde(rename = "secure-access-web", skip_serializing_if = "Option::is_none")]
    pub secure_access_web: Option<bool>,
    /// Secure browser via Akeyless's Secure Remote Access (SRA)
    #[serde(rename = "secure-access-web-browsing", skip_serializing_if = "Option::is_none")]
    pub secure_access_web_browsing: Option<bool>,
    /// Web-Proxy via Akeyless's Secure Remote Access (SRA)
    #[serde(rename = "secure-access-web-proxy", skip_serializing_if = "Option::is_none")]
    pub secure_access_web_proxy: Option<bool>,
    /// Maximum allowed time in seconds for the custom rotator to return the results
    #[serde(rename = "timeout-sec", skip_serializing_if = "Option::is_none")]
    pub timeout_sec: Option<i64>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
    /// Password must contain capital letters [true/false]
    #[serde(rename = "use-capital-letters", skip_serializing_if = "Option::is_none")]
    pub use_capital_letters: Option<String>,
    /// Password must contain lower case letters [true/false]
    #[serde(rename = "use-lower-letters", skip_serializing_if = "Option::is_none")]
    pub use_lower_letters: Option<String>,
    /// Password must contain numbers [true/false]
    #[serde(rename = "use-numbers", skip_serializing_if = "Option::is_none")]
    pub use_numbers: Option<String>,
    /// Password must contain special characters [true/false]
    #[serde(rename = "use-special-characters", skip_serializing_if = "Option::is_none")]
    pub use_special_characters: Option<String>,
}

impl RotatedSecretUpdateCustom {
    pub fn new(name: String) -> RotatedSecretUpdateCustom {
        RotatedSecretUpdateCustom {
            add_tag: None,
            authentication_credentials: None,
            auto_rotate: None,
            custom_payload: None,
            delete_protection: None,
            description: None,
            enable_password_policy: None,
            item_custom_fields: None,
            json: None,
            keep_prev_version: None,
            key: None,
            max_versions: None,
            name,
            new_name: None,
            password_length: None,
            rm_tag: None,
            rotate_after_disconnect: None,
            rotation_event_in: None,
            rotation_hour: None,
            rotation_interval: None,
            secure_access_allow_external_user: None,
            secure_access_bastion_issuer: None,
            secure_access_certificate_issuer: None,
            secure_access_enable: None,
            secure_access_host: None,
            secure_access_rdp_domain: None,
            secure_access_rdp_user: None,
            secure_access_ssh_user: None,
            secure_access_url: None,
            secure_access_web: None,
            secure_access_web_browsing: None,
            secure_access_web_proxy: None,
            timeout_sec: None,
            token: None,
            uid_token: None,
            use_capital_letters: None,
            use_lower_letters: None,
            use_numbers: None,
            use_special_characters: None,
        }
    }
}

