/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecureRemoteAccess {
    #[serde(rename = "account_id", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    #[serde(rename = "allow_port_forwarding", skip_serializing_if = "Option::is_none")]
    pub allow_port_forwarding: Option<bool>,
    #[serde(rename = "allow_providing_external_username", skip_serializing_if = "Option::is_none")]
    pub allow_providing_external_username: Option<bool>,
    #[serde(rename = "bastion_api", skip_serializing_if = "Option::is_none")]
    pub bastion_api: Option<String>,
    #[serde(rename = "bastion_issuer", skip_serializing_if = "Option::is_none")]
    pub bastion_issuer: Option<String>,
    #[serde(rename = "bastion_issuer_id", skip_serializing_if = "Option::is_none")]
    pub bastion_issuer_id: Option<i64>,
    #[serde(rename = "bastion_ssh", skip_serializing_if = "Option::is_none")]
    pub bastion_ssh: Option<String>,
    #[serde(rename = "block_concurrent_connections", skip_serializing_if = "Option::is_none")]
    pub block_concurrent_connections: Option<bool>,
    #[serde(rename = "block_concurrent_connections_level", skip_serializing_if = "Option::is_none")]
    pub block_concurrent_connections_level: Option<String>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    #[serde(rename = "connection_delay_seconds", skip_serializing_if = "Option::is_none")]
    pub connection_delay_seconds: Option<i64>,
    #[serde(rename = "dashboard_url", skip_serializing_if = "Option::is_none")]
    pub dashboard_url: Option<String>,
    #[serde(rename = "db_name", skip_serializing_if = "Option::is_none")]
    pub db_name: Option<String>,
    #[serde(rename = "domain", skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    #[serde(rename = "enable", skip_serializing_if = "Option::is_none")]
    pub enable: Option<bool>,
    #[serde(rename = "endpoint", skip_serializing_if = "Option::is_none")]
    pub endpoint: Option<String>,
    #[serde(rename = "enforce_hosts_restriction", skip_serializing_if = "Option::is_none")]
    pub enforce_hosts_restriction: Option<bool>,
    #[serde(rename = "gw_cluster_id", skip_serializing_if = "Option::is_none")]
    pub gw_cluster_id: Option<i64>,
    #[serde(rename = "host", skip_serializing_if = "Option::is_none")]
    pub host: Option<Vec<String>>,
    #[serde(rename = "host_provider_type", skip_serializing_if = "Option::is_none")]
    pub host_provider_type: Option<String>,
    #[serde(rename = "is_cli", skip_serializing_if = "Option::is_none")]
    pub is_cli: Option<bool>,
    #[serde(rename = "is_desktop_app", skip_serializing_if = "Option::is_none")]
    pub is_desktop_app: Option<bool>,
    #[serde(rename = "is_web", skip_serializing_if = "Option::is_none")]
    pub is_web: Option<bool>,
    #[serde(rename = "isolated", skip_serializing_if = "Option::is_none")]
    pub isolated: Option<bool>,
    #[serde(rename = "native", skip_serializing_if = "Option::is_none")]
    pub native: Option<bool>,
    #[serde(rename = "rd_gateway_server", skip_serializing_if = "Option::is_none")]
    pub rd_gateway_server: Option<String>,
    #[serde(rename = "rdp_user", skip_serializing_if = "Option::is_none")]
    pub rdp_user: Option<String>,
    #[serde(rename = "region", skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    #[serde(rename = "rotate_after_disconnect", skip_serializing_if = "Option::is_none")]
    pub rotate_after_disconnect: Option<bool>,
    #[serde(rename = "schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    #[serde(rename = "ssh_password", skip_serializing_if = "Option::is_none")]
    pub ssh_password: Option<bool>,
    #[serde(rename = "ssh_private_key", skip_serializing_if = "Option::is_none")]
    pub ssh_private_key: Option<bool>,
    #[serde(rename = "ssh_user", skip_serializing_if = "Option::is_none")]
    pub ssh_user: Option<String>,
    #[serde(rename = "status_info", skip_serializing_if = "Option::is_none")]
    pub status_info: Option<Box<models::ItemSraStatus>>,
    #[serde(rename = "target_hosts", skip_serializing_if = "Option::is_none")]
    pub target_hosts: Option<Vec<models::TargetNameWithHosts>>,
    #[serde(rename = "targets", skip_serializing_if = "Option::is_none")]
    pub targets: Option<Vec<String>>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "use_internal_bastion", skip_serializing_if = "Option::is_none")]
    pub use_internal_bastion: Option<bool>,
    #[serde(rename = "web_proxy", skip_serializing_if = "Option::is_none")]
    pub web_proxy: Option<bool>,
}

impl SecureRemoteAccess {
    pub fn new() -> SecureRemoteAccess {
        SecureRemoteAccess {
            account_id: None,
            allow_port_forwarding: None,
            allow_providing_external_username: None,
            bastion_api: None,
            bastion_issuer: None,
            bastion_issuer_id: None,
            bastion_ssh: None,
            block_concurrent_connections: None,
            block_concurrent_connections_level: None,
            category: None,
            connection_delay_seconds: None,
            dashboard_url: None,
            db_name: None,
            domain: None,
            enable: None,
            endpoint: None,
            enforce_hosts_restriction: None,
            gw_cluster_id: None,
            host: None,
            host_provider_type: None,
            is_cli: None,
            is_desktop_app: None,
            is_web: None,
            isolated: None,
            native: None,
            rd_gateway_server: None,
            rdp_user: None,
            region: None,
            rotate_after_disconnect: None,
            schema: None,
            ssh_password: None,
            ssh_private_key: None,
            ssh_user: None,
            status_info: None,
            target_hosts: None,
            targets: None,
            url: None,
            use_internal_bastion: None,
            web_proxy: None,
        }
    }
}

