/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerInventoryPayload {
    #[serde(rename = "auto_rotate", skip_serializing_if = "Option::is_none")]
    pub auto_rotate: Option<bool>,
    #[serde(rename = "auto_rotate_interval_in_days", skip_serializing_if = "Option::is_none")]
    pub auto_rotate_interval_in_days: Option<i32>,
    #[serde(rename = "auto_rotate_rotation_hour", skip_serializing_if = "Option::is_none")]
    pub auto_rotate_rotation_hour: Option<i32>,
    #[serde(rename = "enable_rdp_sra", skip_serializing_if = "Option::is_none")]
    pub enable_rdp_sra: Option<bool>,
    #[serde(rename = "migration_target_id", skip_serializing_if = "Option::is_none")]
    pub migration_target_id: Option<i64>,
    #[serde(rename = "server_targets_path_template", skip_serializing_if = "Option::is_none")]
    pub server_targets_path_template: Option<String>,
    #[serde(rename = "user_groups", skip_serializing_if = "Option::is_none")]
    pub user_groups: Option<Vec<String>>,
    #[serde(rename = "users_ignore_list", skip_serializing_if = "Option::is_none")]
    pub users_ignore_list: Option<std::collections::HashMap<String, bool>>,
    #[serde(rename = "users_rotated_secrets_path_template", skip_serializing_if = "Option::is_none")]
    pub users_rotated_secrets_path_template: Option<String>,
}

impl ServerInventoryPayload {
    pub fn new() -> ServerInventoryPayload {
        ServerInventoryPayload {
            auto_rotate: None,
            auto_rotate_interval_in_days: None,
            auto_rotate_rotation_hour: None,
            enable_rdp_sra: None,
            migration_target_id: None,
            server_targets_path_template: None,
            user_groups: None,
            users_ignore_list: None,
            users_rotated_secrets_path_template: None,
        }
    }
}

