/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetRoleRule {
    /// List of the approved/denied capabilities in the path options: [read, create, update, delete, list, deny]
    #[serde(rename = "capability")]
    pub capability: Vec<String>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// The path the rule refers to
    #[serde(rename = "path")]
    pub path: String,
    /// The role name to be updated
    #[serde(rename = "role-name")]
    pub role_name: String,
    /// item-rule, target-rule, role-rule, auth-method-rule, search-rule, reports-rule, gw-reports-rule or sra-reports-rule, sra-rule
    #[serde(rename = "rule-type", skip_serializing_if = "Option::is_none")]
    pub rule_type: Option<String>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// RoleRule ttl
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i32>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl SetRoleRule {
    pub fn new(capability: Vec<String>, path: String, role_name: String) -> SetRoleRule {
        SetRoleRule {
            capability,
            json: None,
            path,
            role_name,
            rule_type: None,
            token: None,
            ttl: None,
            uid_token: None,
        }
    }
}

