/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SharingItemFullInfo {
    #[serde(rename = "assigners", skip_serializing_if = "Option::is_none")]
    pub assigners: Option<Vec<models::RuleAssigner>>,
    /// The approved/denied capabilities in the path
    #[serde(rename = "capabilities", skip_serializing_if = "Option::is_none")]
    pub capabilities: Option<Vec<String>>,
    #[serde(rename = "cb", skip_serializing_if = "Option::is_none")]
    pub cb: Option<i32>,
    /// flag that indicate that this rule is allowed to be access RemainingAccess of times.
    #[serde(rename = "is_limit_access", skip_serializing_if = "Option::is_none")]
    pub is_limit_access: Option<bool>,
    /// The item id this rule directly refers to (when applicable)
    #[serde(rename = "item_id", skip_serializing_if = "Option::is_none")]
    pub item_id: Option<i64>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "number_of_access_used", skip_serializing_if = "Option::is_none")]
    pub number_of_access_used: Option<i64>,
    #[serde(rename = "number_of_allowed_access", skip_serializing_if = "Option::is_none")]
    pub number_of_allowed_access: Option<i64>,
    /// The path the rule refers to
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "start_time", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<i64>,
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i64>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl SharingItemFullInfo {
    pub fn new() -> SharingItemFullInfo {
        SharingItemFullInfo {
            assigners: None,
            capabilities: None,
            cb: None,
            is_limit_access: None,
            item_id: None,
            name: None,
            number_of_access_used: None,
            number_of_allowed_access: None,
            path: None,
            start_time: None,
            ttl: None,
            r#type: None,
        }
    }
}

