/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignDataWithClassicKey {
    /// Data
    #[serde(rename = "data")]
    pub data: String,
    /// The name of the key to use in the sign data process
    #[serde(rename = "display-id")]
    pub display_id: String,
    /// Defines whether the data should be hashed as part of the signing. If true, the data will not be hashed
    #[serde(rename = "hashed", skip_serializing_if = "Option::is_none")]
    pub hashed: Option<bool>,
    /// HashingMethod
    #[serde(rename = "hashing-method", skip_serializing_if = "Option::is_none")]
    pub hashing_method: Option<String>,
    /// Retrieve the Secret value without checking the Gateway's cache [true/false]. This flag is only relevant when using the RestAPI
    #[serde(rename = "ignore-cache", skip_serializing_if = "Option::is_none")]
    pub ignore_cache: Option<String>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// ClassicKey name
    #[serde(rename = "name")]
    pub name: String,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
    /// classic key version
    #[serde(rename = "version")]
    pub version: i32,
}

impl SignDataWithClassicKey {
    pub fn new(data: String, display_id: String, name: String, version: i32) -> SignDataWithClassicKey {
        SignDataWithClassicKey {
            data,
            display_id,
            hashed: None,
            hashing_method: None,
            ignore_cache: None,
            json: None,
            name,
            token: None,
            uid_token: None,
            version,
        }
    }
}

