/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignJwtWithClassicKey {
    /// The name of the key to use in the sign JWT process
    #[serde(rename = "display-id")]
    pub display_id: String,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// JWTClaims
    #[serde(rename = "jwt-claims")]
    pub jwt_claims: String,
    /// SigningMethod
    #[serde(rename = "signing-method")]
    pub signing_method: String,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
    /// classic key version
    #[serde(rename = "version")]
    pub version: i32,
}

impl SignJwtWithClassicKey {
    pub fn new(display_id: String, jwt_claims: String, signing_method: String, version: i32) -> SignJwtWithClassicKey {
        SignJwtWithClassicKey {
            display_id,
            json: None,
            jwt_claims,
            signing_method,
            token: None,
            uid_token: None,
            version,
        }
    }
}

