/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SplunkPayload {
    #[serde(rename = "audience", skip_serializing_if = "Option::is_none")]
    pub audience: Option<String>,
    #[serde(rename = "expiration_date", skip_serializing_if = "Option::is_none")]
    pub expiration_date: Option<String>,
    #[serde(rename = "hec_token_name", skip_serializing_if = "Option::is_none")]
    pub hec_token_name: Option<String>,
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    #[serde(rename = "token_id", skip_serializing_if = "Option::is_none")]
    pub token_id: Option<String>,
    #[serde(rename = "token_owner", skip_serializing_if = "Option::is_none")]
    pub token_owner: Option<String>,
    #[serde(rename = "validity_period_days", skip_serializing_if = "Option::is_none")]
    pub validity_period_days: Option<i64>,
}

impl SplunkPayload {
    pub fn new() -> SplunkPayload {
        SplunkPayload {
            audience: None,
            expiration_date: None,
            hec_token_name: None,
            token: None,
            token_id: None,
            token_owner: None,
            validity_period_days: None,
        }
    }
}

