/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SplunkLogForwardingConfig {
    #[serde(rename = "splunk_enable_batch", skip_serializing_if = "Option::is_none")]
    pub splunk_enable_batch: Option<String>,
    #[serde(rename = "splunk_enable_tls", skip_serializing_if = "Option::is_none")]
    pub splunk_enable_tls: Option<bool>,
    #[serde(rename = "splunk_index", skip_serializing_if = "Option::is_none")]
    pub splunk_index: Option<String>,
    #[serde(rename = "splunk_source", skip_serializing_if = "Option::is_none")]
    pub splunk_source: Option<String>,
    #[serde(rename = "splunk_sourcetype", skip_serializing_if = "Option::is_none")]
    pub splunk_sourcetype: Option<String>,
    #[serde(rename = "splunk_tls_certificate", skip_serializing_if = "Option::is_none")]
    pub splunk_tls_certificate: Option<String>,
    #[serde(rename = "splunk_token", skip_serializing_if = "Option::is_none")]
    pub splunk_token: Option<String>,
    #[serde(rename = "splunk_url", skip_serializing_if = "Option::is_none")]
    pub splunk_url: Option<String>,
}

impl SplunkLogForwardingConfig {
    pub fn new() -> SplunkLogForwardingConfig {
        SplunkLogForwardingConfig {
            splunk_enable_batch: None,
            splunk_enable_tls: None,
            splunk_index: None,
            splunk_source: None,
            splunk_sourcetype: None,
            splunk_tls_certificate: None,
            splunk_token: None,
            splunk_url: None,
        }
    }
}

