/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SshBastionConf {
    #[serde(rename = "hide_session_recording", skip_serializing_if = "Option::is_none")]
    pub hide_session_recording: Option<bool>,
    #[serde(rename = "kexalgs", skip_serializing_if = "Option::is_none")]
    pub kexalgs: Option<String>,
    #[serde(rename = "log_forwarding", skip_serializing_if = "Option::is_none")]
    pub log_forwarding: Option<Box<models::LogForwardingConfigPart>>,
    #[serde(rename = "session_termination", skip_serializing_if = "Option::is_none")]
    pub session_termination: Option<Box<models::SshBastionSessionTermination>>,
}

impl SshBastionConf {
    pub fn new() -> SshBastionConf {
        SshBastionConf {
            hide_session_recording: None,
            kexalgs: None,
            log_forwarding: None,
            session_termination: None,
        }
    }
}

