/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StaticSecretDeleteSyncOutput {
    #[serde(rename = "secret-name", skip_serializing_if = "Option::is_none")]
    pub secret_name: Option<String>,
    #[serde(rename = "usc-name", skip_serializing_if = "Option::is_none")]
    pub usc_name: Option<String>,
}

impl StaticSecretDeleteSyncOutput {
    pub fn new() -> StaticSecretDeleteSyncOutput {
        StaticSecretDeleteSyncOutput {
            secret_name: None,
            usc_name: None,
        }
    }
}

