/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyslogLogForwardingConfig {
    #[serde(rename = "syslog_enable_tls", skip_serializing_if = "Option::is_none")]
    pub syslog_enable_tls: Option<bool>,
    #[serde(rename = "syslog_formatter", skip_serializing_if = "Option::is_none")]
    pub syslog_formatter: Option<String>,
    #[serde(rename = "syslog_host", skip_serializing_if = "Option::is_none")]
    pub syslog_host: Option<String>,
    #[serde(rename = "syslog_network", skip_serializing_if = "Option::is_none")]
    pub syslog_network: Option<String>,
    #[serde(rename = "syslog_target_tag", skip_serializing_if = "Option::is_none")]
    pub syslog_target_tag: Option<String>,
    #[serde(rename = "syslog_tls_certificate", skip_serializing_if = "Option::is_none")]
    pub syslog_tls_certificate: Option<String>,
}

impl SyslogLogForwardingConfig {
    pub fn new() -> SyslogLogForwardingConfig {
        SyslogLogForwardingConfig {
            syslog_enable_tls: None,
            syslog_formatter: None,
            syslog_host: None,
            syslog_network: None,
            syslog_target_tag: None,
            syslog_tls_certificate: None,
        }
    }
}

