/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SystemAccessCredsSettings : SystemAccessCredsSettings describes system access credential settings for account by minutes
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemAccessCredsSettings {
    #[serde(rename = "jwt_ttl_default", skip_serializing_if = "Option::is_none")]
    pub jwt_ttl_default: Option<i64>,
    #[serde(rename = "jwt_ttl_maximum", skip_serializing_if = "Option::is_none")]
    pub jwt_ttl_maximum: Option<i64>,
    #[serde(rename = "jwt_ttl_minimum", skip_serializing_if = "Option::is_none")]
    pub jwt_ttl_minimum: Option<i64>,
}

impl SystemAccessCredsSettings {
    /// SystemAccessCredsSettings describes system access credential settings for account by minutes
    pub fn new() -> SystemAccessCredsSettings {
        SystemAccessCredsSettings {
            jwt_ttl_default: None,
            jwt_ttl_maximum: None,
            jwt_ttl_minimum: None,
        }
    }
}

