/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TargetCreateSalesforce : targetCreateSalesforce is a command that creates a new Salesforce target
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TargetCreateSalesforce {
    /// Base64 encoded PEM of the connected app private key (relevant for JWT auth only)
    #[serde(rename = "app-private-key-data", skip_serializing_if = "Option::is_none")]
    pub app_private_key_data: Option<String>,
    /// type of the auth flow ('jwt' / 'user-password')
    #[serde(rename = "auth-flow")]
    pub auth_flow: String,
    /// Base64 encoded PEM cert to use when uploading a new key to Salesforce
    #[serde(rename = "ca-cert-data", skip_serializing_if = "Option::is_none")]
    pub ca_cert_data: Option<String>,
    /// name of the certificate in Salesforce tenant to use when uploading new key
    #[serde(rename = "ca-cert-name", skip_serializing_if = "Option::is_none")]
    pub ca_cert_name: Option<String>,
    /// Client ID of the oauth2 app to use for connecting to Salesforce
    #[serde(rename = "client-id")]
    pub client_id: String,
    /// Client secret of the oauth2 app to use for connecting to Salesforce (required for password flow)
    #[serde(rename = "client-secret", skip_serializing_if = "Option::is_none")]
    pub client_secret: Option<String>,
    /// Description of the object
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The email of the user attached to the oauth2 app used for connecting to Salesforce
    #[serde(rename = "email")]
    pub email: String,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Set the maximum number of versions, limited by the account settings defaults.
    #[serde(rename = "max-versions", skip_serializing_if = "Option::is_none")]
    pub max_versions: Option<String>,
    /// Target name
    #[serde(rename = "name")]
    pub name: String,
    /// The password of the user attached to the oauth2 app used for connecting to Salesforce (required for user-password flow)
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    /// The security token of the user attached to the oauth2 app used for connecting to Salesforce  (required for user-password flow)
    #[serde(rename = "security-token", skip_serializing_if = "Option::is_none")]
    pub security_token: Option<String>,
    /// Url of the Salesforce tenant
    #[serde(rename = "tenant-url")]
    pub tenant_url: String,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl TargetCreateSalesforce {
    /// targetCreateSalesforce is a command that creates a new Salesforce target
    pub fn new(auth_flow: String, client_id: String, email: String, name: String, tenant_url: String) -> TargetCreateSalesforce {
        TargetCreateSalesforce {
            app_private_key_data: None,
            auth_flow,
            ca_cert_data: None,
            ca_cert_name: None,
            client_id,
            client_secret: None,
            description: None,
            email,
            json: None,
            key: None,
            max_versions: None,
            name,
            password: None,
            security_token: None,
            tenant_url,
            token: None,
            uid_token: None,
        }
    }
}

