/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TargetUpdateGemini : targetUpdateGemini is a command that updates an existing gemini target
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TargetUpdateGemini {
    /// API key for Gemini
    #[serde(rename = "api-key", skip_serializing_if = "Option::is_none")]
    pub api_key: Option<String>,
    /// Description of the object
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Base URL of the Gemini API
    #[serde(rename = "gemini-url", skip_serializing_if = "Option::is_none")]
    pub gemini_url: Option<String>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Whether to keep previous version [true/false]. If not set, use default according to account settings
    #[serde(rename = "keep-prev-version", skip_serializing_if = "Option::is_none")]
    pub keep_prev_version: Option<String>,
    /// The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Set the maximum number of versions, limited by the account settings defaults.
    #[serde(rename = "max-versions", skip_serializing_if = "Option::is_none")]
    pub max_versions: Option<String>,
    /// Target name
    #[serde(rename = "name")]
    pub name: String,
    /// Deprecated - use description
    #[serde(rename = "new-comment", skip_serializing_if = "Option::is_none")]
    pub new_comment: Option<String>,
    /// New target name
    #[serde(rename = "new-name", skip_serializing_if = "Option::is_none")]
    pub new_name: Option<String>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl TargetUpdateGemini {
    /// targetUpdateGemini is a command that updates an existing gemini target
    pub fn new(name: String) -> TargetUpdateGemini {
        TargetUpdateGemini {
            api_key: None,
            description: None,
            gemini_url: None,
            json: None,
            keep_prev_version: None,
            key: None,
            max_versions: None,
            name,
            new_comment: None,
            new_name: None,
            token: None,
            uid_token: None,
        }
    }
}

