/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TargetTypeDetailsInput {
    #[serde(rename = "artifactory_target_details", skip_serializing_if = "Option::is_none")]
    pub artifactory_target_details: Option<Box<models::ArtifactoryTargetDetails>>,
    #[serde(rename = "aws_target_details", skip_serializing_if = "Option::is_none")]
    pub aws_target_details: Option<Box<models::AwsTargetDetails>>,
    #[serde(rename = "azure_target_details", skip_serializing_if = "Option::is_none")]
    pub azure_target_details: Option<Box<models::AzureTargetDetails>>,
    #[serde(rename = "chef_target_details", skip_serializing_if = "Option::is_none")]
    pub chef_target_details: Option<Box<models::ChefTargetDetails>>,
    #[serde(rename = "custom_target_details", skip_serializing_if = "Option::is_none")]
    pub custom_target_details: Option<Box<models::CustomTargetDetails>>,
    #[serde(rename = "db_target_details", skip_serializing_if = "Option::is_none")]
    pub db_target_details: Option<Box<models::DbTargetDetails>>,
    #[serde(rename = "dockerhub_target_details", skip_serializing_if = "Option::is_none")]
    pub dockerhub_target_details: Option<Box<models::DockerhubTargetDetails>>,
    #[serde(rename = "eks_target_details", skip_serializing_if = "Option::is_none")]
    pub eks_target_details: Option<Box<models::EksTargetDetails>>,
    #[serde(rename = "gcp_target_details", skip_serializing_if = "Option::is_none")]
    pub gcp_target_details: Option<Box<models::GcpTargetDetails>>,
    #[serde(rename = "gemini_target_details", skip_serializing_if = "Option::is_none")]
    pub gemini_target_details: Option<Box<models::GeminiTargetDetails>>,
    #[serde(rename = "github_target_details", skip_serializing_if = "Option::is_none")]
    pub github_target_details: Option<Box<models::GithubTargetDetails>>,
    #[serde(rename = "gitlab_target_details", skip_serializing_if = "Option::is_none")]
    pub gitlab_target_details: Option<Box<models::GitlabTargetDetails>>,
    #[serde(rename = "gke_target_details", skip_serializing_if = "Option::is_none")]
    pub gke_target_details: Option<Box<models::GkeTargetDetails>>,
    #[serde(rename = "globalsign_atlas_target_details", skip_serializing_if = "Option::is_none")]
    pub globalsign_atlas_target_details: Option<Box<models::GlobalSignAtlasTargetDetails>>,
    #[serde(rename = "globalsign_target_details", skip_serializing_if = "Option::is_none")]
    pub globalsign_target_details: Option<Box<models::GlobalSignGccTargetDetails>>,
    #[serde(rename = "godaddy_target_details", skip_serializing_if = "Option::is_none")]
    pub godaddy_target_details: Option<Box<models::GodaddyTargetDetails>>,
    #[serde(rename = "hashi_vault_target_details", skip_serializing_if = "Option::is_none")]
    pub hashi_vault_target_details: Option<Box<models::HashiVaultTargetDetails>>,
    #[serde(rename = "ldap_target_details", skip_serializing_if = "Option::is_none")]
    pub ldap_target_details: Option<Box<models::LdapTargetDetails>>,
    #[serde(rename = "letsencrypt_target_details", skip_serializing_if = "Option::is_none")]
    pub letsencrypt_target_details: Option<Box<models::LetsEncryptTargetDetails>>,
    #[serde(rename = "linked_target_details", skip_serializing_if = "Option::is_none")]
    pub linked_target_details: Option<Box<models::LinkedTargetDetails>>,
    #[serde(rename = "mongo_db_target_details", skip_serializing_if = "Option::is_none")]
    pub mongo_db_target_details: Option<Box<models::MongoDbTargetDetails>>,
    #[serde(rename = "native_k8s_target_details", skip_serializing_if = "Option::is_none")]
    pub native_k8s_target_details: Option<Box<models::NativeK8sTargetDetails>>,
    #[serde(rename = "openai_target_details", skip_serializing_if = "Option::is_none")]
    pub openai_target_details: Option<Box<models::OpenAiTargetDetails>>,
    #[serde(rename = "ping_target_details", skip_serializing_if = "Option::is_none")]
    pub ping_target_details: Option<Box<models::PingTargetDetails>>,
    #[serde(rename = "rabbit_mq_target_details", skip_serializing_if = "Option::is_none")]
    pub rabbit_mq_target_details: Option<Box<models::RabbitMqTargetDetails>>,
    #[serde(rename = "salesforce_target_details", skip_serializing_if = "Option::is_none")]
    pub salesforce_target_details: Option<Box<models::SalesforceTargetDetails>>,
    #[serde(rename = "sectigo_target_details", skip_serializing_if = "Option::is_none")]
    pub sectigo_target_details: Option<Box<models::SectigoTargetDetails>>,
    #[serde(rename = "splunk_target_details", skip_serializing_if = "Option::is_none")]
    pub splunk_target_details: Option<Box<models::SplunkTargetDetails>>,
    #[serde(rename = "ssh_target_details", skip_serializing_if = "Option::is_none")]
    pub ssh_target_details: Option<Box<models::SshTargetDetails>>,
    #[serde(rename = "venafi_target_details", skip_serializing_if = "Option::is_none")]
    pub venafi_target_details: Option<Box<models::VenafiTargetDetails>>,
    #[serde(rename = "web_target_details", skip_serializing_if = "Option::is_none")]
    pub web_target_details: Option<Box<models::WebTargetDetails>>,
    #[serde(rename = "windows_target_details", skip_serializing_if = "Option::is_none")]
    pub windows_target_details: Option<Box<models::WindowsTargetDetails>>,
    #[serde(rename = "zerossl_target_details", skip_serializing_if = "Option::is_none")]
    pub zerossl_target_details: Option<Box<models::ZeroSslTargetDetails>>,
}

impl TargetTypeDetailsInput {
    pub fn new() -> TargetTypeDetailsInput {
        TargetTypeDetailsInput {
            artifactory_target_details: None,
            aws_target_details: None,
            azure_target_details: None,
            chef_target_details: None,
            custom_target_details: None,
            db_target_details: None,
            dockerhub_target_details: None,
            eks_target_details: None,
            gcp_target_details: None,
            gemini_target_details: None,
            github_target_details: None,
            gitlab_target_details: None,
            gke_target_details: None,
            globalsign_atlas_target_details: None,
            globalsign_target_details: None,
            godaddy_target_details: None,
            hashi_vault_target_details: None,
            ldap_target_details: None,
            letsencrypt_target_details: None,
            linked_target_details: None,
            mongo_db_target_details: None,
            native_k8s_target_details: None,
            openai_target_details: None,
            ping_target_details: None,
            rabbit_mq_target_details: None,
            salesforce_target_details: None,
            sectigo_target_details: None,
            splunk_target_details: None,
            ssh_target_details: None,
            venafi_target_details: None,
            web_target_details: None,
            windows_target_details: None,
            zerossl_target_details: None,
        }
    }
}

