/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TargetCreateSectigo : targetCreateSectigo is a command that creates a new Sectigo target
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TargetCreateSectigo {
    /// Certificate Profile ID in Sectigo account
    #[serde(rename = "certificate-profile-id")]
    pub certificate_profile_id: i64,
    /// Customer Uri of the Sectigo account
    #[serde(rename = "customer-uri")]
    pub customer_uri: String,
    /// Description of the object
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// External Requester - a comma separated list of emails
    #[serde(rename = "external-requester")]
    pub external_requester: String,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Set the maximum number of versions, limited by the account settings defaults.
    #[serde(rename = "max-versions", skip_serializing_if = "Option::is_none")]
    pub max_versions: Option<String>,
    /// Target name
    #[serde(rename = "name")]
    pub name: String,
    /// Organization ID in Sectigo account
    #[serde(rename = "organization-id")]
    pub organization_id: i64,
    /// Password of the Sectigo account user
    #[serde(rename = "password")]
    pub password: String,
    /// Timeout waiting for certificate validation in Duration format (1h - 1 Hour, 20m - 20 Minutes, 33m3s - 33 Minutes and 3 Seconds), maximum 1h.
    #[serde(rename = "timeout", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<String>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
    /// Username of the Sectigo account
    #[serde(rename = "username")]
    pub username: String,
}

impl TargetCreateSectigo {
    /// targetCreateSectigo is a command that creates a new Sectigo target
    pub fn new(certificate_profile_id: i64, customer_uri: String, external_requester: String, name: String, organization_id: i64, password: String, username: String) -> TargetCreateSectigo {
        TargetCreateSectigo {
            certificate_profile_id,
            customer_uri,
            description: None,
            external_requester,
            json: None,
            key: None,
            max_versions: None,
            name,
            organization_id,
            password,
            timeout: None,
            token: None,
            uid_token: None,
            username,
        }
    }
}

