/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TargetCreateSplunk : targetCreateSplunk is a command that creates a new splunk target
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TargetCreateSplunk {
    /// Splunk token audience (required when using token authentication for rotation)
    #[serde(rename = "audience", skip_serializing_if = "Option::is_none")]
    pub audience: Option<String>,
    /// Description of the object
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Set the maximum number of versions, limited by the account settings defaults.
    #[serde(rename = "max-versions", skip_serializing_if = "Option::is_none")]
    pub max_versions: Option<String>,
    /// Target name
    #[serde(rename = "name")]
    pub name: String,
    /// Splunk Password (used when authenticating with username/password)
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    /// Splunk Token (used when authenticating with token)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// Splunk Token Owner (required when using token authentication for rotation)
    #[serde(rename = "token-owner", skip_serializing_if = "Option::is_none")]
    pub token_owner: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
    /// Splunk server URL
    #[serde(rename = "url")]
    pub url: String,
    /// Use TLS certificate verification when connecting to the Splunk management API
    #[serde(rename = "use-tls", skip_serializing_if = "Option::is_none")]
    pub use_tls: Option<bool>,
    /// Splunk Username (used when authenticating with username/password)
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
}

impl TargetCreateSplunk {
    /// targetCreateSplunk is a command that creates a new splunk target
    pub fn new(name: String, url: String) -> TargetCreateSplunk {
        TargetCreateSplunk {
            audience: None,
            description: None,
            json: None,
            key: None,
            max_versions: None,
            name,
            password: None,
            token: None,
            token_owner: None,
            uid_token: None,
            url,
            use_tls: None,
            username: None,
        }
    }
}

