/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TargetNameWithHosts {
    #[serde(rename = "hosts", skip_serializing_if = "Option::is_none")]
    pub hosts: Option<Vec<String>>,
    #[serde(rename = "target_name", skip_serializing_if = "Option::is_none")]
    pub target_name: Option<String>,
}

impl TargetNameWithHosts {
    pub fn new() -> TargetNameWithHosts {
        TargetNameWithHosts {
            hosts: None,
            target_name: None,
        }
    }
}

