/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TargetError : TargetError represents a failed target scan
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TargetError {
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(rename = "host", skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<i64>,
}

impl TargetError {
    /// TargetError represents a failed target scan
    pub fn new() -> TargetError {
        TargetError {
            error: None,
            host: None,
            port: None,
        }
    }
}

