/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TargetUpdateLetsEncrypt : targetUpdateLetsEncrypt is a command that updates an existing Let's Encrypt target
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TargetUpdateLetsEncrypt {
    #[serde(rename = "acme-challenge", skip_serializing_if = "Option::is_none")]
    pub acme_challenge: Option<String>,
    /// Description of the object
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Name of existing cloud target for DNS credentials. Required when acme-challenge=dns. Supported: AWS, Azure, GCP targets
    #[serde(rename = "dns-target-creds", skip_serializing_if = "Option::is_none")]
    pub dns_target_creds: Option<String>,
    /// Email address for ACME account registration
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// GCP Cloud DNS: Project ID. Optional - can be derived from service account
    #[serde(rename = "gcp-project", skip_serializing_if = "Option::is_none")]
    pub gcp_project: Option<String>,
    /// AWS Route53 hosted zone ID. Required when dns-target-creds points to AWS target
    #[serde(rename = "hosted-zone", skip_serializing_if = "Option::is_none")]
    pub hosted_zone: Option<String>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Whether to keep previous version [true/false]. If not set, use default according to account settings
    #[serde(rename = "keep-prev-version", skip_serializing_if = "Option::is_none")]
    pub keep_prev_version: Option<String>,
    /// The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "lets-encrypt-url", skip_serializing_if = "Option::is_none")]
    pub lets_encrypt_url: Option<String>,
    /// Set the maximum number of versions, limited by the account settings defaults.
    #[serde(rename = "max-versions", skip_serializing_if = "Option::is_none")]
    pub max_versions: Option<String>,
    /// Target name
    #[serde(rename = "name")]
    pub name: String,
    /// New target name
    #[serde(rename = "new-name", skip_serializing_if = "Option::is_none")]
    pub new_name: Option<String>,
    /// Azure resource group name. Required when dns-target-creds points to Azure target
    #[serde(rename = "resource-group", skip_serializing_if = "Option::is_none")]
    pub resource_group: Option<String>,
    #[serde(rename = "timeout", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<String>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl TargetUpdateLetsEncrypt {
    /// targetUpdateLetsEncrypt is a command that updates an existing Let's Encrypt target
    pub fn new(name: String) -> TargetUpdateLetsEncrypt {
        TargetUpdateLetsEncrypt {
            acme_challenge: None,
            description: None,
            dns_target_creds: None,
            email: None,
            gcp_project: None,
            hosted_zone: None,
            json: None,
            keep_prev_version: None,
            key: None,
            lets_encrypt_url: None,
            max_versions: None,
            name,
            new_name: None,
            resource_group: None,
            timeout: None,
            token: None,
            uid_token: None,
        }
    }
}

