/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TargetCreateGke {
    /// Description of the object
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// GKE Service Account key file path
    #[serde(rename = "gke-account-key", skip_serializing_if = "Option::is_none")]
    pub gke_account_key: Option<String>,
    /// GKE cluster CA certificate
    #[serde(rename = "gke-cluster-cert", skip_serializing_if = "Option::is_none")]
    pub gke_cluster_cert: Option<String>,
    /// GKE cluster URL endpoint
    #[serde(rename = "gke-cluster-endpoint", skip_serializing_if = "Option::is_none")]
    pub gke_cluster_endpoint: Option<String>,
    /// GKE cluster name
    #[serde(rename = "gke-cluster-name", skip_serializing_if = "Option::is_none")]
    pub gke_cluster_name: Option<String>,
    /// GKE service account email
    #[serde(rename = "gke-service-account-email", skip_serializing_if = "Option::is_none")]
    pub gke_service_account_email: Option<String>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Set the maximum number of versions, limited by the account settings defaults.
    #[serde(rename = "max-versions", skip_serializing_if = "Option::is_none")]
    pub max_versions: Option<String>,
    /// Target name
    #[serde(rename = "name")]
    pub name: String,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
    #[serde(rename = "use-gw-cloud-identity", skip_serializing_if = "Option::is_none")]
    pub use_gw_cloud_identity: Option<bool>,
}

impl TargetCreateGke {
    pub fn new(name: String) -> TargetCreateGke {
        TargetCreateGke {
            description: None,
            gke_account_key: None,
            gke_cluster_cert: None,
            gke_cluster_endpoint: None,
            gke_cluster_name: None,
            gke_service_account_email: None,
            json: None,
            key: None,
            max_versions: None,
            name,
            token: None,
            uid_token: None,
            use_gw_cloud_identity: None,
        }
    }
}

