/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TargetList : targetList is a command that returns a list of targets
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TargetList {
    /// Filter by auth method name or part of it
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<String>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Next page reference
    #[serde(rename = "pagination-token", skip_serializing_if = "Option::is_none")]
    pub pagination_token: Option<String>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The target types list . In case it is empty, all types of targets will be returned. options: [hanadb cassandra aws ssh gke eks mysql mongodb snowflake mssql redshift artifactory azure rabbitmq k8s venafi gcp oracle dockerhub ldap github chef web salesforce postgres]
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Vec<String>>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl TargetList {
    /// targetList is a command that returns a list of targets
    pub fn new() -> TargetList {
        TargetList {
            filter: None,
            json: None,
            pagination_token: None,
            token: None,
            r#type: None,
            uid_token: None,
        }
    }
}

