/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TargetUpdateLdap : targetUpdateLdap is a command that updates an existing ldap target
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TargetUpdateLdap {
    /// Bind DN
    #[serde(rename = "bind-dn")]
    pub bind_dn: String,
    /// Bind DN Password
    #[serde(rename = "bind-dn-password")]
    pub bind_dn_password: String,
    /// Description of the object
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Whether to keep previous version [true/false]. If not set, use default according to account settings
    #[serde(rename = "keep-prev-version", skip_serializing_if = "Option::is_none")]
    pub keep_prev_version: Option<String>,
    /// The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// CA Certificate File Content
    #[serde(rename = "ldap-ca-cert", skip_serializing_if = "Option::is_none")]
    pub ldap_ca_cert: Option<String>,
    /// LDAP Server URL
    #[serde(rename = "ldap-url")]
    pub ldap_url: String,
    /// Set the maximum number of versions, limited by the account settings defaults.
    #[serde(rename = "max-versions", skip_serializing_if = "Option::is_none")]
    pub max_versions: Option<String>,
    /// Target name
    #[serde(rename = "name")]
    pub name: String,
    /// New target name
    #[serde(rename = "new-name", skip_serializing_if = "Option::is_none")]
    pub new_name: Option<String>,
    /// Set Ldap server type, Options:[OpenLDAP, ActiveDirectory]
    #[serde(rename = "server-type", skip_serializing_if = "Option::is_none")]
    pub server_type: Option<String>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// Token expiration
    #[serde(rename = "token-expiration", skip_serializing_if = "Option::is_none")]
    pub token_expiration: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl TargetUpdateLdap {
    /// targetUpdateLdap is a command that updates an existing ldap target
    pub fn new(bind_dn: String, bind_dn_password: String, ldap_url: String, name: String) -> TargetUpdateLdap {
        TargetUpdateLdap {
            bind_dn,
            bind_dn_password,
            description: None,
            json: None,
            keep_prev_version: None,
            key: None,
            ldap_ca_cert: None,
            ldap_url,
            max_versions: None,
            name,
            new_name: None,
            server_type: None,
            token: None,
            token_expiration: None,
            uid_token: None,
        }
    }
}

