/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TargetCreateGithub {
    /// Description of the object
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Github app id
    #[serde(rename = "github-app-id", skip_serializing_if = "Option::is_none")]
    pub github_app_id: Option<i64>,
    /// App private key
    #[serde(rename = "github-app-private-key", skip_serializing_if = "Option::is_none")]
    pub github_app_private_key: Option<String>,
    /// Base URL
    #[serde(rename = "github-base-url", skip_serializing_if = "Option::is_none")]
    pub github_base_url: Option<String>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Set the maximum number of versions, limited by the account settings defaults.
    #[serde(rename = "max-versions", skip_serializing_if = "Option::is_none")]
    pub max_versions: Option<String>,
    /// Target name
    #[serde(rename = "name")]
    pub name: String,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl TargetCreateGithub {
    pub fn new(name: String) -> TargetCreateGithub {
        TargetCreateGithub {
            description: None,
            github_app_id: None,
            github_app_private_key: None,
            github_base_url: None,
            json: None,
            key: None,
            max_versions: None,
            name,
            token: None,
            uid_token: None,
        }
    }
}

