/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UidListChildren : uidListChildren is a command that lists child token ids of Akeyless Universal Identity.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UidListChildren {
    /// The universal identity auth method name, required only when uid-token is not provided
    #[serde(rename = "auth-method-name", skip_serializing_if = "Option::is_none")]
    pub auth_method_name: Option<String>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl UidListChildren {
    /// uidListChildren is a command that lists child token ids of Akeyless Universal Identity.
    pub fn new() -> UidListChildren {
        UidListChildren {
            auth_method_name: None,
            json: None,
            token: None,
            uid_token: None,
        }
    }
}

