/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UidCreateChildToken : uidCreateChildToken is a command that creates a new child token using Akeyless Universal Identity.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UidCreateChildToken {
    /// The universal identity auth method name, required only when uid-token is not provided
    #[serde(rename = "auth-method-name", skip_serializing_if = "Option::is_none")]
    pub auth_method_name: Option<String>,
    /// Deny from new child to create their own children
    #[serde(rename = "child-deny-inheritance", skip_serializing_if = "Option::is_none")]
    pub child_deny_inheritance: Option<bool>,
    /// Deny from new child to rotate
    #[serde(rename = "child-deny-rotate", skip_serializing_if = "Option::is_none")]
    pub child_deny_rotate: Option<bool>,
    /// New child token ttl
    #[serde(rename = "child-ttl", skip_serializing_if = "Option::is_none")]
    pub child_ttl: Option<i32>,
    /// Deprecated - use description
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    /// Description of the object
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
    /// The ID of the uid-token, required only when uid-token is not provided
    #[serde(rename = "uid-token-id", skip_serializing_if = "Option::is_none")]
    pub uid_token_id: Option<String>,
}

impl UidCreateChildToken {
    /// uidCreateChildToken is a command that creates a new child token using Akeyless Universal Identity.
    pub fn new() -> UidCreateChildToken {
        UidCreateChildToken {
            auth_method_name: None,
            child_deny_inheritance: None,
            child_deny_rotate: None,
            child_ttl: None,
            comment: None,
            description: None,
            json: None,
            token: None,
            uid_token: None,
            uid_token_id: None,
        }
    }
}

