/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UidRotateToken : uidRotateToken is a command that rotates an Akeyless Universal Identity token.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UidRotateToken {
    /// Create a new child token with default parameters
    #[serde(rename = "fork", skip_serializing_if = "Option::is_none")]
    pub fork: Option<bool>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// The new rotated token to send manual ack for (with uid-token=the-orig-token)
    #[serde(rename = "send-manual-ack-token", skip_serializing_if = "Option::is_none")]
    pub send_manual_ack_token: Option<String>,
    /// The Universal identity token
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
    /// Disable automatic ack
    #[serde(rename = "with-manual-ack", skip_serializing_if = "Option::is_none")]
    pub with_manual_ack: Option<bool>,
}

impl UidRotateToken {
    /// uidRotateToken is a command that rotates an Akeyless Universal Identity token.
    pub fn new() -> UidRotateToken {
        UidRotateToken {
            fork: None,
            json: None,
            send_manual_ack_token: None,
            uid_token: None,
            with_manual_ack: None,
        }
    }
}

