/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UidRevokeToken {
    /// The universal identity auth method name
    #[serde(rename = "auth-method-name", skip_serializing_if = "Option::is_none")]
    pub auth_method_name: Option<String>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// the universal identity token/token-id to revoke
    #[serde(rename = "revoke-token")]
    pub revoke_token: String,
    /// revokeSelf/revokeAll (delete only this token/this token and his children)
    #[serde(rename = "revoke-type")]
    pub revoke_type: String,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl UidRevokeToken {
    pub fn new(revoke_token: String, revoke_type: String) -> UidRevokeToken {
        UidRevokeToken {
            auth_method_name: None,
            json: None,
            revoke_token,
            revoke_type,
            token: None,
            uid_token: None,
        }
    }
}

