/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UidGenerateToken : uidGenerateToken is a command that generates a new token using Akeyless Universal Identity.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UidGenerateToken {
    /// The universal identity auth method name
    #[serde(rename = "auth-method-name")]
    pub auth_method_name: String,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl UidGenerateToken {
    /// uidGenerateToken is a command that generates a new token using Akeyless Universal Identity.
    pub fn new(auth_method_name: String) -> UidGenerateToken {
        UidGenerateToken {
            auth_method_name,
            json: None,
            token: None,
            uid_token: None,
        }
    }
}

