/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UniversalIdentityAccessRules {
    #[serde(rename = "deny_inheritance", skip_serializing_if = "Option::is_none")]
    pub deny_inheritance: Option<bool>,
    #[serde(rename = "deny_rotate", skip_serializing_if = "Option::is_none")]
    pub deny_rotate: Option<bool>,
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i32>,
}

impl UniversalIdentityAccessRules {
    pub fn new() -> UniversalIdentityAccessRules {
        UniversalIdentityAccessRules {
            deny_inheritance: None,
            deny_rotate: None,
            ttl: None,
        }
    }
}

