/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateSecretVal {
    /// for personal password manager
    #[serde(rename = "accessibility", skip_serializing_if = "Option::is_none")]
    pub accessibility: Option<String>,
    /// For Password Management use, additional fields
    #[serde(rename = "custom-field", skip_serializing_if = "Option::is_none")]
    pub custom_field: Option<std::collections::HashMap<String, String>>,
    /// Secret format [text/json/key-value] (relevant only for type 'generic')
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<String>,
    /// For Password Management use, reflect the website context
    #[serde(rename = "inject-url", skip_serializing_if = "Option::is_none")]
    pub inject_url: Option<Vec<String>>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Whether to keep previous version [true/false]. If not set, use default according to account settings
    #[serde(rename = "keep-prev-version", skip_serializing_if = "Option::is_none")]
    pub keep_prev_version: Option<String>,
    /// The name of a key that used to encrypt the secret value (if empty, the account default protectionKey key will be used)
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// The last version number before the update
    #[serde(rename = "last-version", skip_serializing_if = "Option::is_none")]
    pub last_version: Option<i32>,
    /// The provided value is a multiline value (separated by '\\n')
    #[serde(rename = "multiline", skip_serializing_if = "Option::is_none")]
    pub multiline: Option<bool>,
    /// Secret name
    #[serde(rename = "name")]
    pub name: String,
    /// Deprecated
    #[serde(rename = "new-version", skip_serializing_if = "Option::is_none")]
    pub new_version: Option<bool>,
    /// For Password Management use, additional fields
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
    /// For Password Management use
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    /// The secret value (relevant only for type 'generic')
    #[serde(rename = "value")]
    pub value: String,
}

impl UpdateSecretVal {
    pub fn new(name: String, value: String) -> UpdateSecretVal {
        UpdateSecretVal {
            accessibility: None,
            custom_field: None,
            format: None,
            inject_url: None,
            json: None,
            keep_prev_version: None,
            key: None,
            last_version: None,
            multiline: None,
            name,
            new_version: None,
            password: None,
            token: None,
            uid_token: None,
            username: None,
            value,
        }
    }
}

