/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateWebTargetDetails {
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Whether to keep previous version [true/false]. If not set, use default according to account settings
    #[serde(rename = "keep-prev-version", skip_serializing_if = "Option::is_none")]
    pub keep_prev_version: Option<String>,
    /// Target name
    #[serde(rename = "name")]
    pub name: String,
    /// Deprecated
    #[serde(rename = "new-version", skip_serializing_if = "Option::is_none")]
    pub new_version: Option<bool>,
    /// The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)
    #[serde(rename = "protection_key", skip_serializing_if = "Option::is_none")]
    pub protection_key: Option<String>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl UpdateWebTargetDetails {
    pub fn new(name: String) -> UpdateWebTargetDetails {
        UpdateWebTargetDetails {
            json: None,
            keep_prev_version: None,
            name,
            new_version: None,
            protection_key: None,
            token: None,
            uid_token: None,
            url: None,
        }
    }
}

