/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateAuthMethodGcp : updateAuthMethodGCP is a command that updates a new auth method that will be able to authenticate using GCP IAM Service Account credentials or GCE instance credentials. [Deprecated: Use auth-method-update-gcp command]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAuthMethodGcp {
    /// Access expiration date in Unix timestamp (select 0 for access without expiry date)
    #[serde(rename = "access-expires", skip_serializing_if = "Option::is_none")]
    pub access_expires: Option<i64>,
    /// limit the auth method usage for specific client types [cli,ui,gateway-admin,sdk,mobile,extension]
    #[serde(rename = "allowed-client-type", skip_serializing_if = "Option::is_none")]
    pub allowed_client_type: Option<Vec<String>>,
    /// The audience to verify in the JWT received by the client
    #[serde(rename = "audience")]
    pub audience: String,
    /// Subclaims to include in audit logs, e.g \"--audit-logs-claims email --audit-logs-claims username\"
    #[serde(rename = "audit-logs-claims", skip_serializing_if = "Option::is_none")]
    pub audit_logs_claims: Option<Vec<String>>,
    /// A CIDR whitelist with the IPs that the access is restricted to
    #[serde(rename = "bound-ips", skip_serializing_if = "Option::is_none")]
    pub bound_ips: Option<Vec<String>>,
    /// A comma-separated list of GCP labels formatted as \"key:value\" strings that must be set on authorized GCE instances. TODO: Because GCP labels are not currently ACL'd ....
    #[serde(rename = "bound-labels", skip_serializing_if = "Option::is_none")]
    pub bound_labels: Option<Vec<String>>,
    /// === Human and Machine authentication section === Array of GCP project IDs. Only entities belonging to any of the provided projects can authenticate.
    #[serde(rename = "bound-projects", skip_serializing_if = "Option::is_none")]
    pub bound_projects: Option<Vec<String>>,
    /// List of regions that a GCE instance must belong to in order to be authenticated. TODO: If bound_instance_groups is provided, it is assumed to be a regional group and the group must belong to this region. If bound_zones are provided, this attribute is ignored.
    #[serde(rename = "bound-regions", skip_serializing_if = "Option::is_none")]
    pub bound_regions: Option<Vec<String>>,
    /// List of service accounts the service account must be part of in order to be authenticated.
    #[serde(rename = "bound-service-accounts", skip_serializing_if = "Option::is_none")]
    pub bound_service_accounts: Option<Vec<String>>,
    /// === Machine authentication section === List of zones that a GCE instance must belong to in order to be authenticated. TODO: If bound_instance_groups is provided, it is assumed to be a zonal group and the group must belong to this zone.
    #[serde(rename = "bound-zones", skip_serializing_if = "Option::is_none")]
    pub bound_zones: Option<Vec<String>>,
    /// Protection from accidental deletion of this object [true/false]
    #[serde(rename = "delete_protection", skip_serializing_if = "Option::is_none")]
    pub delete_protection: Option<String>,
    /// Auth Method description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// How many days before the expiration of the auth method would you like to be notified.
    #[serde(rename = "expiration-event-in", skip_serializing_if = "Option::is_none")]
    pub expiration_event_in: Option<Vec<String>>,
    /// if true: enforce role-association must include sub claims
    #[serde(rename = "force-sub-claims", skip_serializing_if = "Option::is_none")]
    pub force_sub_claims: Option<bool>,
    /// A CIDR whitelist with the GW IPs that the access is restricted to
    #[serde(rename = "gw-bound-ips", skip_serializing_if = "Option::is_none")]
    pub gw_bound_ips: Option<Vec<String>>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Jwt TTL
    #[serde(rename = "jwt-ttl", skip_serializing_if = "Option::is_none")]
    pub jwt_ttl: Option<i64>,
    /// Auth Method name
    #[serde(rename = "name")]
    pub name: String,
    /// Auth Method new name
    #[serde(rename = "new-name", skip_serializing_if = "Option::is_none")]
    pub new_name: Option<String>,
    /// Choose the relevant product type for the auth method [sm, sra, pm, dp, ca]
    #[serde(rename = "product-type", skip_serializing_if = "Option::is_none")]
    pub product_type: Option<Vec<String>>,
    /// ServiceAccount credentials data instead of giving a file path, base64 encoded
    #[serde(rename = "service-account-creds-data", skip_serializing_if = "Option::is_none")]
    pub service_account_creds_data: Option<String>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// Type of the GCP Access Rules
    #[serde(rename = "type")]
    pub r#type: String,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
    /// A unique identifier (ID) value which is a \"sub claim\" name that contains details uniquely identifying that resource. This \"sub claim\" is used to distinguish between different identities.
    #[serde(rename = "unique-identifier", skip_serializing_if = "Option::is_none")]
    pub unique_identifier: Option<String>,
}

impl UpdateAuthMethodGcp {
    /// updateAuthMethodGCP is a command that updates a new auth method that will be able to authenticate using GCP IAM Service Account credentials or GCE instance credentials. [Deprecated: Use auth-method-update-gcp command]
    pub fn new(audience: String, name: String, r#type: String) -> UpdateAuthMethodGcp {
        UpdateAuthMethodGcp {
            access_expires: None,
            allowed_client_type: None,
            audience,
            audit_logs_claims: None,
            bound_ips: None,
            bound_labels: None,
            bound_projects: None,
            bound_regions: None,
            bound_service_accounts: None,
            bound_zones: None,
            delete_protection: None,
            description: None,
            expiration_event_in: None,
            force_sub_claims: None,
            gw_bound_ips: None,
            json: None,
            jwt_ttl: None,
            name,
            new_name: None,
            product_type: None,
            service_account_creds_data: None,
            token: None,
            r#type,
            uid_token: None,
            unique_identifier: None,
        }
    }
}

