/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateEksTarget : updateEKSTarget is a command that updates an existing target. [Deprecated: Use target-update-eks command]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateEksTarget {
    /// Deprecated - use description
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    /// Description of the object
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Access Key ID
    #[serde(rename = "eks-access-key-id")]
    pub eks_access_key_id: String,
    /// EKS cluster CA certificate
    #[serde(rename = "eks-cluster-ca-cert")]
    pub eks_cluster_ca_cert: String,
    /// EKS cluster URL endpoint
    #[serde(rename = "eks-cluster-endpoint")]
    pub eks_cluster_endpoint: String,
    /// EKS cluster name
    #[serde(rename = "eks-cluster-name")]
    pub eks_cluster_name: String,
    /// Region
    #[serde(rename = "eks-region", skip_serializing_if = "Option::is_none")]
    pub eks_region: Option<String>,
    /// Secret Access Key
    #[serde(rename = "eks-secret-access-key")]
    pub eks_secret_access_key: String,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Whether to keep previous version [true/false]. If not set, use default according to account settings
    #[serde(rename = "keep-prev-version", skip_serializing_if = "Option::is_none")]
    pub keep_prev_version: Option<String>,
    /// The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Set the maximum number of versions, limited by the account settings defaults.
    #[serde(rename = "max-versions", skip_serializing_if = "Option::is_none")]
    pub max_versions: Option<String>,
    /// Target name
    #[serde(rename = "name")]
    pub name: String,
    /// New target name
    #[serde(rename = "new-name", skip_serializing_if = "Option::is_none")]
    pub new_name: Option<String>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
    /// Deprecated
    #[serde(rename = "update-version", skip_serializing_if = "Option::is_none")]
    pub update_version: Option<bool>,
    #[serde(rename = "use-gw-cloud-identity", skip_serializing_if = "Option::is_none")]
    pub use_gw_cloud_identity: Option<bool>,
}

impl UpdateEksTarget {
    /// updateEKSTarget is a command that updates an existing target. [Deprecated: Use target-update-eks command]
    pub fn new(eks_access_key_id: String, eks_cluster_ca_cert: String, eks_cluster_endpoint: String, eks_cluster_name: String, eks_secret_access_key: String, name: String) -> UpdateEksTarget {
        UpdateEksTarget {
            comment: None,
            description: None,
            eks_access_key_id,
            eks_cluster_ca_cert,
            eks_cluster_endpoint,
            eks_cluster_name,
            eks_region: None,
            eks_secret_access_key,
            json: None,
            keep_prev_version: None,
            key: None,
            max_versions: None,
            name,
            new_name: None,
            token: None,
            uid_token: None,
            update_version: None,
            use_gw_cloud_identity: None,
        }
    }
}

