/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateArtifactoryTarget : updateArtifactoryTarget is a command that updates a new target. [Deprecated: Use target-update-artifactory command]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateArtifactoryTarget {
    /// Artifactory Admin Name
    #[serde(rename = "artifactory-admin-name")]
    pub artifactory_admin_name: String,
    /// Artifactory Admin password
    #[serde(rename = "artifactory-admin-pwd")]
    pub artifactory_admin_pwd: String,
    /// Base URL
    #[serde(rename = "base-url")]
    pub base_url: String,
    /// Deprecated - use description
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    /// Description of the object
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Whether to keep previous version [true/false]. If not set, use default according to account settings
    #[serde(rename = "keep-prev-version", skip_serializing_if = "Option::is_none")]
    pub keep_prev_version: Option<String>,
    /// The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Set the maximum number of versions, limited by the account settings defaults.
    #[serde(rename = "max-versions", skip_serializing_if = "Option::is_none")]
    pub max_versions: Option<String>,
    /// Target name
    #[serde(rename = "name")]
    pub name: String,
    /// New target name
    #[serde(rename = "new-name", skip_serializing_if = "Option::is_none")]
    pub new_name: Option<String>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
    /// Deprecated
    #[serde(rename = "update-version", skip_serializing_if = "Option::is_none")]
    pub update_version: Option<bool>,
}

impl UpdateArtifactoryTarget {
    /// updateArtifactoryTarget is a command that updates a new target. [Deprecated: Use target-update-artifactory command]
    pub fn new(artifactory_admin_name: String, artifactory_admin_pwd: String, base_url: String, name: String) -> UpdateArtifactoryTarget {
        UpdateArtifactoryTarget {
            artifactory_admin_name,
            artifactory_admin_pwd,
            base_url,
            comment: None,
            description: None,
            json: None,
            keep_prev_version: None,
            key: None,
            max_versions: None,
            name,
            new_name: None,
            token: None,
            uid_token: None,
            update_version: None,
        }
    }
}

