/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateGodaddyTargetOutput {
    #[serde(rename = "target_id", skip_serializing_if = "Option::is_none")]
    pub target_id: Option<i64>,
}

impl UpdateGodaddyTargetOutput {
    pub fn new() -> UpdateGodaddyTargetOutput {
        UpdateGodaddyTargetOutput {
            target_id: None,
        }
    }
}

