/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateAssoc : updateAssoc is a command that updates the sub-claims of an association between role and auth method.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAssoc {
    /// The association id to be updated
    #[serde(rename = "assoc-id")]
    pub assoc_id: String,
    /// Treat sub claims as case-sensitive [true/false]
    #[serde(rename = "case-sensitive", skip_serializing_if = "Option::is_none")]
    pub case_sensitive: Option<String>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// key/val of sub claims, e.g group=admins,developers
    #[serde(rename = "sub-claims", skip_serializing_if = "Option::is_none")]
    pub sub_claims: Option<std::collections::HashMap<String, String>>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl UpdateAssoc {
    /// updateAssoc is a command that updates the sub-claims of an association between role and auth method.
    pub fn new(assoc_id: String) -> UpdateAssoc {
        UpdateAssoc {
            assoc_id,
            case_sensitive: None,
            json: None,
            sub_claims: None,
            token: None,
            uid_token: None,
        }
    }
}

