/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageEventSetting {
    #[serde(rename = "enable", skip_serializing_if = "Option::is_none")]
    pub enable: Option<bool>,
    #[serde(rename = "enable_time", skip_serializing_if = "Option::is_none")]
    pub enable_time: Option<String>,
    #[serde(rename = "interval_by_days", skip_serializing_if = "Option::is_none")]
    pub interval_by_days: Option<i64>,
}

impl UsageEventSetting {
    pub fn new() -> UsageEventSetting {
        UsageEventSetting {
            enable: None,
            enable_time: None,
            interval_by_days: None,
        }
    }
}

