/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UscSyncInfo {
    #[serde(rename = "delete_remote", skip_serializing_if = "Option::is_none")]
    pub delete_remote: Option<bool>,
    #[serde(rename = "jq_secret_filter", skip_serializing_if = "Option::is_none")]
    pub jq_secret_filter: Option<String>,
    #[serde(rename = "last_error", skip_serializing_if = "Option::is_none")]
    pub last_error: Option<String>,
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    #[serde(rename = "secret_id", skip_serializing_if = "Option::is_none")]
    pub secret_id: Option<String>,
    #[serde(rename = "secret_name", skip_serializing_if = "Option::is_none")]
    pub secret_name: Option<String>,
}

impl UscSyncInfo {
    pub fn new() -> UscSyncInfo {
        UscSyncInfo {
            delete_remote: None,
            jq_secret_filter: None,
            last_error: None,
            namespace: None,
            secret_id: None,
            secret_name: None,
        }
    }
}

