/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UscListSecretsOutput {
    #[serde(rename = "secrets_list", skip_serializing_if = "Option::is_none")]
    pub secrets_list: Option<Vec<models::SecretInfo>>,
}

impl UscListSecretsOutput {
    pub fn new() -> UscListSecretsOutput {
        UscListSecretsOutput {
            secrets_list: None,
        }
    }
}

