/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UscCreateSecretOutput {
    #[serde(rename = "secret_id", skip_serializing_if = "Option::is_none")]
    pub secret_id: Option<String>,
    #[serde(rename = "version_id", skip_serializing_if = "Option::is_none")]
    pub version_id: Option<String>,
}

impl UscCreateSecretOutput {
    pub fn new() -> UscCreateSecretOutput {
        UscCreateSecretOutput {
            secret_id: None,
            version_id: None,
        }
    }
}

