/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ValidateCertificateChallenge : ValidateCertificateChallenge validates HTTP-01 challenge and finalizes certificate issuance (Phase 2)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidateCertificateChallenge {
    #[serde(rename = "Result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<models::ValidateCertificateChallengeOutput>>,
    /// Certificate display ID from Phase 1
    #[serde(rename = "cert-display-id", skip_serializing_if = "Option::is_none")]
    pub cert_display_id: Option<String>,
    /// Set output format to JSON
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<bool>,
    /// Certificate name (alternative to cert-display-id)
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Validation timeout in seconds
    #[serde(rename = "timeout", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<i64>,
    /// Authentication token (see `/auth` and `/configure`)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The universal identity token, Required only for universal_identity authentication
    #[serde(rename = "uid-token", skip_serializing_if = "Option::is_none")]
    pub uid_token: Option<String>,
}

impl ValidateCertificateChallenge {
    /// ValidateCertificateChallenge validates HTTP-01 challenge and finalizes certificate issuance (Phase 2)
    pub fn new() -> ValidateCertificateChallenge {
        ValidateCertificateChallenge {
            result: None,
            cert_display_id: None,
            json: None,
            name: None,
            timeout: None,
            token: None,
            uid_token: None,
        }
    }
}

