/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VenafiTargetDetails {
    #[serde(rename = "venafi_api_key", skip_serializing_if = "Option::is_none")]
    pub venafi_api_key: Option<String>,
    #[serde(rename = "venafi_base_url", skip_serializing_if = "Option::is_none")]
    pub venafi_base_url: Option<String>,
    #[serde(rename = "venafi_tpp_access_token", skip_serializing_if = "Option::is_none")]
    pub venafi_tpp_access_token: Option<String>,
    #[serde(rename = "venafi_tpp_client_id", skip_serializing_if = "Option::is_none")]
    pub venafi_tpp_client_id: Option<String>,
    /// Deprecated: VenafiAccessToken and VenafiRefreshToken should be used instead
    #[serde(rename = "venafi_tpp_password", skip_serializing_if = "Option::is_none")]
    pub venafi_tpp_password: Option<String>,
    #[serde(rename = "venafi_tpp_refresh_token", skip_serializing_if = "Option::is_none")]
    pub venafi_tpp_refresh_token: Option<String>,
    /// Deprecated: VenafiAccessToken and VenafiRefreshToken should be used instead
    #[serde(rename = "venafi_tpp_username", skip_serializing_if = "Option::is_none")]
    pub venafi_tpp_username: Option<String>,
    #[serde(rename = "venafi_use_tpp", skip_serializing_if = "Option::is_none")]
    pub venafi_use_tpp: Option<bool>,
    #[serde(rename = "venafi_zone", skip_serializing_if = "Option::is_none")]
    pub venafi_zone: Option<String>,
}

impl VenafiTargetDetails {
    pub fn new() -> VenafiTargetDetails {
        VenafiTargetDetails {
            venafi_api_key: None,
            venafi_base_url: None,
            venafi_tpp_access_token: None,
            venafi_tpp_client_id: None,
            venafi_tpp_password: None,
            venafi_tpp_refresh_token: None,
            venafi_tpp_username: None,
            venafi_use_tpp: None,
            venafi_zone: None,
        }
    }
}

