/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WindowsServiceAttributes {
    #[serde(rename = "connection_type", skip_serializing_if = "Option::is_none")]
    pub connection_type: Option<String>,
    /// IISAppPool marks this entry as an IIS Application Pool rather than a Windows Service
    #[serde(rename = "iis_app_pool", skip_serializing_if = "Option::is_none")]
    pub iis_app_pool: Option<bool>,
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<String>,
    /// SkipRestart allows skipping recycle/start of the IIS App Pool after credential update
    #[serde(rename = "skip_restart", skip_serializing_if = "Option::is_none")]
    pub skip_restart: Option<bool>,
    #[serde(rename = "use_tls", skip_serializing_if = "Option::is_none")]
    pub use_tls: Option<bool>,
}

impl WindowsServiceAttributes {
    pub fn new() -> WindowsServiceAttributes {
        WindowsServiceAttributes {
            connection_type: None,
            iis_app_pool: None,
            port: None,
            skip_restart: None,
            use_tls: None,
        }
    }
}

